### ISSUE TITLE
Link til digitale planer - Odeum

### ISSUE THREAD

**Issue by clausmegaard** [Septima/spatialsuite-s4#102]
Horsens benytter "Odeum" til digitale planer.

Hvis der findes en digital plan vil vi foretrække at S4 resultatet linker til den digitale plan, frem for pdf-udgaven på plansystemet.

I SpatialSuite-presentation er det løst ved at "skifte" linket til  
```xml
<column format="hyperlink" name="37">
  <label>'Plandokument'</label>
  <value>'http://plandk2.mapcentia.com/apps/custom/planurl/public/index.php/api/v1/url/horsens/lokalplaner.lpplandk2_join/' + planid</value>
  <condition>IsDefined(planid)</condition>
</column>
```
Se f.eks *lokalplan 2014-2 BOLIGER, DAHLIAVEJ, HORSENS*
Digital plan:
http://plandk2.mapcentia.com/apps/custom/planurl/public/index.php/api/v1/url/horsens/lokalplaner.lpplandk2_join/2849799

PDF-plan:
http://soap.plansystem.dk/pdfarchive/20_2849799_1412771375722.pdf

Kan vi/I ændre linket i S4-presentation'en også?

**Comment by klavspc** [comment]
Du må meget gerne sende mig datasource- og endpointdefinition for Odeumplaner, samt den fulde version af den presesentation du nævner. (klavs@septima.dk)

Ligger alle Horsens' godkendte lokalplaner i Odeum eller er det kun nogen af dem?
* Hvis alle ligger der kan vi overveje at lave en decideret Odeum-plugin til s4.
* Hvis det kun er nogen, der ligger i Odeum skal vi, for hver plan, forespørge Odeum om den ligger dér.   

I begge tilfælde skal vi bruge en service-snitflade mod Odeum. Jeg vil dog gerne klædes på inden jeg taler med Martin Høegh

**Comment by clausmegaard** [comment]
Vores datasource- og endpoint peger stadig på plansystem.dk

Fra datasource:
```xml 
<endpoint name="plansystem_wms" endpointtype="wms">
    <service>http://kort.plansystem.dk/wms</service>
    <parameters>
         <servicename>wms</servicename>
    </parameters>
</endpoint>
<endpoint name="plansystem_wfs" endpointtype="wfs">
   <service>http://geoservice.plansystem.dk/wfs</service>
   <kvpbboxencoding>bbox</kvpbboxencoding>
   <parameters>
       <maxfeatures>10000</maxfeatures>
   </parameters>
</endpoint>

<datasource name="plansystem_lokalplan-vedtaget" endpoint="plansystem_wms">
   <wms>
      <layers>theme-pdk-lokalplan-vedtaget</layers>
      <format>image/PNG</format>
      <transparent>true</transparent>
   </wms>
</datasource>
<datasource name="plansystem_wfs_lokalplan-vedtaget" endpoint="plansystem_wfs">
   <wfs geometrycolumn="GEOMETRI">
      <typename>pdk:theme_pdk_lokalplan_vedtaget_v</typename>
   </wfs>
</datasource>
```

Jeg har sendt den fulde presentation til dig som mail. Den eneste forskel fra standard datamodulet er at vi har ændret link-kolonnen med vores eget link.

Hvis man kalder nævnte link med et gyldigt planid, bliver man ledt hen til den relevante plan (hvad enten det er en flad pdf eller en digital plan) 
Fx
http://plandk2.mapcentia.com/apps/custom/planurl/public/index.php/api/v1/url/horsens/lokalplaner.lpplandk2_join/2860765
eller
http://plandk2.mapcentia.com/apps/custom/planurl/public/index.php/api/v1/url/horsens/lokalplaner.lpplandk2_join/2849799

Hvis det "kun" var Horsens I indekserede, burde det være nok at lave samme ændring i jeres S4-presentation'en. 

Men jeg kan godt se udfordringen for jeres indexering, da der jo også er planer uden for Horsens kommune...  Men I må jo have kommune-informationen når I kan filtrere søgningerne..

Derudover har vi ikke noget at udsætte på indexerings arbejdet og den tilhørende søgning. Så vi vil  helst hvis det kunne løses i jeres indexering af lokalplanerne, så vi slipper for det ;-).

**Comment by klavspc** [comment]
Jeg er ved at være klar over hvordan det skal skrues sammen.
* Knappen til pdf-linket skal tages ud af s4 og være et selvstændigt plugin ligesom E-Knappen feks er det.
* Så kan man bruge standard plugin mod Plansystemet og dem, der har Odeum, vil bruge et Odeum-plugin.

Der ligger nok en halv dag, måske lidt mere, i opgaven hvis den udføres ifbm en release. Hvor mange s4-kunder har Odeum og ville evt. være med på det?

**Comment by renolindberg** [comment]
Mange kommuner har NIRAS løsning for digitale lokalplaner. Måske et "odeum pluin", skulle tænkes bredere, så man forbereder den, så der let kan anvendes andre løsninger?

**Comment by klavspc** [comment]
Der skal laves et separat plugin til hvert system. Halvdelen af arbejdet med den første, Odeum, er at flytte pdf-knappen ud af s4 og und i en plugin. Derefter vil efterfølgende plan-plugins tage tage maks to timer, som inkluderer at de får eget ikon. Således vil Plansystem-pdf. Odeum, Niras og efterfølgende få egne ikoner.

**Comment by gis-haderslev** [comment]
Vi er med på det. Og vi bruger Odeum.

**Comment by clausmegaard** [comment]
Jeg forhørte mig lige ved Cowi for at høre hvilke kommuner, der ellers benytter Odeum til digitale lokalplaner, det er:
Holbæk Kommune
Lyngby-Taarbæk Kommune
Odder Kommune
Samsø Kommune

På vej i gang:
Randers Kommune
Frederikssund Kommune

**Comment by klavspc** [comment]
Inkludér i profil:  
```xml
<tool module="s4" name="s4-odeum-plugin" />
```  
Sæt følgende parameter for at pluginnet virker:  
```xml
<param name="s4.odeumClientName">odeumClientName</param>
```  
, hvor _odeumClientName_ er den del af urlen som bruges i ODEUM til din kommune. For url'en _http://plandk2.mapcentia.com/apps/custom/planurl/public/index.php/api/v1/url/horsens/lokalplaner.lpplandk2_join/xxx_ er det _horsens_.
