### ISSUE TITLE
Link til digitale planer - Niras

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#103]
Se #102 for baggrundsinfo.
Niras-plugin til Plansøgeren med eget ikon - to timer, hvis #102 er udført først

**Comment by renolindberg** [comment]
De 2 timer kaster vi gerne i puljen :-)

**Comment by klavspc** [comment]
Er der en Niras-kunde, der kan hjælpe med et passende ikon, ca 20*20, som kan bruges som link til lokalplanen i Niras' system?

**Comment by klavspc** [comment]
Jeg har afklaret med Niras hvordan der skal linkes til DKplan.
Er det kun internt i vil bruge linket eller skal borgere også blive ledt til DKplan når en lokalplan er valgt?

**Comment by klavspc** [comment]
Inkludér i profil:
```xml
<tool module="s4" name="s4-dkPlan-plugin" />
```  
Sæt følgende parameter for at pluginnet virker:  
```xml
<param name="s4.dkPlanClientName">dkPlanClientName</param>
```  
, hvor _dkPlanClientName_ er den del af urlen som bruges i din kommune. For url'en _http://silkeborglokalplaner.viewer.dkplan.niras.dk/dkplan/dkplan.aspx?LokalplanNr=xxx_ er det _silkeborglokalplaner_.
