### ISSUE TITLE
Håndtere javascript-links i presentation (Bl.a. til Acadre)

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#108]
I dag håndteres almindelige hyperlinks. Der har vist sig et behov for at håndtere javascript-links (Link til Acadre)

**Comment by klavspc** [comment]
4-6 timer

**Comment by rastermanden** [comment]
Acadre link ser således ud:

```xml
<column format="hyperlink">
	    <label>'Vis i Acadre'</label>
	    <value>"javascript:esdhSearchSingle('" + locid + "');"</value>
	    <condition/>
</column>

```

**Comment by klavspc** [comment]
Jeg vil implementere link til Acadre som et plug-in, ligesom E-Knap, OIS-link og mange andre. Det er mere fleksibelt end at skrive i presentation.

**Comment by klavspc** [comment]
Formatet bliver, at javascript skal skrives således:  
```xml
<column format="javascriptlink">
  <label>'Vis i Acadre'</label>
  <value>"esdhSearchSingle('" + locid + "');"</value>
</column>
```
