### ISSUE TITLE
søgning i temaer/arbejdsområder mv - der indeholder parenteser

### ISSUE THREAD

**Issue by dikkri** [Septima/spatialsuite-s4#110]
S4 fungerer ikke optimalt når man søger på ord, der er indeholdt i en parentes. Fx i arbejdsområder. Her bruger vi ofte vores initialer til at søge efter fx dikkri - men i titlen på arbejdsområdet står initialerne i parentes (dikkri). Søger man i S4 efter kkri så finder man ikke sine områder.  Skal man søge på noget der står i en parentes så skal man skrive ordet fuldt ud - her skal skrives dikkri for at finde alle sine områder.
Kan S4 tilrettes så man også kan søge på dele af et ord inde i parenteser?

**Comment by gis-haderslev** [comment]
Hermed eksempler på Arbejdområder:

![s4_ao_par_4](https://cloud.githubusercontent.com/assets/8122296/6410997/65563fdc-be74-11e4-9603-03731be3956b.PNG)
![s4_ao_par](https://cloud.githubusercontent.com/assets/8122296/6410999/655c77da-be74-11e4-972d-993c26cd14c4.PNG)
![s4_ao_par_1](https://cloud.githubusercontent.com/assets/8122296/6410998/655c21b8-be74-11e4-8e0d-b05679c88c07.PNG)
![s4_ao_par_2](https://cloud.githubusercontent.com/assets/8122296/6411001/655ebee6-be74-11e4-9a3f-f33851f771fb.PNG)
![s4_ao_par_3](https://cloud.githubusercontent.com/assets/8122296/6411000/655cb51a-be74-11e4-9f23-d4821cfb83f5.PNG)

**Comment by gis-haderslev** [comment]
Det virker lidt anderledes ved søgning i temaer
![s4_par_bag](https://cloud.githubusercontent.com/assets/8122296/6411035/ae772172-be74-11e4-942e-088e60268b7e.PNG)
![s4_uden_par](https://cloud.githubusercontent.com/assets/8122296/6411037/ae7b1386-be74-11e4-933d-847d1986ed6f.PNG)
![s4_par_for](https://cloud.githubusercontent.com/assets/8122296/6411036/ae79ba5e-be74-11e4-9cda-7f3a66c4d7a6.PNG)

**Comment by klavspc** [comment]
Septima Search, og dermed S4, matcher altid fra starten af ord. Der matches på alle ord i sætninger, men altså kun fra starten af ordene.

Arbejdsområder:
S4 søger i felterne titel og inititaler, hvor titel er konstrueret af _navn_ (_initialer_)
* Når der således søges på enten _"(dison"_ eller _"dison"_ vil arbejdsområdet blive fundet (fra hhv titel og initialer)
* Når der søges på _"ison"_ vil det ikke blive fundet da det ikke er starten af hverken navn eller initialer.

Temaer
* Når DAI-temaerne findes ved at skrive _"(DAI"_ er det fordi ordet _(DAI)_ indgår i temaets eller temagruppens navn. Alle temaer er, som man kan se, efterfulgt af ordet _(DAI)_
* Når der søges på _"DAI"_ findes de ikke da det ikke er starten af et ord i temaets navn.

Opførslen er helt konsekvent i Septima Search, S4. Vi kan sagtens se på om der også skal matches inden i ord. Det vil dog være en større udvidelse:
* Dels skal der helt sikkert skulle indtastes minimum tre bogstaver, Hvis ét bogstav var nok vil alting stort set blive fundet så snart man har skrevet feks. _"k"_.
* Dels skal søgningen ombygges for at performance ikke skal rammes negativt. Det er dyrere at kigge inden i alle ord end kun starten af ord. (At kigge i starten understøttes direkte af database-indexer)

**Comment by gis-haderslev** [comment]
Tak for forklaringen, det giver menning. Det kan godt være at S4 skal ikke kigge inden i alle ord, men behandler kun de tilfælde hvor ordet starter med parantese eller anden special symbol som for eksempel ' " / { osv.
