### ISSUE TITLE
pages.xml

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-s4#112]
Hej Grontmij.

Har lige hentet 2.2.6 fra https://github.com/Septima/spatialsuite-s4/archive/2.2.6.zip
Mangler følgende ikke i pages.xml?
    <page name="s4getkmsticket" contenttype="text/xml">
        <data handler="expression" operation="evaluate">
            <url-parameters>
                <url-parameter name="expression">'getKmsTicket("[s4.gst.login]","[s4.gst.password]", true)'</url-parameter>
            </url-parameters>
        </data>
    </page>

**Comment by moelgaard730** [comment]
GITHUB snuppede lige noget af min tekst
    page name="s4getkmsticket" contenttype="text/xml"
        data handler="expression" operation="evaluate"
            url-parameters
                url-parameter name="expression">'getKmsTicket("[s4.gst.login]","[s4.gst.password]", true)'</url-parameter
            /url-parameters
        /data
    /page

**Comment by klavspc** [comment]
Nej - Den page er udgået. Fejler kaldene til geosearch?

*Klavs Pihlkjær Christensen*
Partner, seniorkonsulent
+45 9132 6946
klavs@septima.dk
--------------------------
Septima P/S
Frederiksberggade 28, 2.tv
1459 Kbh K
www.septima.dk

2015-03-12 14:50 GMT+01:00 Kåre Rasmussen <notifications@github.com>:
