### ISSUE TITLE
Sortering af adresser og matrikler

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#114]
Modtaget via mail:

I dag vises adresserne og matrikel. nr i S4 i en noget rodet rækkefølge kan jeg ændre på det?

![image](https://cloud.githubusercontent.com/assets/3736091/6776406/50a1b01c-d13e-11e4-80c3-15a5e016605a.png)
![image](https://cloud.githubusercontent.com/assets/3736091/6776414/5b2fee90-d13e-11e4-89b1-b3722de367d4.png)

**Comment by klavspc** [comment]
Adresse- og matrikelresultater vises som de returneres fra gst's geosearch. Det vil derfor være dem, der skal kontaktes mht sortering. Når det er sagt har jeg to bemærkninger:
* Jeg synes, at adresserne sorterer meget godt. De er vægtet efter hvor godt de matcher søgestrengen
* Matriklernes sortering er ikke indlysende. De matcher alle Mellerup og kunne være sorteret efter feks matrikelnummer.

Senere i år udgår smartadresse, som er den service, der anvendes i geosearch. Den erstattes af [Danmarks Adressers Web API](http://dawa.aws.dk/). Dawa tilbyder ikke samme funktioner som smartadresse og vi vil snart begynde at overveje om dawa er det korrekte valg til s4 eller om vi skal finde på noget andet. Der vil snart blive oprettet relevante issues i dette forum til en diskussion af dette.

**Comment by cfischer00** [comment]
@klavspc : Det ser nu alligevel lidt mærkeligt ud. Hvis jeg forsøger:
http://kortforsyningen.kms.dk/Geosearch?search=mellerup&resources=matrikelnumre&limit=100&login=septima&password=[septimapwdhere]

Får jeg en anden sortering på matrikelnumre.

Adressedelen kikser også 8C skulle være mellem 8B og 8D - så vidt jeg kan se, er sorteringen en anden gennem GeoSearch.

Jeg kan ikke gennemskue hvor forskellen ligger.

**Comment by klavspc** [comment]
DAWA kommer snart i s4 og vi har ikke hørt mere til sortering. Issuet lukkes
