### ISSUE TITLE
GST's Geosearch fejler

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#115]
Søgninger mod Geosearch er ustabile i dag onsdag d. 25 marts.

S4 bruger Geosearch til søgning i adresser, matrikler og DAGI.

Desværre er Kortforsyningens hjemmeside nede så det ikke er muligt at se status for deres services

**Comment by gis-haderslev** [comment]
Det gør meget besværligt at bruge S4, hvis vi skal skifte manuelt  i config filen mellem geosearch og vores egne indeks. Der skal findes en løsning, hvor det kan gøres automatisk.

**Comment by gis-haderslev** [comment]
Det sker alt for tit på det sidste.

**Comment by klavspc** [comment]
Så er geosearch oppe at køre igen
