### ISSUE TITLE
Kunne bestemme ikon for indekserede spatial suite data (s4-index)

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#116]
I config.xml for indekset skal der kunne angives et ikon for hver datasource. Så kan man feks få et skole-ikon ud for s4 skole-resultater.

6 timer

**Comment by gis-haderslev** [comment]
Vi er med

**Comment by klavspc** [comment]
Kun Haderslev har meldt sig som interesseret. Er der andre, der er interesserede? Vil du være interesseret, @gis-haderslev, selvom ingen andre springer på?

**Comment by gis-haderslev** [comment]
Du får svar meget snart. Skal lige drøfte med kollegaerne hvor vigtig det er.
