### ISSUE TITLE
Kunne tænde tema når man har fundet noget.

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#117]
Hvis man ekempelvis har fremsøgt en skole skal man tilbydes at kunne tænde for temaet _Skoler_. Det kan gøres ved _enten_ at
* i config.xml ud for en datasource at give mulighed for at kunne angive navnet på et tema _eller_
* s4 automatisk kigger temaerne igennem og finder de temaer, der indeholder datasourcen

Fordelen ved det sidste alternativ er at der ikke er nogen opsætning.

Når s4 har fundet et tema, der indeholder Skole, så skal der vises en tema-knap ud for skolen, der kan tænde temaet.

8 - 12 timer

**Comment by mwtishoj** [comment]
Det lyder spændende, hvad gøres, når det man har søgt på findes i flere temaer?

**Comment by klavspc** [comment]
Så skal alle temaerne vises med mulighed for at tænde dem enkeltvis

*Klavs Pihlkjær Christensen*
Partner, seniorkonsulent
+45 9132 6946
klavs@septima.dk
--------------------------
Septima P/S
Frederiksberggade 28, 2. tv
1459 Kbh K
www.septima.dk

2015-09-25 9:24 GMT+02:00 Mik Wulff Thomsen <notifications@github.com>:

**Comment by mwtishoj** [comment]
Hvormange timer vil det tage?

**Comment by gis-haderslev** [comment]
God ide! Vi kunne også være interesseret. Kommer an på prisen.
