### ISSUE TITLE
Felstavat i den svenska översättningen av S4

### ISSUE THREAD

**Issue by BoStenungsundsKommun** [Septima/spatialsuite-s4#118]
Detta är den korrekta stavningen: s4.themesearcher.visiblethemes = T\u00e4nda teman

**Comment by klavspc** [comment]
Tak Bo. Jeg retter i næste version. Klavs

Klavs Pihlkjær Christensen
Partner, seniorkonsulent
+45 9132 6946
klavs@septima.dk
--------------------------
Septima P/S
Frederiksberggade 28, 2.tv
1459 Kbh K
www.septima.dk
