### ISSUE TITLE
Opdatere dokumentation af s4-indeks med feltstørrelser

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#119]
Beskriv gældende begrænsninger af feltstørrelser i s4's indeks.

De fleste strenge er defineret til at måtte være 255 tegn, hvilket er alt rigeligt. I presentations kan strenge trunkeres med SUBSTR. Her er er eksempel, hvor sagstitel trunkeres til 250 tegn. (250 er stadig alt for langt til en titel, som måske bør være ca 40 tegn)
```xml
<column format='heading'>
  <label></label>
  <value>SUBSTR(TOSTRING(sagstitel),1,250)</value>
</column>
```
De felter, der oftest volder problemer er title og description

Dette er feltstørrelserne (Skal skrives ind i dokumentationen i læselig form)
datasource.id varchar(255)
featuretypesingle varchar(255)
featuretypeplural varchar(255))
title varchar(255)
description varchar(255)
wkt varchar(100000)
term varchar(255)

**Comment by moelgaard730** [comment]
Hej Klavs.
Jeg har nu oprettet et view på en datasource for at begrænse mængden af data. Viewet ser således ud:
CREATE OR REPLACE VIEW v_ds_beskyttede_naturtyper_kpmaal_a_s4 AS 
 SELECT beskyttede_naturtyper.wkb_geometry, beskyttede_naturtyper.adm_kode,beskyttede_naturtyper.ogc_fid
   FROM beskyttede_naturtyper
  WHERE beskyttede_naturtyper.kp_maalsaetning::text = 'A'::text;

Min presentation ser således ud:
<?xml version="1.0" encoding="ISO-8859-1"?>
<presentation>
    <text name="overskrift" plural="kpmaalaer" value="kpmaala"/>
    <columns>
        <column format="heading">
            <label>'' + adm_kode</label>
            <value></value>
        </column>
    </columns>
</presentation>
Jeg har vedhæftet et billede med de data der findes i viewet. Som du kan se, så er der kun tallet 730 i adm_kode. Og feltet er varchar, så jeg er lidt på bar bund, hvorfor jeg får:
data exception: string data, right truncation, når jeg forsøger at indexsere.
![klavs_s4](https://cloud.githubusercontent.com/assets/6029987/7276718/02dec078-e90c-11e4-94c9-638b47621516.png)

**Comment by moelgaard730** [comment]
Hej igen Klavs.
Kan problemet være, at S4 forsøger at læse shape_wkt og i den forbindelse læser mere end de 250 tegn? Jeg ændret mit view, så den sender centroiden videre i stedet for hele polygonen - og nu går det godt.

Mvh.
Kåre

**Comment by moelgaard730** [comment]
Hej Klavs.

Lad mig præsenterer dig for en geometri, der omdannet til wkt fylder 144850 karakterer :-)
![144850](https://cloud.githubusercontent.com/assets/6029987/7297972/c9594c6c-e9cc-11e4-95f0-89914fec8858.png)

**Comment by moelgaard730** [comment]
Hej Klavs.

I forhold til, om der skal oprettes et view til data eller ej (for at reducere mængde af data som S4 skal arbejde med), kan man så forstille sig det gjort med en inputdatasource ala:

<datasource name="datasource_med_faa_kolonner">
	<inputdatasource>datasource_med_mange_kolonner</inputdatasource>
	<columns appendcolumns="false">
		<column name="geometry" type="geometry">shape_wkt</column>
		<column name="plannavn">if isDefined(plannavn) then plannavn else "" endif</column>
		<column name="planid">if isDefined(planid) then planid else "" endif</column>
	</columns>   
</datasource>
Det tænker jeg var den nemmeste og hurtigste løsninger, frem for, at skulle lave et view.
Lad mig høre, hvad du mener

Mvh.
Kåre

**Comment by klavspc** [comment]
Ja, det var en stor geometri. wkt er ligenu begrænset til 100.000 tegn i
S4's index.Vi kan sagtens hæve den grænse i en senere release.

**Comment by moelgaard730** [comment]
Det tror jeg bliver nødvendigt. Jeg har lige kigget i vores park data. Der er to geometrier (henholdsvis 114k og 150k), som ikke kan håndteres. 150k er vedhæftet.

Mvh.
Kåre
![150786](https://cloud.githubusercontent.com/assets/6029987/7298469/0cf2277a-e9d0-11e4-9c80-b9724050c776.png)
