### ISSUE TITLE
Favoritter respekterer ikke temaer der er tændt via S4

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#120]
Randers melder:

Jeg har erfaret, at når man tænder temaer via S4 og dermed også bliver vist som tændt i temavælgeren, ja så betyder det ikke at systemet opfatter dem som tændte – når jeg gemmer dem som favoritter. Kan I give mig en god begrundelse for det. Kan I aktivere temaerne på en anden måde, så CBkort ved de er tændt?

**Comment by klavspc** [comment]
Kan ikke genskabe det i har set. Hvis i stadig kan oplever problemet så notér venligst version af Spatial Suite og gerne info om hvilket lag, som ikke gemmes med favoritten. Gerne et lag som er med i standard Spatial Suite; det vil lette min fejlfinding.

**Comment by gis-haderslev** [comment]
Vi har samme problem :( 
SpatialSuite 3.9.1
S4 2.2.62

**Comment by klavspc** [comment]
ThemeSearcher:
       	if (typeof cbKort.themeSelector.setSpatialMapState !== 'undefined'){
            	cbKort.themeSelector.setSpatialMapState();
       	}
