### ISSUE TITLE
JS fejl i S4

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-s4#121]
Hej Septima. 
Jeg oplever følgende JavaScript fejl i forbindelse med S4
![s4_fejl_20150601](https://cloud.githubusercontent.com/assets/6029987/7911397/97192920-085d-11e5-846c-bc6398437809.png)

**Comment by klavspc** [comment]
Er det en fejl jeg kan genskabe på ydersiden hos jer så jeg kan se den? Hvis ikke så fortæl mig hvilken version af s4 og Spatial Suite I bruger og send mig en kopi af jeres custom tool.

**Comment by moelgaard730** [comment]
Hej Klavs.

Vi har endnu ikke rykket S4 ud på webkortet, så informationerne kommer her:
S4: version 2.2.6
SpatialSuite: version 3.9.0


Fra: Klavs Pihlkjær [mailto:notifications@github.com]
Sendt: 1. juni 2015 13:41
Til: Septima/spatialsuite-s4
Cc: Kåre Mølgaard Rasmussen
Emne: Re: [spatialsuite-s4] JS fejl i S4 (#121)


Er det en fejl jeg kan genskabe på ydersiden hos jer så jeg kan se den? Hvis ikke så fortæl mig hvilken version af s4 og Spatial Suite I bruger og send mig en kopi af jeres custom tool.

**Comment by klavspc** [comment]
Jeg har været inde på jeres server og fandt en fejl i s4, der udløser dette. Jeg vil snarest udsende en lille opdatering, der løser denne fejl. Det bliver formodentlig på torsdag.

**Comment by klavspc** [comment]
Note: jsts allerede defineret før searcher.preparejsts()
