### ISSUE TITLE
Kan S4 søge på en del af et ord evt. med %?

### ISSUE THREAD

**Issue by mwtishoj** [Septima/spatialsuite-s4#124]
Jeg synes ikke at jeg kan søge på en del af et ord via s4 , hvor man bruger "%"  

eks. %park%, så den finder strandpark.

Det skal også gælde i lokalplanerne.

**Comment by klavspc** [comment]
S4 søger i starten af alle ord..

Vi er ved at undersøge mulighederne for at matche vilkårligt i teksten på indekserede objekter, men indtil nu er teknologien ikke klar. Det kan sagtens lade sig gøre, men performance på søgninger er blevet så dårlig, at det praktisk taget er ubrugeligt.

Der er dog ved at vise sig nogle nye muligheder og dem vil vi evaluere og udnytte.

**Comment by gis-haderslev** [comment]
Den kunne evt. betragtes som alternativ langsom søgning?
Et specialtegn (fx %) i S4 feltet, der indikere at man vil søge på wildcard, så kører søgningen meget langsomt - men så er klar vi over det.

**Comment by mwtishoj** [comment]
Vi er med på noget finansiering. 
Er det muligt, at der kan blive estimeret et antal timer for opgaven?

**Comment by klavspc** [comment]
Den er ikke nem. Der bliver trukket fra en del services og det er kun dem vi selv har kontrol over som evt vil kunne bringes til det. Geosearch og DAWA har det ikke. Undersøgelsen og udtænkning af en løsning og estimat kan tage et par timer uden, at der nødvendigvis kommer noget brugbart ud af det. Skal vi lægge et par timer for at se hvad man kan? Det vil blive en time til jer hver @mwtishoj og @mwtishoj. Måske uden at vi kommer videre.

**Comment by mwtishoj** [comment]
Det er fint

**Comment by gis-haderslev** [comment]
Hej Klaus du mente en time til @mwtishoj  og en time til @gis-Haderslev. 
Det er også fint for mig.
