### ISSUE TITLE
Detaljeret  visning hopper og danser

### ISSUE THREAD

**Issue by mwtishoj** [Septima/spatialsuite-s4#128]
Når jeg har søgt på et ord, eks. "matrikel", så kommer der en liste frem på ca. 10 stk., hvis jeg gerne vil se detaljeret info om temaet ved at klikke på pilen, så dukker info kort op, neden under resultatlisten(uden at man kan nå at læse detaljerne) og andre gange selvstændigt lige under søgeboksen. 

Kan det ændres, så det bare vises lige under det tema, som man ønsker at få vist detaljerne om, ligesom i temavælgeren, og så kan lukke den igen, og listen er stadig åben?

**Comment by klavspc** [comment]
Jeg har ikke selv set fejlen og kan ikke provokere den frem. Er det noget du stadig ser?
