### ISSUE TITLE
 Fejl efter bulidIndex til S4​ (Truncate)

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#129]
Jeg har fået efterfølgende fejlmelding efter bulidIndex til S4.

Hvad er årsag til denne fejl og hvordan rettes det?

![image](https://cloud.githubusercontent.com/assets/3736091/8303111/d7390f94-199b-11e5-8abe-814432a33f51.png)

**Comment by klavspc** [comment]
Årsagen er at et felt fra din datasource er for stort til databasen. Se #119.

De felter, der oftest volder problemer er title og description og der står i issuet hvordan du kan forkorte indholdet af et felt.

For at finde ud af hvilket felt der er tale om i din datasource (bornuddannels_t_5709_skoledistrdata) må du udkommentere dem enkeltvis et ad gangen. Med mindre du med det samme kan se, hvilket felt det er, som vil skabe problemet.

**Comment by markusroesgen** [comment]
der

**Comment by markusroesgen** [comment]
Feltet distrikt_navn har en længde på 128, feltet link er på 255 tegn.

Er det wkt, der er over de 100.000 tegn?

Hvordan løser jeg det problem?

![skoledistrikter s4](https://cloud.githubusercontent.com/assets/11993556/8304619/ec95c6f0-19a7-11e5-9eb7-439fc3ef1384.JPG)

**Comment by klavspc** [comment]
@markusroesgen 
Det burde ikke være et problem at have en lang wkt. Har du opdateret WEB-INF/lib med den nye jar-fil, som følger med? Husk at slette den gamle jar-fil.

**Comment by markusroesgen** [comment]
Nu har jeg opdateret jar-filen og det virker i TEST-miljø. For at det slår igennem i PROD-miljø skal jeg først køre en eksport til PROD med efterfølgende buildIndex, rigtigt?

**Comment by klavspc** [comment]
Det var godt at høre. Ja, du skal eksportere konfigurationen og køre index
på produktionssitet.

Klavs Pihlkjær Christensen
Partner, seniorkonsulent
+45 9132 6946
klavs@septima.dk
--------------------------
Septima P/S
Frederiksberggade 28, 2.tv
1459 Kbh K
www.septima.dk

**Comment by markusroesgen** [comment]
Hej Klavs

Nu er der opstået samme problem igen efter opdatering til den nye version 2.5.2. Felterne har en længde på 128 tegn og jeg har opdateret jar-filen.

Kan du hjælpe?

Hilsen
Markus
