### ISSUE TITLE
sortering/rækkefølge i søgekategorier på egne indekserede data

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-s4#130]
Da vi har indeks på flere af vores datasources, vi vil gerne bestemme rækkefølgen i søgekategorier.
Det gælder både sortering blandt vores egne søgekategorier og deres gruppe position mht. resten.
Hvordan gør vi det?

**Comment by klavspc** [comment]
Vi kan lave en tilpasning så datasources vises i den rækkefølge de er
defineret i s4's config.xml.

Det vil også kunne styres hvor i søgeresultatet datasources fra s4's index
vises. I dag vises de *efter *geosearcher-resultater. Det er muligt at
splitte geosearcher resultater op så egne datasources bliver skudt ind i
mellem adresser og resten. Jeg har altid tænkt, at man gerne vil have
afresser øverst, hvis der søges i dem.

Resultater fra s4's index vil dog altid blive vist samlet.

Venlig hilsen

Klavs

*Klavs Pihlkjær Christensen*
Partner, seniorkonsulent
+45 9132 6946
klavs@septima.dk
--------------------------
Septima P/S
Frederiksberggade 28, 2.tv
1459 Kbh K
www.septima.dk

Den 2. juli 2015 kl. 11.20 skrev GIS Haderslev <notifications@github.com>:

**Comment by gis-haderslev** [comment]
Det er fint at s4's index resultater bliver vist samlet og vi behøver ikke splitte geosearch resultater. 
Vi vil kun bestemme rækkefølgen ind i index-gruppen og vil kunne flytte hele gruppen.

**Comment by klavspc** [comment]
Rækkefølge af datasources:
At kunne bestemme rækkefølgen af datasources som beskrevet ovenfor; _Vi kan lave en tilpasning så datasources vises i den rækkefølge de er defineret i s4's config.xml._ 4-6 timer.

At kunne flytte hele gruppen: Se #140

**Comment by klavspc** [comment]
Bo Thörnwall er muligvis interesseret
