### ISSUE TITLE
workspacesearcher virker ikke

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-s4#131]
Vores workspacesearcher virker ikke
Har lavet ny værktøj kopi af s4-plugin-all.xml men arbejdsområder kommer ikke frem i S4

**Comment by klavspc** [comment]
Det er vel s4-plugin-*dk*-all, der er brugt.

Er der workspace i profilen?
Hvilken version af SpatialSuite og s4 bruger i?

Venlig hilsen Klavs

*Klavs Pihlkjær Christensen*
Partner, seniorkonsulent
+45 9132 6946
klavs@septima.dk
--------------------------
Septima P/S
Frederiksberggade 28, 2.tv
1459 Kbh K
www.septima.dk

Den 2. juli 2015 kl. 11.35 skrev GIS Haderslev <notifications@github.com>:

**Comment by gis-haderslev** [comment]
SpatialSuite version 3.9.1
S4 version 2.2.62

Det er favoritter der er koblet til profilen - ingen problem med at søge i dem.
Workspaces er ikke afhængige af profilen. Jeg har ellers oprettet en ny workspace i test profilen.
De vises faktisk slet ikke som søgekategori.

**Comment by klavspc** [comment]
Hej,

Sidste spørgsmål inden jeg lige må logge ind og se, hvad der foregår; Er
workspace-searcher slået til i jeres custom tool?

Venlig hilsen Klavs

*Klavs Pihlkjær Christensen*
Partner, seniorkonsulent
+45 9132 6946
klavs@septima.dk
--------------------------
Septima P/S
Frederiksberggade 28, 2.tv
1459 Kbh K
www.septima.dk

2015-07-06 10:37 GMT+02:00 GIS Haderslev <notifications@github.com>:

**Comment by gis-haderslev** [comment]
Ja, hvis du mener det:
	            //Workspaces
	            workspacesearcher: {enabled: true}

**Comment by klavspc** [comment]
Test på workspace_init istedet for workspace_container. (workspace_container er ikke defineet i 3.9.1 før efter klik på menu)
