### ISSUE TITLE
Definer hvilken konfliktsøgning der bruges.

### ISSUE THREAD

**Issue by agf-syddjurs** [Septima/spatialsuite-s4#132]
Mulighed for at definere, at hvis der laves en konfliktsøgning fra s4 på adressen, så er det alligevel matriklen der bruges i konfliktsøgningen.

**Comment by klavspc** [comment]
Den undersøger jeg lige

**Comment by klavspc** [comment]
Kan løses ved at brugeren i detaljevisningens hvad-gælder-for afsnit kan vælge hvilken profilequery, der skal bruges. (Ligesom brugeren i dag i _Hvad gælder for_ kan vælge query)
Se #162
