### ISSUE TITLE
S4 virker ikke hvis temagrup navnet indeholder semikolon

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-s4#134]
http://kort.haderslev.dk/spatialmap?profile=konsulent

prøv at søge på 'KP13' - efter resultatet kommer frem kan man om man vælger en af 'temagrupper' bliver listen med relevante temaer ikke udvidet. Man kan ikke tænde noget.

**Comment by klavspc** [comment]
Har lige set, at det er rigtigt, at søgningen går galt, hvis er er kolon i navnet. Jeg ser på det og sender en opdatering til s4 ud snarest.

**Comment by klavspc** [comment]
Version 2.2.71 retter denne fejl ved at vise temagruppenavnet uden kolon. Det er eneste rettelse ifht v. 2.2.7.

* Download: https://github.com/Septima/spatialsuite-s4/archive/2.2.71.zip
* Udpak modulet og overskriv eksisterende modul. Den korrekte placering af modulet er
```xml
<module name="s4" dir="thirdparty/septima/s4" permissionlevel="public"/>
```
* Det er _ikke nødvendigt_, at opdatere jar-filen i WEB-INF/lib.
* Det er _ikke nødvendigt_ at opdatere dit custom tool.
