### ISSUE TITLE
Stednavnesøgning i S4

### ISSUE THREAD

**Issue by LailaNissen** [Septima/spatialsuite-s4#135]
GST er gået i luften med en ny stednavnetjeneste:
http://kortforsyningen.dk/indhold/danske-stednavne-faar-nye-tjenester

Det vil være rigtig godt, hvis den kan medtages i S4søgning

**Comment by klavspc** [comment]
Vi har undersøgt den nye tjeneste og den ser ud til at være til at gå til. Dog kan man endnu ikke filtrere på kommune, som man kan med de øvrige resourcer i GeoSearch. Det er vi ved at tale med gst om. Hvis der ikke filtreres på kommune, og det foretrækker de fleste, så vil der være voldsomt mange hits.

Vi vender tilbage når vi har nyt fra GST

**Comment by LailaNissen** [comment]
super, I undersøger hos GST. Jeg er enig i, at det primært har vores kommunale interesse, hvis vi kan selektere på kommune nr.

**Comment by klavspc** [comment]
Har netop erfaret, at gst vil opdatere servicen til at acceptere kommune-filter. Jeg melder tilbage når vi har set, at det er på plads

**Comment by mwtishoj** [comment]
Vi er med på en finansiering af del af opgaven.

**Comment by klavspc** [comment]
Så er stednavn_v2 i geosearch på plads med kommunefilter. Jeg regner med et par timer til at lægge Septima Search om til at vise dem. Kan vi aftale, at de deles med en time til jer hver @LailaNissen og @mwtishoj?

**Comment by mwtishoj** [comment]
Det er helt fint.

**Comment by LailaNissen** [comment]
Ja, det er fint
