### ISSUE TITLE
Søgning i SBSYS

### ISSUE THREAD

**Issue by LailaNissen** [Septima/spatialsuite-s4#141]
Vi er ved at implementere SBSYS - er det mon muligt at søge efter sager via S4?

**Comment by klavspc** [comment]
Talte med Ditmer om det for nylig. Der findes et søge-api til sbsys.

Største problem er rettigheder. Det er ikke helt ligetil kun at fremfinde de sager som spatialsuite brugeren gerne må se. En løsning kunne være at lade s4 få rettigheder svarende til laveste niveau.

Lad os gå videre med det. I er en del, der bruger sbsys som kan samfinansiere muligheden. Hvem af jer har en god dialog med brugergruppen og Ditmer? Så kan vi arrangere en lille snak med dem om hvad, der bedst kan lade sig gøre.

**Comment by flemmingrasbak** [comment]
Hej Laila.
Som du ved har vi i Næstved integration mellem Spatial Map og SBSYS. Vi kan søge efter stedfæstede sager via S4, og åbne sagen i SBSYS via et link i infoboksen.

**Comment by klavspc** [comment]
Flemming har ret. Stedfæstelserne kan indekseres og fremsøges.

Min samtale med Ditmer var baseret på, at man ville søge i dokumenter. Man kan, som det er i dag, lave en finsøgning på titel, initialer og sagsnummer.

Flemming: Du kan dele din presentation her i dette issue. Jeg kan huske, at vi lige måtte rode lidt med den for at få den helt på plads.

**Comment by LailaNissen** [comment]
Tak for jeres besvarelser. Den med søgning i dokumenter lyder god. Vi prøver lige Næstveds setup i første omgang, når vi går i luften her i oktober.

**Comment by flemmingrasbak** [comment]
Den presentation vi bruger se sådan ud:

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<presentation xmlns:fo="http://www.w3.org/1999/XSL/Format">
    <text name="overskrift" value="Stedfæstelse" plural="SBSYS-stedfæstelser"/>
    <columns>
        <column format="heading">
			<label>''</label>
			<value>SUBSTR(TOSTRING(sagstitel),1,250)</value>
        </column>
        <column format="description">
            <label></label>
            <value>sagsnummer + ' - ' + user_id</value>
        </column>
    </columns>
</presentation>
```

I S4 ser det fx sådan ud:

![sbsys_eks](https://cloud.githubusercontent.com/assets/8004072/9757770/d8f6b00a-56e2-11e5-8067-9983e5fdebf5.png)

**Comment by LailaNissen** [comment]
Tusind tak Flemming.
