### ISSUE TITLE
Søgning i DAR (DAWA)

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#142]
Udvid Septima Search med mulighed for at søge adresser fra DAR
Der er to fordele ved DAWA:
* Adresserne er mere opdaterede end adresser i gst's geosearch
* Der vil være mulighed for at søge i midlertidige adresser  

Dette sidste punkt kan være vigtigt, hvis man eksempelvis ønsker at tilbyde borgere, der har købt endnu ufærdigt projektbyggeri, mulighed for at undersøge deres nye område.

S4's vil understøtte begge søgninger. I konfigurations-filen vil man angive hvilken søgning, der skal bruges.

Opgaven vurderes til at ligge mellem een og to dage.

**Comment by klavspc** [comment]
Hvis Septima Search udvides med adressesøgning i DAR vil det, udover s4, også være muligt at søge i DAR i Widget- og rutemodulet.

**Comment by mwtishoj** [comment]
Vi vil gerne være med på den dele betaling

**Comment by tinadyhr** [comment]
Vi vil også gerne være med til at dele betalingen

**Comment by gis-haderslev** [comment]
Vi er også med til at dele betalingen

**Comment by LailaNissen** [comment]
Vi er også med på betaling

**Comment by karsten-brauner** [comment]
Hvidovre Kommune er interesseret. Deltagelse i betaling kan tidligst afgøres d. 21/9.

**Comment by Dorthe-Bak-Toefting** [comment]
Silkeborg Kommune vil også gerne være med til at dele betalingen

**Comment by mortenaag** [comment]
Roskilde er også med på at dele betalingen til denne

**Comment by Jette-Herlev** [comment]
Herlev er med på denne, vi skal da have de mest opdaterede adresser i S4
Hvor langt er 'vi' i processen?
