### ISSUE TITLE
Søgning af adresser på tværs af postnummer

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/spatialsuite-s4#143]
Er det muligt at sætte S4 op, så søgningen på adresser giver et samlet resultat for en vej frem for at opdele efter postnummer. Fx giver søgning på Ny Carlsberg Vej resultater for hhv. 1760 København V og 1799 København V.
Det er ikke hensigtsmæssigt, at man som bruger skal kende postnummeret for at vælge det rigtige husnummer.

**Comment by klavspc** [comment]
Det korte svar er nej; s4's adresse-søgning kan ikke konfigureres yderligere end hvilken kommune man ønsker at fremfinde adresser i.

S4 bruger geosearch til at fremfinde adresser og det er dermed geosearch's strategi for vejudvælgelse som du ser.

Vær opmærksom på issue #142 (Søgning i DAWA/DAR), som snart vil blive planlagt til en s4-release. Hvis heller ikke DAWA opfører sig som ønsket så vurderer jeg, at muligheden for at påvirke DAWA er større end gst's adressesøgning.

Den ultimative kontrol over søgestrategi kan vi få, hvis vi implementerer en egen adresse-søgning. Det er noget vi har overvejet, men der vil være et betydeligt arbejde i specifikation og finansiering.
