### ISSUE TITLE
De nyeste lokalplaner kommer ikke med i resultatet

### ISSUE THREAD

**Issue by rsp-solrod** [Septima/spatialsuite-s4#144]
Der er en del nye lokalplaner, der ikke kommer i resultatlisten i s4. Det drejer sig blandt andet om vores lokalplan 603.11 'To-etages boliger på boligø 11 i Trylleskov Strand', der blev vedtaget i august og 673.2 'Firemileskoven', der blev vedtaget i marts. Derimod kan jeg finde 673.1 'Firemileskoven', der er aflyst, og ikke burde dukke op.

**Comment by klavspc** [comment]
Vi har fundet og identificeret fejlen i vores indeksering af lokalplaner.
Mange tak for at have meldt fejlen.

Vi har valgt at opdatere løsnngen selvom vi ikke er _helt_ færdige med at
rette problemet; vi tænker, at rettelser af data skal ud hurtigst muligt.
Planer, der skal fjernes er nu væk. En del af de nye planer er kommet ind,
men vi bokser med nogle geometrifejl på nogle planer.

Vi er ved at at se på det og håber at opdatere vores indeks med korrekte
planer i denne uge.

*Klavs Pihlkjær Christensen*
Partner, seniorkonsulent
+45 9132 6946
klavs@septima.dk
--------------------------
Septima P/S
Frederiksberggade 28, 2. tv
1459 Kbh K
www.septima.dk

Den 18. september 2015 kl. 11.08 skrev Rasmus Slot <notifications@github.com
