### ISSUE TITLE
S4 til Qgis

### ISSUE THREAD

**Issue by mwtishoj** [Septima/spatialsuite-s4#146]
Jeg har gået og tænkt tanken, at det ville være smart, hvis man kunne få lavet S4 til Qgis. 

Lige som vi har i spatial suite. At den kan søge og finde adresser, temaer i forskellige databaser, Wfs, Wms, projekter m.v. og så skal man kunne åbne dem direkte fra S4. 

Måske kan man bruge/genbruge opsætningen fra Spatial suite eller omvendt, så man ikke behøver, at sætte samme søgning op 2 steder. 

Jeg søger nogen med samme interesse, så man kunne sætte sig sammen og lave en godt case, sammen med septima.

**Comment by gis-haderslev** [comment]
Vi har det samme interesse.

**Comment by mwtishoj** [comment]
Hej 
Vi er ved at kører Qgis i stilling til at være vores hoveddesktop gis, derfor at vi nogle ønsker /behov for at gøre Qgis og samspillet meget nemmere. Derfor at vi prøvet at beskrive vores behov i 3 dokumenter, som beskriver forskellige ønsker.  Jeg ved godt, at det kun er det ene som drejer sig om S4, men der er en sammenhæng mellem de andre plugins, som ønskes ind tænkt der for de vedhæftet. 

Vi er klar med finansiering til dette projekt, men start i år gerne hurtigst muligt.

 
Jeg har forsøgt at vedhæfte 3 pdf'er, men kan det ikke?

**Comment by mwtishoj** [comment]
Vi er klar med en pose penge, på ca. 10 - 15 timers arbejde, hvis der er andre som også kan bidrag lidt til noget start udvikling

**Comment by klavspc** [comment]
Vi er i gang med at beskrive hvad en første version af Septima Search til Qgis skal kunne. Herunder kunne søge i s4's index.

Alle, der er interesserede i at deltage i denne specifikation og udvikling er velkomne til at notere sig på dette issue eller skrive til mig eller Bo.

Når vi kommer længere vil vi oprette et særskilt repo i github til Septima Search for Qgis

**Comment by gis-haderslev** [comment]
Vi er også med til at finansiere.

**Comment by gis-haderslev** [comment]
Vi er også klar med penge til 10 - 15 timer

**Comment by klavspc** [comment]
Opgaven er flyttet til et eget projekt.

Tal med @MieWinstrup, hvis du er interessret i Septima Search for QGis
