### ISSUE TITLE
Opdatering af CVR

### ISSUE THREAD

**Issue by LailaNissen** [Septima/spatialsuite-s4#148]
Vi søgt på Alfafarm i Solrød. Vi har erfaret, at virksomheden er flyttet til Middelfart (muligvis sidste efterår), men den kommer fortsat frem på søgning i kortet via S4 søgning?

**Comment by klavspc** [comment]
Vi er metop ved at lægge vores cvr-indeks om. Med næste release af s4, som
kommer i denne måned, vil cvr-indekset være dagligt opdateret.

Vi har erfaret at vort hidtidige indeks ikke korrekt kunne geokode alle
virksomheder. Herudover var opdateringsfrekvensen svingende og ikke hyppig
nok. Det kan vi gøre bedre.

Vi har derfor lagt om og det kommer alle s4-brugere til del ved næste
release.

*Klavs Pihlkjær Christensen*
Partner, seniorkonsulent
+45 9132 6946
klavs@septima.dk
--------------------------
Septima P/S
Frederiksberggade 28, 2. tv
1459 Kbh K
www.septima.dk

Den 15. oktober 2015 kl. 16.50 skrev Laila Nissen <notifications@github.com>
:

**Comment by LailaNissen** [comment]
Tak for svaret - jeg mente nok jeg havde hørt det var på vej...
