### ISSUE TITLE
CVR-søgning giver ingen resultater

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-s4#151]
Opleves i version 2.3.2

**Comment by klavspc** [comment]
Der var i nat fejl i de data vi loadede fra virk.dk.
* For de interesserede bestod fejlen i, at der var registreret produktionsenheder, som ikke var tilknyttet en virksomhed.

Vi har opdateret vores import-script så det filtrerer disse ugyldige enheder fra.

__Efter vores kørsel i nat bør cvr-søgningen være oppe igen__

**Comment by gis-haderslev** [comment]
Det kører nu.
