### ISSUE TITLE
Teksten "s4Plugin" vises i top menuen

### ISSUE THREAD

**Issue by Andy-KK** [Septima/spatialsuite-s4#152]
Efter opgraderingen til 2.3.1 og efterfølgende 2.3.3 vises teksten "s4Plugin" som sidste menu i menulinjen foroven, udover at placere s4 i "panel-brand". Vi er ikke interesseret i at have s4 i menulinjen.
Panel er ellers sat til 'default' i toolet. s4_xxxx.xml
Bug eller har jeg glemt en lille detalje i opsætningen???

**Comment by klavspc** [comment]
Du skal sikre dig at top level i s4-plugin-xxx er _tool_. Se https://github.com/Septima/spatialsuite-s4/blob/master/tools/s4-plugin-dk-all.xml.

Hvis det ikke er det, der fejler så send mig en kopi af dit tool sammen med info om hvilken Spatial Map version I anvender.

**Comment by Andy-KK** [comment]
Pas??? Jeg viser her toppen af s4_kommunekort.xml toolet.
Spatialmap version 3.9.1

<?xml version="1.0" encoding="UTF-8"?>

<tool>
    <requires>
	<include ignore="not ModuleDefined('profileselector')" src="[module:profileselector.dir]/tools/profileselector.xml" nodes="/tool/requires/*" mustexist="true"/>
        <include src="[module:s4.dir]/tools/s4-requires.xml" nodes="/tool/requires/*" mustexist="true"/>
        <file type="script" name="/modules/s4/js/s4ThemeSearcher.js"/>
        <file type="script" name="/modules/s4/js/workspaceSearcher.js"/>
        <file type="script" name="/modules/s4/js/profileSearcher.js"/>
        <file type="script" name="/modules/s4/js/favoriteSearcher.js"/>

        
        
    </requires>
    <displayname>s4Plugin</displayname>
    <src><![CDATA[
            s4_init({

				//Mellemrums-separeret liste af kommunenumre. '*' søger i alle kommuner. Ellers feks. '101' eller '101 253'. 
                municipality: '101',
                
                //Positioning of s4. Choose between
                //  'default': In panel-brand if possible, else in panel-middle (menu linie, right justified)
                //  'tool': Use the panel as specified in the profile
                //  'panel-brand': Force s4 to panel-brand 
                //  'panel-top': Force s4 to top menu
                //  'panel-middle': Force s4 to menu linie (right justified)
                //  'menu': As the last menu in the menu line
                panel: 'default',

**Comment by klavspc** [comment]
Fejlen skyldtes, at toolets navn ikke startede med _s4-plugin_. Det skal det. Se https://github.com/Septima/spatialsuite-s4#include-tools-in-profiles
