### ISSUE TITLE
Test af seneste version 2.4

### ISSUE THREAD

**Issue by Andy-KK** [Septima/spatialsuite-s4#154]
Funktionen "Hvad gælder her" som detail hænger for alle type søgninger. Det virker stadig på "gammeldags" maner vore boksen kommer frem for at vælge "Tændt temaer" eller "Alle temaer".
![test_af_s4](https://cloud.githubusercontent.com/assets/8900845/11525027/33c811ac-98d0-11e5-806c-75bc3c41540e.gif)
Ellers er "Details" funktionen flot designet og smidig.

Os som stadig kører med den klassiske temavælger, har problemer med at få tændt/slukket det valgte tema i temavælgeren.

"Nearest" funktionen er skide smart og hurtigt.

**Comment by klavspc** [comment]
Her lige været inde og teste.

Der er så mange lag at _Hvad gælder for_ bliver træt.

* Har lavet en lille tilpasning, hvor jeg reducerer i antallet af lag og nu kører det. Det er noget jeg skal se på.
* Herudover søger i i rigtig mange ting i "info"-query. Hvis jeg nu laver s4 sådan at du kan angive hvilken query, der skal anvendes. Er det noget som man vil bruge? Jeg synes f.eks. ikke, at det giver mening feks at finde skråbilleder i detail view.

**Comment by klavspc** [comment]
Apropos skråfoto:

Kan man i almindelige _Hvad gælder for_ vælge et skråfoto og så se det i kortet. Så skal man også kunne det i s4.

Kan du ikke sende mig din presentation for skråfotos, Andy?

**Comment by Andy-KK** [comment]
Vi har de gamle udgave af skråfotos som vises med det almindelig "Hvad gælder for". Det nye fra 2014 vises med jeres egen speciel udviklet skråfotos visning....uden at indgår i "Hvad gælder for" funktionen, sandsynligvis fordi vi ikke har lavet nyere presentations til disse. Jeg sender dig XML-filen seperat.
