### ISSUE TITLE
TEST-site ikke tilgængelig efter opdatering til ny version 2.4.0

### ISSUE THREAD

**Issue by markusroesgen** [Septima/spatialsuite-s4#156]
Hej
Jeg har lige opdateret vores TEST-site med den nye version S4 2.4.0.
Har erstattet det gamle modul med det nye i [cbinfo.config.dir]/modules/thirdparty/septima/s4.

Efterfølgende har jeg kopieret \lib\custom-dk.septima.spatialsuite.index-xx.jar til \WEB-INF\lib og fjernet den gamle jar-fil.

Reload config.

Build search index.

Efterfølgende fejl kommer og Test-sitet svarer ikke mere. 

![fejl_index](https://cloud.githubusercontent.com/assets/11993556/11527216/d8909178-98df-11e5-8eaa-49ae50c097fd.JPG)

**Comment by klavspc** [comment]
Det er en out-of-memory fejl ved indeksering af data. Der er ikke ændret noget i de senere versioner mht indeksering. Er du sikker på at ovenstående fejl ikke også kommer i den tidligere version?
* _Hvis_ fejlen også opstår i tidligere version så vil jeg gerne høre hvilken database I bruger til s4's indeks. Hvis i bruger databasen som er indbygget i Spatial Suite, så vil det givet hjælpe at bruge jeres almindelige database istedet. (Dette er i øvrigt også en forudsætning for at bruge nogle af de nyere funktioner som releases med v 2.4.0) Se https://github.com/Septima/spatialsuite-s4/wiki/How-to-use-an-external-database
* _Hvis_ fejlen er introduceret med denne nye version så må jeg logge ind via vpn og fejlsøge. Det er dog alligevel min anbefaling at man bruger ekstern database istedet for den indbyggede. S4 vil ikke vedblive at understøtte den indbyggede database.

**Comment by markusroesgen** [comment]
Jeg har nu installeret version 2.3.3. i stedet for. Denne gang uden fejl ved indeksering af data. Jeg var ikke klar over, at den nyeste version 2.4.0 ikke var aftestet og frigivet...

**Comment by klavspc** [comment]
Version 2.4.2 er nu kørende i Sønderborg uden problemer
