### ISSUE TITLE
Ønske om søgning på vejkode i dawa (markering af hele vejen v søgning)

### ISSUE THREAD

**Issue by Dorthe-Bak-Toefting** [Septima/spatialsuite-s4#158]
Nu hvor vi er gået over til dawa-adresserne er den funktionalitet forsvundet hvor en søgning på vejnavn (uden at skrive husnr) gav mulighed for at klikke på navnet hvorefter der blev zoomet til vejen og den blev markeret med en rød streg. Det savner vores brugere. 

Er der andre som også er interesserede i at få den funktionalitet tilbage?

VH Dorthe, Silkeborg Kommune

**Comment by mwtishoj** [comment]
det er vi også

**Comment by klavspc** [comment]
Det vil tage godt en halv dags tid at få funktionen tilbage i dawasearcheren, hvis det gøres ifbm med øvrige arbejder.

Jeg planlægger den til første release efter jul

**Comment by clausmegaard** [comment]
Horsens er også interesserede

**Comment by Dorthe-Bak-Toefting** [comment]
Klavs - det lyder godt hvis det kan nå med første release efter jul :)

**Comment by Dortehaar** [comment]
Sønderborg er med også
