### ISSUE TITLE
Fejl ved opgradering til HTTPS

### ISSUE THREAD

**Issue by PeterGothard** [Septima/spatialsuite-s4#159]
Som det fremgår af nedenstående er vi ved at få opgraderet borgersite (hostet af Sweco) til HTTPS. Der kommer en fejlmeddelse vedrørende jeres program (må være s4)
 
Er det noget du kan rette?
 
Venlig hilsen

Peter Gothard Petersen
GIS-koordinator  
Teknik og Kultur - Sekretariatet - GIS                               
Direkte: 8964 5117 
Besøgsadresse: Torvegade 7, 8450 Hammel

Hovednummer: 8964 1010
Postadresse: Skovvej 20, 8382 Hinnerup, DK                       
                                                     
 
 
Fra: Sweco Issue Tracker [mailto:cbit@ghop.dk] 
Sendt: 4. december 2015 11:27
Til: Peter Gothard Petersen (Favrskov Kommune)
Emne: [CBIT] (SPSFAK-98) Opsætning af Spatial Suite borgersite til HTTPS
 

Thomas Hallundbæk Petersen commented on  SPSFAK-98 

  
Re: Opsætning af Spatial Suite borgersite til HTTPS 

Hej Peter
På borgersitet bliver der hentet eksterne javascriptfiler med http.
Disse vil ikke blive hentet når i kommer på https, så dele af funktionaliteten vil ikke virke, før dette er rettet.
Denne her bliver meldt ud i en fejlmeddelelse:
http://common.cdn.septima.dk/jsts/latest/javascript.util.js
Men det kan være, at der er flere, der først bliver hentet senere.
Jeg foreslår at du kontakter Septima, så de kan rette dette.
vh
Thomas

 
Add Comment

**Comment by klavspc** [comment]
Vi har lokaliseret årsagen til fejlen. (searcher.js:93-98)

Vi har planlagt en service-release af s4 til medio december. Vi udsender nyhedsbrev ved denne release og har selvfølgelig noteret os at det er en ændring, som er vigtig.
