### ISSUE TITLE
Søgning i egne datakilder virker ikke efter opgradering..

### ISSUE THREAD

**Issue by rsp-solrod** [Septima/spatialsuite-s4#165]
Efter opgraderingen af S4 kommer vores egne datakilder ikke med i søgeresultaterne. Vi har skiftet ud med den nye jar-fil og dannet nyt indeks, og vi kan se, at indekset er dannet rigtigt (vi kan søge i lokale data på siden, der kommer, når man har dannet indeks). Vi har også genstartet serveren. Er der nogen nye krav til presentation-filerne? Eller hvad kan det ellers skyldes?

**Comment by klavspc** [comment]
Ved opgraderingen har i opdateret jeres tool s4-plugin-xxx. Hvis i har kopieret fra det medleverede eksempel-tool, s4-plugin-dk-all, skal i være opmærksomme på at indexsearcher er disabled, dvs _enabled: false_ som standard. I skal rette til _enabled: true_.

Måske løser det problemet - ellers må jeg ind og se på jeres site

**Comment by rsp-solrod** [comment]
Det er det. Jeg var så tæt på, som at konstatere at den var sat til at søge i '*'. Men jeg havde ikke set, hvad der stod på næste linje.. Nu kører det. Tak for hjælpen!
