### ISSUE TITLE
Søgning på ejendomsnummer

### ISSUE THREAD

**Issue by LailaNissen** [Septima/spatialsuite-s4#166]
Er det muligt at søge på ejendomsnummer?

**Comment by Andy-KK** [comment]
Københavns Kommune har samme ønske. Vi vinder mange point hos brugerne hvis det her kan blive til noget :-)

**Comment by klavspc** [comment]
Vi er netop ved at lægge sidste hånd på et modul, som tillader søgning på ejendomme på ESR-ejendomsnummer og ejernavn i _Cognito local_. Medleveres i kommende eller næstkommende version af s4.

Det er vores plan at lave et parallelt modul til LOIS, hvis der er interesse for det.
