### ISSUE TITLE
Link til CVR fejler

### ISSUE THREAD

**Issue by torbeneriksen** [Septima/spatialsuite-s4#167]
Har netop installeret version 2.4.1 på vores testsite, men link fra søgeresultat til cvr fejler:

EntityFieldQueryException: Entity <em class="placeholder"></em> has no base table. in EntityFieldQuery->propertyQuery() (line 1209 of /data/applications/apache-httpd-2/datadistribution/site-root/data/includes/entity.inc).

Mvh. Torben, Køge Kommune

**Comment by klavspc** [comment]
Rettes i #168
