### ISSUE TITLE
Hyperlinks i presentations driller med conditions

### ISSUE THREAD

**Issue by mortenaag** [Septima/spatialsuite-s4#169]
Hej

Vi har en grundejerforeningstabel med en link kolonne som kun er sparsomt udfyldt. I spatialsuite fjernes denne kolonne i presentation med en condition der hedder: 

<condition>Length(link) &gt; 0 AND Length(trim(link)) &gt; 0</condition>

Denne condition fungerer også i s4 men hvis der er attributter der ikke er udfyldt på den kolonne den bruges på vises shape_wkt som tekst i detaljevisningen

![clipboard01](https://cloud.githubusercontent.com/assets/11662057/11838529/fd674600-a3e7-11e5-9dad-d7ca85cd919c.jpg)

Workaround for os er indtil videre at fjerne hyperlink formatet i presentation så hjemmeside teksten vises som normal tekst der kan kopieres ud.

![udklip](https://cloud.githubusercontent.com/assets/11662057/11838596/6219a8d6-a3e8-11e5-9fe4-dd181af11dc4.PNG)

**Comment by klavspc** [comment]
Erstattes af #171.
