### ISSUE TITLE
Version 2.4.2 fejler i IE10

### ISSUE THREAD

**Issue by dkahad** [Septima/spatialsuite-s4#170]
Efter at have installeret det nye modul vises temavælgeren ikke længere i vores profiler med IE10.
Med Chrome og Firefox har jeg ingen problemer med temavælgeren.

**Comment by klavspc** [comment]
Problemet løste sig ved at trykke CTRL-F5 (Fuld reload, drop cache) i SpatialMap. Det er et problem ved opgraderinger, at browsere gemmer gamle versioner af filer.
