### ISSUE TITLE
Ønske om markering af hele vejen også selv om der kun er én vej i søgeresultatet

### ISSUE THREAD

**Issue by Dorthe-Bak-Toefting** [Septima/spatialsuite-s4#172]
Når der kun er ét resultat i S4 på en vejnavns-søgning gives der pt ikke mulighed for at vælge hele vejen (dvs at få hele vejen markeret i kortet). Denne mulighed findes kun for de veje hvor der er flere vejnavne der matcher søgningen.

En "workaround" vi pt benytter os af er kun at skrive en lille del af vejnavnet og dermed få flere resultater. Men vi ønsker os en løsning hvor s4 skriver vejen som resultat i toppen af listen (før adresserne) uanset der kun findes den ene vej.

**Comment by clausmegaard** [comment]
Ja, 
Vi synes også den "gamle" løsning, hvor man skulle vælge vejnavnet med "enter", før man gik til adressesøgning på den valgte vej, virkede bedre.

I nogle tilfælde er der et entydigt match på vejnavn allerede efter 2 bogstaver (fx. Cikorievej), og så er det ikke muligt at bruge "Dorthes workaround"

**Comment by klavspc** [comment]
Jeg kan rette dawa-searchenren til så vejnavnet altid vises uagtet at der er kun er fundet adresser indenfor denne ene vej. Vejen vil altid blive vist øverst.

Opgaven estimeres til ca 4 timer. Meld ind om I vil være med og det vil virke fra næste version af s4.

**Comment by Dorthe-Bak-Toefting** [comment]
Hej Klavs
Den er vi med på her i Silkeborg.
Vh Dorthe

**Comment by klavspc** [comment]
Vejnavnet vises altid øverst. Så kan vejen vælges og ses i kortet.

![image](https://cloud.githubusercontent.com/assets/3736091/15012114/55d317f2-11f6-11e6-9d7b-62b862500ad5.png)
