### ISSUE TITLE
Ønske: At få vist postnr og by i søgeresultat når der er valgt adresse

### ISSUE THREAD

**Issue by Dorthe-Bak-Toefting** [Septima/spatialsuite-s4#174]
Når der søges på en vej - f.eks. ved at skrive 'Anemonevej 10' - og der efterfølgende klikkes på et af resultaterne - f.eks. Anemonevej 10, 8600 Silkeborg - vil vi gerne have at hele adressen inkl postnr og by vises i indtastningsfeltet. Sådan har det vist været tidligere?
Vores sagsbehandlere benyttede det til hurtigt at kopiere en adresse fra indtastningsfeltet og de savner funktionen :)

![adressesoeg_s4](https://cloud.githubusercontent.com/assets/14307722/12551101/68275a80-c368-11e5-9d78-c9a35f65e489.JPG)

**Comment by klavspc** [comment]
Ja, det giver mening at kunne kopiere adressen til videre brug. Og det er der bestemt en løsning på.

Det har nu aldrig været sådan at den valgte adresse blev vist i indtastningsfeltet, derimod ville det være oplagt at man ville kunne kopiere adressen i detaljevinduet, når en adresse er valgt. Det kan man ikke ligenu (prøv feks at vælge en adresse på http://v391.sps-demo.septima.dk. Teksten kan ikke vælges), men det skal vi fikse i den kommende release.

**Comment by klavspc** [comment]
Teksten i detaljevinduet kan nu kopieres
![image](https://cloud.githubusercontent.com/assets/3736091/13179023/1d0c19f0-d722-11e5-9118-e660c0ede142.png)
