### ISSUE TITLE
Indeksering fejler ved danske karakterer?

### ISSUE THREAD

**Issue by ChristianHelringAndersen** [Septima/spatialsuite-s4#176]
Hej Klavs

jeg har lige opdaget at S4 tilsyneladende har problemer med danske karakterer i vedtagne lokalplaner. Er det noget du er opmærksom på?
![danske_karakterer_s4](https://cloud.githubusercontent.com/assets/4671599/13218912/0655bdb8-d96d-11e5-8106-f8858e5d5643.png)

**Comment by klavspc** [comment]
Vi har registreret problemet og vil undersøge hvorfor der bliver indlæst
planer med forkert encoding i vores søgeindeks.

*Klavs Pihlkjær Christensen*
Partner, seniorkonsulent
+45 9132 6946
klavs@septima.dk
--------------------------
Septima P/S
Frederiksberggade 28, 2. tv
1459 Kbh K
www.septima.dk

Den 22. februar 2016 kl. 14.03 skrev Christian Helring Andersen <
notifications@github.com>:

**Comment by rsp-solrod** [comment]
Hvad er status på denne?

**Comment by klavspc** [comment]
Vores indlæsning er rettet til og næste version af s4 vil vise korrekte tegn
