### ISSUE TITLE
Får ikke vist hele temabeskrivelsen for et tema 

### ISSUE THREAD

**Issue by mwtishoj** [Septima/spatialsuite-s4#181]
![skaermbillede 2016-04-27 kl 11 55 08](https://cloud.githubusercontent.com/assets/4126030/14848759/8e4e086c-0c6f-11e6-9d71-682eeab14457.png)
Jeg får ikke vist hele beskrivelsen af et tema, hverken når jeg holder musen hen over eller når jeg har valgt temaet. 
Det har man kunnet i tidligere den gamle version af S4

**Comment by klavspc** [comment]
Mouseover giver nu hele beskrivelsen:
![image](https://cloud.githubusercontent.com/assets/3736091/14919962/7236d9de-0e2b-11e6-9385-4dc206452d11.png)
