### ISSUE TITLE
Jordforureningsattest på jordstykker og adresser

### ISSUE THREAD

**Issue by rastermanden** [Septima/spatialsuite-s4#183]
Det vil være smart med en mulighed for at "trække" en jordforureningsattest på adresser og jordstykker:

Det kan gøres ved at kalde miljøportalen med denne url:

http://arealinformation.miljoeportal.dk/gis/SoilContamination.aspx?elav=231451&matrnr=42g

**Comment by klavspc** [comment]
![image](https://cloud.githubusercontent.com/assets/3736091/14918856/45d081d8-0e26-11e6-936e-51dbae69106c.png)
