### ISSUE TITLE
Link til ois.dk, skat og jordforureningsattest fra adresse

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#184]

**Comment by klavspc** [comment]
s4-adresse-plugin-xml følger nu med s4 v. 2.5

![image](https://cloud.githubusercontent.com/assets/3736091/14949056/01b15a7c-1047-11e6-8393-e1bfb79dd637.png)

**Comment by mwtishoj** [comment]
Jeg har prøvet at tilføje dette Tool i min profil, men får ikke noget der ligner ovenstående. Er der andre indstiller, som skal tilrettes for at det virker ?
