### ISSUE TITLE
Vis Dagi-info for adresse

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#185]

**Comment by klavspc** [comment]
s4-details-dawa-dagi-plugin.xml inkluderet i s4 v. 2.5

Inkludér in profil:  
```xml
    <tool module="s4" name="s4-details-dawa-dagi-plugin" />
```    

![image](https://cloud.githubusercontent.com/assets/3736091/14949517/f1af2e20-104a-11e6-8306-ced1940b8aa4.png)

**Comment by mwtishoj** [comment]
Kan ikke få dette til at virke i min udgange, har tilføjet det min profil.

**Comment by klavspc** [comment]
![image](https://cloud.githubusercontent.com/assets/3736091/18475050/445d4db2-79c5-11e6-89f7-cb161bbbcbab.png)
