### ISSUE TITLE
Adressesøgning "Buskmosevej 2" viser "Buskmosevej 22" som resultat

### ISSUE THREAD

**Issue by markusroesgen** [Septima/spatialsuite-s4#186]
Søger man "Buskmosevej 2", vises "Buskmosevej 22" som resultat. Først når man klikker på "flere adresser" er der mulighed for at udpege "Buskmosevej 2" i resultatlisten.

Det samme gælder fx "Buskmosevej 4":

![buskmosevej](https://cloud.githubusercontent.com/assets/11993556/15138823/adb693cc-1692-11e6-97a6-6ff419de4fab.JPG)

**Comment by gis-haderslev** [comment]
Workaround er at skrive bindestreg symbolen lige efter adressenummeret
![adresse](https://cloud.githubusercontent.com/assets/8122296/15316156/f3ab67b6-1c1b-11e6-9b73-a53fcf1bdf51.PNG)
Vi har også valgt at vise længere liste med søgeresultater ved adressesøgningen i stedet for Flere Adresser, men så kommer adressen længst ned i listen
![adresse2](https://cloud.githubusercontent.com/assets/8122296/15316263/80242200-1c1c-11e6-9255-d939198595b3.PNG)

**Comment by klavspc** [comment]
Adresserne liste i denne rækkefølge fordi det er den, som returneres fra dawa's autocomplete-service. Se her: https://dawa.aws.dk/adgangsadresser/autocomplete?q=buskmosevej+2&type=adgangsadresse&kommunekode=540

Jeg er enig i, at dette ikke er hvad en bruger forventer af en adresse-søgning. Vi er i dialog med dawa om andre dele af deres service og vil tage det op med dem.

Der er også den mulighed, at s4 sorterer adresserne. Dette skal være sidste udvej, idet s4 vil skulle blive nødt til at hjemtage mange flere resultater for at kunne sortere som brugeren forventer.

**Comment by cfischer00** [comment]
"Uhensigtsmæssigheden" er indmeldt til DAWA's GitHUB: https://github.com/DanmarksAdresser/Dawa/issues/464

**Comment by klavspc** [comment]
Septima Search viser resultaterne som de returneres fra dawa. Følg det oprettede issue i dawa: https://github.com/DanmarksAdresser/Dawa/issues/464
