### ISSUE TITLE
Conditionals i presentations

### ISSUE THREAD

**Issue by rsp-solrod** [Septima/spatialsuite-s4#188]
Hej!

Jeg har sat S4 op til at søge i vores grundejerforeninger, vejlaug og boligforeninger og lavet min presentation sådan, at der bliver linket til cvr, hvis grundejerforeningen har et cvr-nummer:
```
<column format="hyperlink">
            <label>if cvr_nr != '' then 'Se forening i cvr' else '' endif</label>
            <value>if cvr_nr != '' then 'http://datacvr.virk.dk/data/visenhed?enhedstype=virksomhed&amp;id=' + cvr_nr+ '&amp;type=Alle' else '' endif</value>
        </column>
```
![eks1](https://cloud.githubusercontent.com/assets/10754902/15323696/973a65e0-1c43-11e6-97cb-a928784c84fd.png)
Men efter at have opdateret S4, viser den links for alle grundejerforeninger (ved mouse over), og folk risikerer at åbne en ny blank tab, hvis de rammer en, der tilfældigvis ikke har cvr-nummer:
![eks2](https://cloud.githubusercontent.com/assets/10754902/15323747/bfc54d22-1c43-11e6-9e27-43a14d8fc9ad.png)
Skal jeg indstille mig på, at jeg ikke kan bruge sådan nogle udtryk i den nye version? Eller er det en fejl?

**Comment by klavspc** [comment]
Conditions i columns i presentations ser sådan her ud:

```
<column format="hyperlink">
  <condition>web_id > 0</condition>
  <label>'Læs mere om monumentet på kk.dk'</label>
  <value>'http://www.kk.dk/monumentbasen.aspx?id='+web_id </value>
</column>
```  
_Condition_-tagget skal evaluere til true før kolonnen medtages i output (i eksemplet skal web_id være større end 0)

**Comment by rsp-solrod** [comment]
Hm, jeg har prøvet nogle varianter af udtrykket i en condition tag. Fx:

```
<column format="hyperlink">
   <condition>not cvr_nr = ''</condition>
   <label>'Se foreningen i cvr'</label>
   <value>'http://datacvr.virk.dk/data/visenhed?enhedstype=virksomhed&amp;id=' + cvr_nr</value>
</column>
```

Men så får jeg overhovedet ikke nogen links i S4. Hvad kan der være galt? Den burde ikke evaluere til false for alle rækkerne, for den presentation jeg viste i første post plejede at virke, og data har ikke ændret sig.

**Comment by klavspc** [comment]
Hvis du har en nyere version af s4 så burde det virke. Men der kan selvfølgelig være forhold der ikke har taget højde for. (Husker du iøvrigt at indeksere når du har ændret presentation? jsp/modules/s4/buildIndex.jsp)

En nem måde at teste conditions er at skrive dem i den presentation du bruger til almindelig _hvad gælder for_; dvs dine almindelige presentations. Så vil linket komme for nogle foreninger, men ikke for andre. Når du kan konstatere, at du har en korrekt condition, som dog ikke virker ved indekseringen i s4 så send den til mig, gerne sammen med dine grundejerforeninger i en shape-fil. Så vil jeg se hvad det er der sker med disse links

**Comment by rsp-solrod** [comment]
Ja, jeg har opdateret indekset hver gang. Vi kører med version 2.5.2.

Jeg prøver i en almindelig 'hvad gælder for', som du siger. Hvis jeg så ikke hitter en løsning, får du grundejerforeninger og shape-fil.

**Comment by klavspc** [comment]
Løst. Problemet var at s4 kræver at de faste felter i presentations (heading, description, searchtext) kommer som de første. Derefter de øvrige felter. Dokumentationen opdateres.
