### ISSUE TITLE
Vise hele beskrivelsen af temaet

### ISSUE THREAD

**Issue by mwtishoj** [Septima/spatialsuite-s4#190]
Vi har en længere beskrivelse af selve temaet, end hvad S4 viser i dag, derfor vil vi gerne havde hele beskrivelsen med, så brugerne kan finde det rigtige tema med det samme. 
Det kunne være med en mouseover funktion, hvor man ved at holde musen over et tema, og den udvider sig, så man kan se hele den beskrivende tekst, og eller hele beskrivelsen temaet vises under detaljer,

**Comment by klavspc** [comment]
Der er faktisk mouseover på beskrivelsen, men det skal jo lige gå op for brugeren.

Det er en god idé at rykke beskrivelsen ned i toppen af selve detaljevinduet. Det vil vi se på.

**Comment by klavspc** [comment]
Beskrivelsen er rykket ned i toopen af detaljevinduet, hvor der er masser af plads

**Comment by klavspc** [comment]
![image](https://cloud.githubusercontent.com/assets/3736091/18478007/fd9c04b2-79cf-11e6-8b55-3457e8104c61.png)
