### ISSUE TITLE
Vise postdistriker/opstillingskredse som polyoner ikke BBox

### ISSUE THREAD

**Issue by mwtishoj** [Septima/spatialsuite-s4#191]
Postdistrikter, opstillingskredse vises med bounding Box og ikke som den rigtige polygon.
-	Kan det laves om, så det virker som matriklerne ?

**Comment by klavspc** [comment]
GeoSearch fra kortforsyningen returnerer boundingbox, ikke geometri, for de udbudte dagi-temaer. Derfor kan s4 kun vise bbox. For matriklerne gælder det at septima search laver et opslag i geonøgler og får den faktiske geometri. Dette er ikke muligt for dagi-temaerne.
