### ISSUE TITLE
Fejl på visning på nogle af vores lokalplaner i s4

### ISSUE THREAD

**Issue by mwtishoj** [Septima/spatialsuite-s4#192]
Nogle af vores lokalplaner vises ikke korrekt

![skaermbillede 2016-06-14 kl 11 23 49](https://cloud.githubusercontent.com/assets/4126030/16037843/a48bf3f4-3222-11e6-9c11-32dd1f271568.png)

**Comment by klavspc** [comment]
I næste version af s4 benyttes et nyt lokalplan-indeks, som tager højde for at planer downloades i forskellige tegnsæt fra plansystemet.
