### ISSUE TITLE
Muligt problem med søgning i egne data

### ISSUE THREAD

**Issue by GIS-RandersKommune** [Septima/spatialsuite-s4#195]
Hej Septima.
Det kan være en fejl i min konfiguration (se filen: s4_knudepunkt_opsaetning), men jeg forventer egentlig, at når value/plural skaber "grupper", man søge efter - men det virker ikke umiddelbart (se filen: s4_knudepunkt_sogning)

Mvh.
Kåre
![s4_knudepunkt_sogning](https://cloud.githubusercontent.com/assets/13584505/16646551/f556e81a-442a-11e6-8180-7139b9573500.png)

![s4_knudepunkter_opsaetning](https://cloud.githubusercontent.com/assets/13584505/16646509/c0c5393a-442a-11e6-9bb9-fbbe37c98409.png)

**Comment by klavspc** [comment]
Hej Kåre,

Kan du illustrere forskellen imellem, hvad du ser og hvad du forventer at se?

Observationer:
* Jeg kan se i din presentation, at du har samme streng (Knudepunkter) for ental og flertal. Det fejler ikke, men bør være Knudepunkt/Knudepunkter for at give mest mening for brugeren
* Du har også samme værdi (knudenavn) for titel og beskrivelse. Igen ikke noget, der fejler, men det vil betyde, at navnet står to gange for hver knude i søgeresultatet.
