### ISSUE TITLE
Ændre farve i infoboks

### ISSUE THREAD

**Issue by admth** [Septima/spatialsuite-s4#196]
Søgeresultatet vises i en infoboks med en pæn grøn farve som desværre kolliderer med vores blå kommunefarve. Vil det være muligt at ændre farven via en parameter?

Mvh,
Torben Hansen
Herning Kommune

**Comment by klavspc** [comment]
.septimasearch ul.better-autocomplete li.ssDetailHeader
.septimasearch .ssTargetbit .ssTargetlabel, .septimasearch .ssTargetbit .ssTargetclosebutton 

s4Color.css distrubueres med s4. filen skal kopieres, tilpasses og inkluderes i toolet

**Comment by klavspc** [comment]
@admth: s4Color.css distrubueres med s4. Filen skal kopieres, tilpasses og inkluderes i toolet. Se kommentarer øverst i [s4-plugin-dk-all.xml](https://github.com/Septima/spatialsuite-s4/blob/master/tools/s4-plugin-dk-all.xml)

Her vises toppen i blå:
![image](https://cloud.githubusercontent.com/assets/3736091/18476334/e17c85dc-79c9-11e6-8166-24b65b1406ec.png)
