### ISSUE TITLE
Bug i ruteberegningsmodulet efter installation af S4 2.6.16

### ISSUE THREAD

**Issue by flemmingrasbak** [Septima/spatialsuite-s4#207]
Jeg har installeret seneste version af S4 (2.6.16). Vi har nu opdaget en mystisk ting i ruteberegningsmodulet. Om det har noget med S4 at gøre ved jeg ikke, men problemet har ikke været der før, så det er nærliggende at tro.

Probemet opstår når man i Spatial Map benytter ruteberegningsmodulet, lukker ruteberegningsmodulet ned og derefter aktiverer det igen. Så sker der det, at søgefeltet gentages for hver gang man starter ruteberegningsmodulet igen, se nedenstående:

![beregn_rute](https://cloud.githubusercontent.com/assets/8004072/18784917/9466b19a-8195-11e6-9cb3-3ac6fff1d198.PNG)

**Comment by klavspc** [comment]
Ja, det ser pænt ubrugeligt ud. Vi vil se på det og gøre hvad vi kan for at få det rettet inden for en uges tid.

Indtil fejlen er rettet må man enten rulle S4 tilbage til tidligere version eller bede brugerne genstarte SpM, hvis de vil beregne rute anden gang. Ikke en optimal situation. Vi vil gøre hvad vi kan i en fart.

**Comment by klavspc** [comment]
Rutemodulet er rettet og har nu version 2.1.13.
* Hent nyeste version fra http://www.septima.dk/spatialsuite-route/.
* Gamle version skal blot overskrives. Der er ingen ændring i konfiguration
