### ISSUE TITLE
Problem med scrolleren version 2.6.16 i IE

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-s4#208]
Ved nogle tilfælde forsvinder scrolldown listen, når jeg prøver at få fat i scrolleren .
Fejlen opstår kun i Internet Explorer !
1. Når jeg klikker i søgefeltet og prøver at få fat i scrolleren.
2. Når jeg giver slip for scrolleren ved at flytte musen samtidig ud over dropdown listen.

**Comment by klavspc** [comment]
@gis-haderslev kan du stadig genskabe problemet eller skal vi lukke issue?
