### ISSUE TITLE
Mouseover på temavisningsresultatet

### ISSUE THREAD

**Issue by mwtishoj** [Septima/spatialsuite-s4#211]
Det ville være snart, hvis man kunne få en mouseover over temaet, når man får et resultat på temasøgningen. Især rart, hvis temaerne hedder nogenlunde det sammen, dan man ikke kan se hele temanavnet
Hvis man så holder pilen henover et tema i ca. 0,5 - 1 sek, så vises hele temanavnet og temabeskrivelsen.

**Comment by klavspc** [comment]
Lukkes. Fixes i #230

**Comment by mwtishoj** [comment]
Jeg vil gerne have mouseover samlet i en, så man får det hele samlet både teamnavn og beskrivelse, lige meget hvor man peger på temaet. 

Nu vises det ene eller det andet, alt afhængig af hvilken tekst man lige får ramt.
