### ISSUE TITLE
Inkompabilitet med SpS 3.12 3. niveau  i temavælger

### ISSUE THREAD

**Issue by albmorten** [Septima/spatialsuite-s4#213]
Hej

Vi har netop fået SpS 3.12.1b 

Hvis vi bruger den nye mulighed for 3. niveau i temavælgeren holder S4 op med at kunne fremsøge temaer og selve søgeboksen vises ikke men til gengæld får vi en javascript fejl: TypeError: Cannot read property 'length' of undefined

Hvis 3. niveau fjernes igen eller themesearcher deaktiveres virker S4 som normalt.

3. niveau laves ved at tilføje en parentgroup til themegroup

f.eks.

<themegroup displayname="Sektorplaner" name="sektorplaner" expanded="false"/>
<themegroup displayname="Grundvandsbeskyttelsesplan 2017-24" expanded="false" name="grundvandsbeskyttelse" parentgroup="sektorplaner" type="checkbutton"/>

**Comment by klavspc** [comment]
Rettes i 2.6.20, som forventes ca 20. januar

**Comment by Ellebjerg** [comment]
Hej Klavs

Du har lukket dette issue, men det er stadig den samme version 2.6.16 af S4, der ligger til download. Har du en løsning klar?
