### ISSUE TITLE
S4 forsvinder når der trykkes på dropdown menu

### ISSUE THREAD

**Issue by albmorten** [Septima/spatialsuite-s4#214]
Hvis et S4 tool er sat til at opføre sig som et tool under panel i tool filen så forsvinder hele S4 søgeboksen når der trykkes en dropdown menu i SpS

Så vidt jeg kan se er det kun et problem når S4 indsættes som et tool

 Før tryk på dropdown
![ingen_tryk](https://cloud.githubusercontent.com/assets/24713112/21421559/ddc377b2-c833-11e6-8d9e-84583b04932e.png)

Efter tryk på dropdown:
![ved_tryk](https://cloud.githubusercontent.com/assets/24713112/21421580/ebed30e4-c833-11e6-81c3-96fa2ef36619.png)

S4 tool:
![s4](https://cloud.githubusercontent.com/assets/24713112/21421586/f39d637c-c833-11e6-833b-5c9145ad3a69.png)

S4 config:
![s4_config](https://cloud.githubusercontent.com/assets/24713112/21421608/0deff2f8-c834-11e6-8276-ec93c715dec8.png)

**Comment by klavspc** [comment]
2.6.21
