### ISSUE TITLE
Foreløbige adresser i S4

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/spatialsuite-s4#215]
Adressesøgning i S4 inkluderer foreløbige husnumre. Til os, der ved, hvad der er hvad, og som kender lokale adresser bedre end de fleste, kan det være ok, men brugt overfor offentligheden kan det godt give noget forvirring. 
Burde det ikke kun være de gældende adresser, der søges frem, eventuelt med mulighed for at administrator kan angive, at foreløbige også skal med?

**Comment by klavspc** [comment]
S4 benytter autocomplete-kaldet til dawa. Autocomplete tilbyder desværre ikke at filtrere på status. Jeg har oprettet [Lade Autocomplete respektere status som input parameter #530](https://github.com/DanmarksAdresser/Dawa/issues/530)
