### ISSUE TITLE
S4 finder ikke temaer i SpS 3.12

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/spatialsuite-s4#216]
Efter at vi har fået opgraderet Spatial Suite til 3.12, finder Septiam Search kun 56 temaer mod ca. 1200 før opgraderingen.  Mit bud er, at det skyldes, at S4 ikke kan finde ud af, at der nu er tre niveauer i temavælgeren.

**Comment by klavspc** [comment]
Se #213
