### ISSUE TITLE
Signaturforklaring dækker for søgelisten

### ISSUE THREAD

**Issue by flemmingrasbak** [Septima/spatialsuite-s4#217]
Kan man få søgelisten/resultatlisten til at ligge foran signaturforklaringen, så den ikke bliver delvis skjult? Se vedhæftede eksempel.

Mvh. Flemming
![s4](https://cloud.githubusercontent.com/assets/8004072/22425799/1d5eb23c-e6fd-11e6-9e98-474030b256e7.png)

**Comment by klavspc** [comment]
Der sker meget med versioner disse dage. Både i s4 og SpS.

For dette issue, og andre, der kommer i disse dage, må i gerne lige skrive i hvilken version af hhv s4 og SpS problemet ses.

Jeg ser på snarest muligt

**Comment by flemmingrasbak** [comment]
Vi kører lige nu S4 2.6.16 og SpS 3.12.1b.

**Comment by klavspc** [comment]
Fungerer korrekt med nyeste versioner, dvs s4 2.6.22 og SpS 3.12.2
