### ISSUE TITLE
Sortering af husnumre?

### ISSUE THREAD

**Issue by ChristianHelringAndersen** [Septima/spatialsuite-s4#219]
Hej Klavs

en sagsbehandler har observeret at husnumrene ikke bliver sorteret korrekt. Hvis der indgår bogstaver i husnummeret ligger det sig mere eller mindre tilfældigt (i bunden?) af listen. Er der mulighed for at gøre noget ved det eller er det bare sådan resultatet leveres fra DAWA servicen?

DBH

Christian

**Comment by klavspc** [comment]
Det er sådan DAWA returnerer dem. S4 forbedrer allerede nu sorteringen af adresser.

I version 2.6.25 har vi skruet endnu mere på sorteringen således at alle husnumre kommer i numerisk rækkefølge i langt de fleste tilfælde. (Dog vises det eksakte match på søgestrengen altid øverst)

![image](https://cloud.githubusercontent.com/assets/3736091/24150114/279093a0-0e45-11e7-9340-06775bf075cb.png)
