### ISSUE TITLE
S4 finder ikke aktivt CVR-nummer

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/spatialsuite-s4#226]
Vi har prøvet at søge på CVR 11916910 (Skov- og Naturstyrelsen) i S4 uden resultat. Samtidig kan vi se på virk.dk, at nummeret er aktivt, og vi har matrikler i kommunen, hvor nummeret står som ejer.

![image](https://cloud.githubusercontent.com/assets/10741426/25842905/ddbdcffe-34a5-11e7-8d40-65c3747df7c1.png)

**Comment by klavspc** [comment]
Der gælder følgende for virksomheds-søgningen i s4:
* Der søges og vises produktionsenheder (P-enheder, fysisk tilstedeværelse registreret i CVR). Der kan søges både med CVR- og P-nummer.
* Der søges efter produktionsenheder i den/de kommuner, der er sat op vha _municipality_-parameteren i toolet.

Skov- og Naturstyrelsen har ingen produktionsenheder i Hvidovre. Men de ejer åbenbart jord.

@Ellebjerg: Du må meget gerne uddybe, hvilken søgning du ønsker at udføre.
* Hvis du ønsker at bruge s4 som _opslag_ i cvr så skal s4 evt tilpasses så Virksomhedssøgningen kan søge i hele Danmark, mens det vel stadig kun er kommunens adresser, der er interessant. Opret gerne separat issue, hvis relevant.
* Hvis du ønsker at _finde ejendom_ ved at at indtaste ejerinfo så skal der indføres en ejendomssøgning, som kan dette. Opret gerne issue eller inspicér og kommentér feks #44. (#65 og #66 relaterer sig også til ejendomssøgning)

**Comment by klavspc** [comment]
Besvaret
