### ISSUE TITLE
Visning af veje uden adresse

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/spatialsuite-s4#229]
Det er i dag ikke muligt at få vist veje uden adresse i S4. Vejnavnet kan søges frem, med den vises ikke på kort. Det er ikke hensigtsmæssigt.
I Hvidovre gælder det fx Christian Sørensens Alle, Amagermotorvejen og Holbækmotorvejen.

**Comment by klavspc** [comment]
Dawa, dawa.aws.dk, som adressesøgningen benytter, er en adressesøgning, ikke en vejsøgning.

I princippet returneres kun veje, hvor der findes adresser, men det ses ofte, at dawa indeholder veje _uden_ adresser. Det er nok det du ser.

Hvis du vil søge i veje uden adresser må du selv etablere datagrundlaget, f.eks. fra FOT-vejmidter. Der er et tool, der kan hjælpe dig her: https://github.com/Septima/spatialsuite-s4/tree/master/tools#s4-soeg-egne-vejmidter-plugin

**Comment by klavspc** [comment]
Dawa, dawa.aws.dk, som adressesøgningen benytter, er en adressesøgning, ikke en vejsøgning.

I princippet returneres kun veje, hvor der findes adresser, men det ses ofte, at dawa indeholder veje uden adresser. Det er nok det du ser.

Hvis du vil søge i veje uden adresser må du selv etablere datagrundlaget, f.eks. fra FOT-vejmidter. Der er et tool, der kan hjælpe dig her: https://github.com/Septima/spatialsuite-s4/tree/master/tools#s4-soeg-egne-vejmidter-plugin

**Comment by klavspc** [comment]
Jeg har konstateret, at det netop er fordi Christian Sørensens Alle ikke har adresser, at du oplever problemet. Jeg har oprettet https://github.com/DanmarksAdresser/Dawa/issues/531

**Comment by Ellebjerg** [comment]
Det virkelige problem er nok, at det er temmeligt håbløst at få brugerne til at forstå konceptet med, at de kan søge på nogle vejnavne og få vist hele vejen, men ikke på andre.

Jeg kan ikke rigtigt gennemskue, om den bedste løsning er, at der kun vises egentlige adresser, og ikke hele vejen, når der fx søges på Hvidovrevej, eller om der kan gøres noget andet. Det er i hvert fald svært for brugerne at forstå, at de kan søge nogle veje, men ikke andre.

Det er formentlig ikke noget, du kan gøre så meget ved, hvis det helt og aldeles er styret af DAWA, men et eller andet bør gøres. Vi havde også udfordringer med det i København.
