### ISSUE TITLE
Opslag i Tingbog via S4

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#233]
Hej Septima

Søgning på "Ryesgade 16, 8680" i S4 giver intet resultat, men søgning i Tinglysning giver et resultat
https://dreambroker.com/channel/vms5brpe/lgmjpspu

https://www.tinglysning.dk/m/#/ejendomme/962c462b-45f9-4c0c-a6e9-5b3f55b7ecd7

**Comment by klavspc** [comment]
Løst i https://github.com/Septima/spatialsuite-s4/issues/228#issuecomment-305730521
