### ISSUE TITLE
Geosearch virker ikke på Matrikelnumre og i Stednavne

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-s4#234]
Vi oplever at der kan ikke søges i Matrikelnumre og i Stednavne. Det kører uendelig og kommer aldrig med nogle hits. Det må være lokalt problem, men vi ved ikke hvordan vi kan fange det.

**Comment by klavspc** [comment]
Kortforsyningen kører som den skal.

Prøv F12 i Chrome og se om der er nogle fejl at se.

**Comment by gis-haderslev** [comment]
Uncaught (in promise) SyntaxError: Unexpected token U in JSON at position 0

**Comment by gis-haderslev** [comment]
Det må være vores bruger og kodeord, for der kommer også:
User not authenticated
User not found

**Comment by gis-haderslev** [comment]
GET /Geosearch?service=GEO&limit=100&resources=stednavne_v2&area=muncode0510&search=h&login=***&password=***
GET /Geosearch?service=GEO&limit=100&resources=stednavne_v2&area=muncode0510&search=h&login=***&password=***

**Comment by gis-haderslev** [comment]
Hvorfor fejler det ikke på adresser, cvr osv. ? Sjovt nok men vi har ikke ændret vores login og adgangskode til GST/KMS

**Comment by gis-haderslev** [comment]
Har prøvet samme login oplysninger i SeptimaSearch for QGIS - virker uden problem

**Comment by GregersP** [comment]
Er der forsat problemer? 
evt. kan du sende præcis url pr mail til mig, så tjekker jeg lige her fra.

**Comment by gis-haderslev** [comment]
Ja, det er der.  Hvilken URL skal jeg sende ?
Du kan prøve det på http://kort.haderslev.dk/spatialmap? ved at søge på Matrikelnumre

**Comment by GregersP** [comment]
Det ser ud som om brugernavn/login og password til kortforsyningen ikke er angivet?

https://kortforsyningen.kms.dk/Geosearch?service=GEO&limit=8&resources=matrikelnumre%2Cstednavne_v2&area=muncode0510&search=gram%201a&login=***&password=***

**Comment by gis-haderslev** [comment]
<param name="s4.gst.login"  **hidden="true"** ignore="Not IsDefined(module.kms.login)">[module.kms.login]</param>
  <param name="s4.gst.password" **hidden="true"** ignore="Not IsDefined(module.kms.password)">[module.kms.password]</param>

**Comment by gis-haderslev** [comment]
Det må være hidden=true der gør det. Jeg retter det lige.

**Comment by gis-haderslev** [comment]
Det var så det. Jeg har tidligere tilføjet automatisk hidden="true" til alle passwords i SpatialMap, men der er jo ikke behov for s4. Mange tak for hjælpen.
