### ISSUE TITLE
Udvidelse af detaljevisning til visning af billeder

### ISSUE THREAD

**Issue by albmorten** [Septima/spatialsuite-s4#235]
Hej

Vi vil gerne have udvidet detalje visningen i S4 til SpS til at inkludere billede visning i stil med den normale visning af billeder via præsentation i SpatialSuite.

Mvh Morten
Albertslund

**Comment by klavspc** [comment]
Følgende column i en presentation vil nu vise en and i detaljevisningen. Ret til med et passende billede
```
<column format="imageURL">
  <label></label>
  <value>'https://web.stanford.edu/dept/CTL/cgi-bin/academicskillscoaching/wp-content/uploads/2012/07/baby-duck.jpg'</value>
</column>
```
![image](https://user-images.githubusercontent.com/3736091/29415052-f8926bae-8361-11e7-8be6-29a2d2b8a84e.png)
