### ISSUE TITLE
S4-index: Tænd korresponderende tema

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#240]
Hej Klavs
 
Tak for snakken i dag. Som aftalt hermed en kort beskrivelse af den funktionalitet, som ønskes tilføjet s4. Jeg vil gerne have et estimat på opgaven inden den igangsættes.
 
Workflow:
 
1 - Bruger fremsøger footprint i s4 (via søgeord eller listevisning)
2 - Detaljevisning for footprint vises
3 - Korresponderende tema(er) tændes (i dette tilfælde dronefoto svarende til footprint) rød søge-markering slukkes
 
Rød markering i billed 2 viser evt. placering af knap til tænding af lag/tema. Tekst til knap skal være konfigurerbar.
 
1)
![image](https://user-images.githubusercontent.com/3736091/30315606-d8cdb8c6-97a4-11e7-8ff8-8db747b7de10.png)

2)
![image](https://user-images.githubusercontent.com/3736091/30315620-e1d9fad8-97a4-11e7-8c85-570d6ca34229.png)

3)
![image](https://user-images.githubusercontent.com/3736091/30315631-e9ccb0aa-97a4-11e7-8f0a-4e6cebeb37b9.png)

**Comment by klavspc** [comment]
![image](https://user-images.githubusercontent.com/3736091/30315674-0fca3066-97a5-11e7-9783-a0d90ab4d735.png)

**Comment by klavspc** [comment]
kommer med 2.6.34

**Comment by klavspc** [comment]
2.6.34

**Comment by klavspc** [comment]
Mangler _rød søge-markering slukkes_

**Comment by klavspc** [comment]
Rød søgemarkering slukkes når valgte feature er en polygon.
2.6.35

**Comment by mortentj** [comment]
Virker denne feature stadigvæk, jeg synes ikke jeg kan få den til at virke?
