### ISSUE TITLE
Problemer med IE 10?

### ISSUE THREAD

**Issue by ChristianHelringAndersen** [Septima/spatialsuite-s4#242]
Der er tilsyneladende problemer med seneste release af S4 og IE 10 (som vi desværre anvender i kommunen). Der er ingen problemer med IE 11, Chrome og Firefox.

**Comment by klavspc** [comment]
Det er toolet _s4-details-themesForIndex-plugin_, som indeholder en fejl. Udkommentér
`<tool module="s4" name="s4-details-themesForIndex-plugin" />`
i profilen således:
`<!--tool module="s4" name="s4-details-themesForIndex-plugin" /-->`

**Comment by klavspc** [comment]
Rettes snarest i 2.6.36
