### ISSUE TITLE
Adressesøgning + gældende lokalplan

### ISSUE THREAD

**Issue by Jette-Herlev** [Septima/spatialsuite-s4#244]
Vores sagsbehandlere ønsker at kunne fremsøge en adresse i S4 og få vist den gældende lokalplan

**Comment by ChristianHelringAndersen** [comment]
Lidt a la det her?

https://github.com/Septima/spatialsuite-s4/issues/240


2017-11-14 10:40 GMT+01:00 Jette Hinrichs <notifications@github.com>:

**Comment by Jette-Herlev** [comment]
Lidt a la men alligevel ikke...du har fået lavet så man kan se relaterede temaer, her ønskes at temagrupperne det søgte tema ligger i, listes op.
:-)

**Comment by klavspc** [comment]
Nyt tool viser gældende lokalplan for an adresse
```xml
<tool module="s4" name="s4-adresse-planer-plugin" />
```
![image](https://user-images.githubusercontent.com/3736091/35329139-043c90ea-00ff-11e8-8486-cd9b9cc8ddd1.png)
Park Allé 45 er valgt. Der er kommet et panel for _Vedtaget lokalplan_

Ved klik på panelet kan man se lokalplanen
![image](https://user-images.githubusercontent.com/3736091/35329254-843792b8-00ff-11e8-8ce6-c105daee8268.png)

... og klikke på _Mere_ for at se detaljer:
![image](https://user-images.githubusercontent.com/3736091/35329333-cae03e4a-00ff-11e8-9cb1-4b318f6ce6b6.png)

**Comment by markusroesgen** [comment]
Det virker desværre ikke hos os.

Jeg kan se lokalplanen i SpS...

![s4_lokalplan](https://user-images.githubusercontent.com/11993556/35564865-89b8b510-05b3-11e8-9f19-2b4862215bad.PNG)


... men klikker jeg på "mere" dukker der ingen detaljer op og s4 lukker sig:

![s4_lokalplan_2](https://user-images.githubusercontent.com/11993556/35564982-c2716730-05b3-11e8-9b7f-0b48f6d2f2ac.PNG)

**Comment by klavspc** [comment]
Grunden til at det ikke virker hos @markusroesgen er at der kun er custombuttons, ingen detaljevisning, på planer. Dette tager _s4-details-dawa-planer-plugin_ ikke højde for.

Hvis du også har problemet kan det løses det ved at lægge toolet [s4-details-spatialquery-plugin](https://github.com/Septima/spatialsuite-s4/tree/master/tools#s4-details-spatialquery-plugin) på. Så kommer der også detaljevisning på planer i den almindelige plansøgning, men det er det bedste jeg kan gøre indtil næste release.

```xml
<tool module="s4" name="s4-details-spatialquery-plugin" />
```

**Comment by klavspc** [comment]
Toolet tager ikke højde for - at der kan være flere gældende planer - rettes til v. 2.9

**Comment by klavspc** [comment]
Alle vedtagen lokalplaner vises nu for adresse.
![image](https://user-images.githubusercontent.com/3736091/38298038-730e7352-37f6-11e8-89d2-93dee6d1f3a1.png)
