### ISSUE TITLE
Vise tilhørende temagruppe

### ISSUE THREAD

**Issue by Jette-Herlev** [Septima/spatialsuite-s4#245]
Når der søges på temaer i S4, vil det være en super hjælp at få vist tilhørende temagruppe, hvor er temaet placeret.

**Comment by klavspc** [comment]
Nyt tool viser relaterede temaer
```xml
<tool module="s4" name="s4-details-themes-related-plugin" />
```

![image](https://user-images.githubusercontent.com/3736091/35275734-ffd0e628-0040-11e8-874c-bb79a1f76a5c.png)
Temaet GST Ortofoto - forår er valgt. Det ses. at temaet tilhører gruppen _Baggrundskort_.

Ved klik på panelet kan man se andre temaer i gruppen:
![image](https://user-images.githubusercontent.com/3736091/35275787-240c00cc-0041-11e8-8ccb-275869bbef4f.png)
