### ISSUE TITLE
Detaljevisning - header fylder meget

### ISSUE THREAD

**Issue by Jette-Herlev** [Septima/spatialsuite-s4#246]
Sagsbehandlerne her synes at detaljevisningen fylder for meget, de har ikke alle lige store skærme!

**Comment by klavspc** [comment]
Fikset i 2.7, som kommer i uge 4

**Comment by klavspc** [comment]
Lav/almindelig header i detaljevisning kommer til at blive styret af cbinfo-parameter. Se #255

**Comment by klavspc** [comment]
Definér parameteren s4.header.small således i din cbinfo.xml:
```xml
<param name="s4.header.small">True</param>
```
