### ISSUE TITLE
Låsning af søgefelt under indlæsning af temaer

### ISSUE THREAD

**Issue by agf-syddjurs** [Septima/spatialsuite-s4#247]
Vi er efterhånden oppe på 1879 temaer i vores standardprofil. Når vi laver den første søgning i S4 i vores citrix miljø, så går der op til 5 sekunder hvor S4 er læst, mens den tæller op hvor mange temaer der kan søges i, og begynder man at skrive noget, så registreres det ikke. Det forvirrer mange brugere hos os.

**Comment by klavspc** [comment]
Ja - det tager desværre tid at indlæse alle temaer. Vi er i dialog med Sweco om hvorvidt en temasøgefunktion kan indbygges i SpS så s4 kan kalde den istedet for selv at indlæse dem. Indtil denne funktion er på plads vil vi finde på noget andet, der kan forbedre brugeroplevelsen. Det kommer i en snarlig opdatering.

Mine idéer er indtil videre:

Vi kan ikke komme uden om at det tager tid at indlæse - Det bør dog ikke blokere for at brugeren kan indtaste. Jeg vil flytte indlæsningen i baggrunden så der kan indtastes.  Der vil ikke blive givet temasøgersultater før temaerne er indlæst, men det gør nok ikke så meget, at man først kan søge i temaer efter fem sekunder; Det er jo _langt_ fra alle søgninger, der går direkte mod temaer fra starten og det kan være at de når at blive indlæst i den tid man taster og kikker på "Temaer" i resultatlisten.

**Comment by mwtishoj** [comment]
Vi oplever det samme, og det er en god start @Klavs

**Comment by agf-syddjurs** [comment]
Tænker også at det vigtigste er at brugerne ikke oplever at feltet låse, vi kan godt leve med lidt forsinkelse på temaerne, for nogle afde ander kommer også dryssende lidt hen ad vejen. Og som du selv skriver, så er det nok mere end 90 % af søgningerne der efter andet end temaer.

Venlig hilsen

Allan Gyldendal Frederiksen
GIS-koordinator
Syddjurs Kommune, Digitalisering

Direkte +4587535261
Mobil +4530924749
agf@syddjurs.dk<mailto:agf@syddjurs.dk>

Fra: Klavs Pihlkjær [mailto:notifications@github.com]
Sendt: 15. november 2017 11:59
Til: Septima/spatialsuite-s4
Cc: Allan Gyldendal Frederiksen; Author
Emne: Re: [Septima/spatialsuite-s4] Låsning af søgefelt under indlæsning af temaer (#247)


Ja - det tager desværre tid at indlæse alle temaer. Vi er i dialog med Sweco om hvorvidt en temasøgefunktion kan indbygges i SpS så s4 kan kalde den istedet for selv at indlæse dem. Indtil denne funktion er på plads vil vi finde på noget andet, der kan forbedre brugeroplevelsen. Det kommer i en snarlig opdatering.

Mine idéer er indtil videre:

Vi kan ikke komme uden om at det tager tid at indlæse - Det bør dog ikke blokere for at brugeren kan indtaste. Jeg vil flytte indlæsningen i baggrunden så der kan indtastes. Der vil ikke blive givet temasøgersultater før temaerne er indlæst, men det gør nok ikke så meget, at man først kan søge i temaer efter fem sekunder; Det er jo langt fra alle søgninger, der går direkte mod temaer fra starten og det kan være at de når at blive indlæst i den tid man taster og kikker på "Temaer" i resultatlisten.

**Comment by gis-haderslev** [comment]
Vi oplever det samme problem. Enig med de forslag, som Klavs og Allan kom med. Vores brugere søger hovedsagelig på adresser og matrikler.

**Comment by klavspc** [comment]
Fikset i 2.7, som kommer i uge 4

**Comment by agf-syddjurs** [comment]
Virker fint, undtagen i Internet Explorer (11), hvor det desværre ser ud til at S4 opfører sig som før.

**Comment by klavspc** [comment]
Blev meget bedre i 2.7, men kan optimeres endnu mere. Koordinér med SWECO's opdatering af temavælger i 3.14.2

**Comment by gis-haderslev** [comment]
Det blev ikke bedre i 3.13.2 i hvertfæld

**Comment by klavs** [comment]
Hello.

**Comment by klavspc** [comment]
Vi og Sweco har optimeret indlæsning af temaer således at version 2.8 af s4 i SpS 3.14.1 kører rigtig godt.

Tidligere versioner virker selvfølgelig stadig med den performance der nu engang er.
