### ISSUE TITLE
Integration til EjdExplorer fra LIFA

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#248]
For valgt adresse/matrikel at kunne åbne EjdExplorer fra detaljevisningen

Info fra Preben Lisby, LIFA:

> Når en bruger finder en adresse eller matrikel i Septima Search, og gerne vil have den åbnet i EjdExplorer, skal de kalde EjdExplorer som beskrevet her:
> http://dok.lifa.dk/manual/EjdExplorer/HTML/8_integrationsspecifikation.htm
> …i mode=single, som er beskrevet i den nederste 1/3-del af siden.
>  
> Det vil sige, at de skal benytte de funktioner du har lavet:
> adresser_userdatasource_to_single-plugin
> eller
> jordstykker_userdatasource_to_single-plugin

**Comment by klavspc** [comment]
Hvis EjdExplorer-modulet er installeret (leveres af LIFA) så kan man tilføje følgende tool til profilen:
```xml
<tool module="ejdexplorer" name="s4/s4-adresse-matrikel-plugin"/>
```
![image](https://user-images.githubusercontent.com/3736091/35339160-22cd9484-0120-11e8-8813-e1aa78e2d051.png)
En adresse er valgt i s4

**Comment by markusroesgen** [comment]
Hej Klaus

Jeg har tilføjet efterfølgende i min profil:
<tool module="ejdexplorer" name="s4/s4-adresse-matrikel-plugin"/>

... men desværre fejler profilen, se fejlmelding:
Error getting profile 'webkort'. java.lang.Exception: Error in profile 'webkort'. java.lang.Exception: Error in tool 's4/s4-adresse-matrikel-plugin' (module 'ejdexplorer', tool number 46). java.lang.Exception: Error in tool 's4/s4-adresse-matrikel-plugin'. com.carlbro.cbinfo.request.pub.ProfileException: FILE NOT FOUND, additional error message: d:/spatialsuite/sites/test-kort.sonderborg.alssok.net/appbase/spatialmap/WEB-INF/config/**modules/thirdparty/lifa/ejdexplorer/tools/s4/s4-adresse-matrikel-plugin.xml could not be found**

**Comment by markusroesgen** [comment]
![s4_ejdexplorer](https://user-images.githubusercontent.com/11993556/37146224-0b02f3f0-22bb-11e8-858a-e0ccb97eacd5.JPG)

**Comment by markusroesgen** [comment]
![s4_ejdexplorer_2](https://user-images.githubusercontent.com/11993556/37146343-5b3c1202-22bb-11e8-91df-507d70bad8cf.JPG)

**Comment by klavspc** [comment]
@markusroesgen Toolet er en del af EjdExplorer-modulet, som leveres af LIFA. Når du har installeret en opdateret version af det modul kan du inkludere toolet i profilen

```xml
<tool module="ejdexplorer" name="s4/s4-adresse-matrikel-plugin"/>
```
Jeg er i kontakt med LIFA - opdatering følger
