### ISSUE TITLE
Detaljevisning i SpS 3.14

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#252]
Udfordringer vedr. S4 efter opgradering til SPS ver. 3.14

 

Som det ser ud inden opgraderingen:

![image](https://user-images.githubusercontent.com/3736091/35037772-c6adceb4-fb78-11e7-8310-53e6b6573258.png)

Efter opgraderingen ser det sådan ud:
![image](https://user-images.githubusercontent.com/3736091/35037785-cf920982-fb78-11e7-9a34-38f7844f0cb8.png)

Når vi så klikker på Tingbogen bliver vi mødt af dette:
![image](https://user-images.githubusercontent.com/3736091/35037791-d504d4c6-fb78-11e7-9d31-a923dbfeeded.png)
 

Og først når vi har klikket på de tre prikker, kommer den velkendte dialogboks frem – Kan du hjælpe?

**Comment by markusroesgen** [comment]
Hej Klavs

Kommer der et fiks/ny version, som løser dette problem? Og hvornår?

Hilsen
Markus

**Comment by markusroesgen** [comment]
"Hvad gælder for matriklen" og "hvad gælder for" fungerer ikke. Systemet reagerer ikke når man trykker på "OK":

![s4_hvad_gaelder_for](https://user-images.githubusercontent.com/11993556/35150221-789468ce-fd11-11e7-8bea-b5ff2e8eba6c.PNG)

**Comment by klavspc** [comment]
Fikset i 2.7, som kommer i uge 4

**Comment by Ellebjerg** [comment]
Overså denne. Tak!
