### ISSUE TITLE
Ekstrafunktioner kommer ikke frem i SpS 3.14

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/spatialsuite-s4#256]
I SpS 3.14 kommer ekstrafunktionerne ejendomsoplysninger, BBR-oplysninger... ikke frem, når adressesøgning foretages. Først efter klik på et af de andre menupunkter i søgeresultatet, fx DAGI-info, kommer der en bjælke frem, som kan klikkes, hvorefter funktionerne kommer frem.

![image](https://user-images.githubusercontent.com/10741426/35388704-1db4ca66-01d5-11e8-8687-964fb59c4dfe.png)
![image](https://user-images.githubusercontent.com/10741426/35388722-326b6f96-01d5-11e8-895a-768898c4371f.png)
![image](https://user-images.githubusercontent.com/10741426/35388739-443cfd98-01d5-11e8-8b67-fed61be7d48c.png)

**Comment by klavspc** [comment]
Løst i #252
