### ISSUE TITLE
Problemer med S4-findnearest-toolet

### ISSUE THREAD

**Issue by ikast-mofri** [Septima/spatialsuite-s4#257]
Jeg har installeret den nyeste version og forsøger mig med toolet ”findnearest”, men kan ikke få det til at virke. Den står bare og søger, men kommer aldrig med et resultat.

Jeg kan finde følgende fejlmeddelelse:

septimasearch.min.js?ver=3.13.1:2 POST http://kort.ibk.lan/jsp/modules/s4/queryIndex.jsp 401 (Unauthorized)
(anonymous) @ septimasearch.min.js?ver=3.13.1:2
h @ septimasearch.min.js?ver=3.13.1:2
(anonymous) @ septimasearch.min.js?ver=3.13.1:2
mySq @ septimasearch.min.js?ver=3.13.1:2
(anonymous) @ septimasearch.min.js?ver=3.13.1:2
sq @ septimasearch.min.js?ver=3.13.1:2
(anonymous) @ septimasearch.min.js?ver=3.13.1:2
handle @ septimasearch.min.js?ver=3.13.1:2
(anonymous) @ septimasearch.min.js?ver=3.13.1:2
Promise resolved (async)
(anonymous) @ septimasearch.min.js?ver=3.13.1:2
(anonymous) @ septimasearch.min.js?ver=3.13.1:2
activatePanel @ septimasearch.min.js?ver=3.13.1:2
(anonymous) @ septimasearch.min.js?ver=3.13.1:2
dispatch @ jquery-1.11.1.min.js:3
r.handle @ jquery-1.11.1.min.js:3

**Comment by klavspc** [comment]
Det er konstateret, at når man kører SpS direkte mod Tomcat på serveren, dvs ikke igennem den IIS, der normalt står foran Tomcatten, så fungerer det. Det vil sige, at det skal undersøges hvorfor IIS'en mon stopper forespørgslen.

Hvis der er noget S4 kan gøre anderledes så det virker vil vi forsøge at få det med i en snarlig release

**Comment by klavspc** [comment]
@moelgaard730 har kigget på IIS-opsætning og hvordan s4 kalder SpS. Han er kommet med et par forslag som vi sammen vil teste af i den kommende tid. Når vi har styr på løsningen melder vi ud her hvordan det bliver releaset

**Comment by klavspc** [comment]
Løst
