### ISSUE TITLE
S4 v. 2.7.1 - arbejdsområder fremsøges ikke - SPS v. 3.14 

### ISSUE THREAD

**Issue by gladsaxe-pia-jacobsen** [Septima/spatialsuite-s4#258]
Ved søgning vises arbejdsområder fint, men S4 finder dem ikke ved markering.
Vedhæftet fejlbesked i Microsoft Edge, samt de tools der er i custom\tools_intern_standard

[S4 fejl i arbejdsområder.pdf](https://github.com/Septima/spatialsuite-s4/files/1702179/S4.fejl.i.arbejdsomrader.pdf)

**Comment by markusroesgen** [comment]
Vi oplever det samme hos os i Sønderborg (SpS 3.14).

**Comment by klavspc** [comment]
@gladsaxe-pia-jacobsen og @markusroesgen:

Jeg har en mistanke om, hvad der er galt - hvis det er rigtigt hvad jeg _tror_ så virker arbejdsområde slet ikke hos jer. Kan i ikke lige prøve at starte arbejdsområde i menuen og se om det virker?

**Comment by gladsaxe-pia-jacobsen** [comment]
Arbejdsområder virker fint hos os - bare ikke via S4
Vi konstaterede i går at Hvidovre har samme udfordring

**Comment by markusroesgen** [comment]
Arbejdsområder virker også hos os - bare ikke via s4.

**Comment by klavspc** [comment]
@gladsaxe-pia-jacobsen og @markusroesgen:

Tak for jeres input - jeg nærmer mig en løsning og har vedlagt et fix som jeg vil bede jer teste.
* Download og omdøb denne fil [workspaceSearcher.txt](https://github.com/Septima/spatialsuite-s4/files/1710470/workspaceSearcher.txt) til workspaceSearcher.js.
* _Erstat_ den eksisterende workspaceSearcher.js i WEB-INF\config\modules\thirdparty\septima\s4\js med denne nye fil.
* Reload sitet (/admin?command=reloadconfig) og prøv igen

Hvis dette virker rettes søgningen i v 2.8 som kommer senere på måneden.

**Comment by markusroesgen** [comment]
Det har hjulpet hos os i Sønderborg :)

**Comment by klavspc** [comment]
Den nye kode virker og kommer i s4 v 2.8 som kommer senere på måneden.
