### ISSUE TITLE
Udvidelse af DAWA vejmidte søgning, søgning på vejkode

### ISSUE THREAD

**Issue by albmorten** [Septima/spatialsuite-s4#261]
Vil det være muligt at udvide dawa vejmidte plugin så det også søger på vejkode?

**Comment by klavspc** [comment]
@albmorten Jeg skal lige have uddybet, hvad du ønsker. Dawa vejmidte plugin viser vejmidten for en valgt vej. Vil du gerne i s4's søgefelt kunne søge på en vejkode og så få vist vejen?

**Comment by albmorten** [comment]
Ja det var det vi tænkte . 

Min tanke var ikke et helt nyt punkt på listen i S4 men blot en udvidelse til den eksisterende vejnavne søgning så man også kunne finde veje via vejkode. det er en gang imellem nyttigt. 
Vi har haft det liggende som en egen opsat søgning på et lokalt datasæt  men tænker der måde være andre end os der kunne bruge det nogle gange.

**Comment by klavspc** [comment]
Der kan nu søges på vejkode i s4.

Hvis s4 er sat op til at søge i én kommune (Og det er de fleste s4-installationer) så vil der blive søgt med vejkode, hvis man indtaster fire cire.

Hér er der blevet søgt på en vejkode i s4 mod Hørsholm (`municipality: '223'` i s4-plugin.xml).

![image](https://user-images.githubusercontent.com/3736091/45633891-4bdbd800-baa1-11e8-96f3-aa1104381bdc.png)

**Comment by birgithepaasch** [comment]
Hej Klavs - Så glæder vi os til at I også laver en løsning mht. at kunne søge på vejkode, når der søges ned igennem flere kommuner.  Under supplerende oplysninger vises fx vej med vejkoden på kortet  inkl. kommunenummeret foran (mouseover på globus = visning i kortet), kunne søgningen ikke bare laves tilsvarende :-)

**Comment by markusroesgen** [comment]
Vejkode søgning viser ikke altid det korrekte resultat. Det ser ud som om vejkode søgning fejler lige så snart den har fået fat i et vejnavn, der eksisterer flere gange i kommunen, se vedhæftet beskrivelse.
