### ISSUE TITLE
Tingbogoplysninger fra ejendom bestående af flere matrikler

### ISSUE THREAD

**Issue by ChristianHelringAndersen** [Septima/spatialsuite-s4#263]
Hej Klavs

En kollega har opdaget at hvis en ejendom består af flere matrikeller vil disse ikke figurere under tingbogs –listen med særskilt matrikelnummer. Er der muligheden for at tilføje et matrikelnummer til oversigten så man kan se, at der ikke er tale om en fejl?

![torbistvej13](https://user-images.githubusercontent.com/4671599/36370165-5ad94c0e-155e-11e8-81cf-0a86b5dd2ed8.png)

**Comment by klavspc** [comment]
Jeg skal forsøge at få det med i 2.8 som kommer snart

**Comment by klavspc** [comment]
Desværre - Søgeservicen i Tingbogen giver to resultater, men de præsenteres på samme måde. Dette er kaldet, der ligger bag @ChristianHelringAndersen's eksempel 

[https://www.tinglysning.dk/rest/soeg/Torbistvej 13 2610](https://www.tinglysning.dk/rest/soeg/Torbistvej%2013%202610) returnerer:
```xml
{
	"statuskode": 0,
	"statustekst": null,
	"items": [{
		"uuid": "bcf41507-1614-4db1-bbd7-235aeb701bda",
		"adresse": "Torbistvej 13 2610 Rødovre",
		"bog": "Tingbog"
	}, {
		"uuid": "3c98010b-854d-408c-8a8f-3e55aef28050",
		"adresse": "Torbistvej 13 2610 Rødovre",
		"bog": "Tingbog"
	}]
}
```

Vi håber på snarest at kunne indlæse Tinglysninger fra Cognito og Lois - Dette vil give mere fleksibilitet. Der kan ligge et par dages udvikling i det - så når vi kender omfanget vender vi tilbage for at høre om der er nok der er interesserede i opgaven
