### ISSUE TITLE
s4 skriver s4plugoin som nyt felt i menuen

### ISSUE THREAD

**Issue by Andy-KK** [Septima/spatialsuite-s4#265]
Spatial suite version 3.13.0
s4 version 2.7.1
![udklip](https://user-images.githubusercontent.com/8900845/36480027-b2670eac-1702-11e8-9df5-68173d7911bb.PNG)

**Comment by klavspc** [comment]
@Andy-KK kan du vedlægge dit skin? Så vil vi forsøge at få det løst til v. 2.9

**Comment by klavspc** [comment]
Fejlkonfiguration af s4 - Det er vigtigt at s4's tools hedder _**s4-plugin**-xxx.xml_

Se navnekonvention i dokumentationen: https://github.com/Septima/spatialsuite-s4#create-profile-specific-search-tools
