### ISSUE TITLE
Opslag i planer

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#274]
Opslag i planer via S4 fejler, sikkert fordi det er plansystem der bruges istedet for plandata.dk
![plansystem_error_s4](https://user-images.githubusercontent.com/21097639/41768393-6495e536-760c-11e8-8fe9-5989608f7873.PNG)

**Comment by puwose** [comment]
Det virker på vores interne løsning, som kører på nyeste version af S4.
Måske skal jeg bare opdatere vores borgersite med nyeste version af S4.....

**Comment by puwose** [comment]
Så ligger den nyeste version på borgersitet, men jeg får fejlen "Der opstod en fejl: TypeError: Failed to fetch"

**Comment by klavspc** [comment]
Ja, nyeste version kører mod plandata. Den forrige version, som screen-shottet er fra, kørte mod plansystem, som nu er udfaset. Så du skal bare opdatere borgersitet.

Men: Nogle steder ser vi at kaldet til plandata fejler i Internet Explorer. Vi arbejder på højtryk med at finde årsagen. Chrome, Firefox og Edge virker. (Se #275)

**Comment by puwose** [comment]
Jeg bruger Chrome, og får stadig fejlen "Der opstod en fejl: TypeError: Failed to fetch"
Jeg har restartet SPS og tømt cache (og prøvet på flere maskiner)

**Comment by puwose** [comment]
Hvis jeg indlæser "usikre scripts" virker det.
![usikre_scripts](https://user-images.githubusercontent.com/21097639/41770220-e39992ec-7611-11e8-90b6-5e296eec77e0.PNG)

**Comment by puwose** [comment]
Har lige snakket med vores IT-afd, og det vil kun komme til at virke hvis plandata.dk kører SSL
