### ISSUE TITLE
Link til dokumenter i Tinglysningen via KMD Cognito Ejendomsbogen

### ISSUE THREAD

**Issue by MichaelDavidKnudsen** [Septima/spatialsuite-s4#277]
KMD har en løsning til deres Cognito database, som giver adgang til Tinglysningen. Den hedder KMD Cognito Ejendomsbogen, og indeholder data fra ejendomsbogen inkl. links. Med den løsning (inkl. KMD Cognito Links, som følger med) skulle der blive mulighed for, enten via GIS, WebGIS, CAD, Excel etc. , at fremsøge alle detaljer om den pågældende ejendom eller de pågældende dokumenter som ejendomsbogen indeholder.
 
I dag er der et link til Tingbogen i Septima Search, men her får man desværre ikke mulighed for at se de pågældende dokumenter.
 
Det ville være oplagt, at få Septima Search til at anvende KMD Cognito Ejendomsbogen. Hvad siger du til det? Jeg vil tro, at en hel del kommuner med KMD Cognito vil være interesseret.

**Comment by klavspc** [comment]
Vi er i gang med at integrere til Cognito fra Septima Search Server.

I Search Server er vi også ved at lave nogle gode ejendomssøginger mod Datafordeleren.

Når Search Server er klar til levering vil vi give alle S4-kunder et tilbud om opgradering. Med Search Server kan man med én konfiguration have samme søgninger i SpS, QGIS, ArcGis og [OneDoor](http://one-door.septima.dk/#/Dawa/Adresse/0a3f507a-6fa1-32b8-e044-0003ba298018). Meget mere om det senere
