### ISSUE TITLE
"Vis ejendomsoplysninger" i søgeresultat virker først, når toolet er aktiveret udenfor S4

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/spatialsuite-s4#286]
Ved søgning på fx adresse virker "Vis ejendomsoplysninger" ikke, før toolet er blevet aktiveret via E-knappen i SpS.

**Comment by klavspc** [comment]
I seneste version blev E_Knap-toolet opdateret til netop at løse dette problem og det _skal_ selvfølgelig rettes så det virker.

Lad mig lige høre til din installation @Ellebjerg : Har du et custom tool til E-Knappen? _Hvis_ du har så skal du opdatere dette så det får ændringerne med. Det drejer sig om [denne linie](https://github.com/Septima/spatialsuite-s4/blob/master/tools/s4-eknap-plugin.xml#L57) i koden.

`if (eknapModule === null){` er blevet rettet til
`if (typeof eknapModule === 'undefined' || eknapModule === null){`

Sig endelig til, hvis det ikke er et custom tool, der giver problemet - så skal det jo løses

**Comment by Ellebjerg** [comment]
Vi har standardversion, men det er lige gået op for mig, at det virker fint i emdb2. Det er i emdb3, som vi har i test, at det går galt.

**Comment by klavspc** [comment]
Jep - s4 kan ikke klare emdb3 endnu. emdb3 er lige ved at komme ud af test.

Har kontaktet Sweco for at få emdb3 installeret og afprøvet i s4.
