### ISSUE TITLE
Søgning i html

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#288]
Vil S4 kunne sætte op til at søge i vejledninger, der ligger på vores Medarbejderportal

**Comment by puwose** [comment]
![snipimage](https://user-images.githubusercontent.com/21097639/48062787-4f4b3000-e1c3-11e8-8356-0aab17ff5e0f.JPG)

**Comment by klavspc** [comment]
Fritekst-søgning i dine guides er ikke noget s4 umiddelbart kan. Hvis du indekserer dine guides på en-eller-anden måde (Elastic-search eller i sql-server, hvis den kan det) så vil der være mulighed for at forespørge i indekset.

Hvis du derimod kan konstruere en oversigt over dine guides i json-format så kan du måske bruge det _eksperimentelle_ guide-searcher-tool som du finder her: https://github.com/Septima/spatialsuite-s4/blob/master/tools/s4-details-guides-plugin.xml

Det er denne del af toolet du skal erstatte med din egen liste:
```
{title: "Guide 1", description:"Beskrivelse af guide 1", text: "Dette er den lange tekst, der beskriver hvad guide 1 omhandler", link: "http://www.disney.com"},
{title: "Guide 2", description:"Beskrivelse af guide 2", text: "Dette er den lange tekst, der beskriver hvad guide 2 omhandler", link: "http://www.cnn.com"}
```

Hvis dette eksperimentelle ikke længere virker (Det er et par s4-versioner gammelt) eller du gerne vil have en helt anden funktionalitet - så vend tilbage

**Comment by puwose** [comment]
Hej Klavs
Det prøver vi

**Comment by puwose** [comment]
Hej Klavs
Kan man gøre sådan, at den lange tekst "word wrapper"?
![s4-guides](https://user-images.githubusercontent.com/21097639/48134935-c0f6ad00-e29b-11e8-9297-b7cdab45eb78.JPG)

**Comment by puwose** [comment]
Jeg kan også bare bruge "</br>"

**Comment by puwose** [comment]
Jeg kan også bare bruge `</br>`
Jeg siger til, hvis vi vil have lavet det mere elegant :-)
