### ISSUE TITLE
S4 -Sps. 4.0 - Søgemarkering kan ikke slettes

### ISSUE THREAD

**Issue by birgithepaasch** [Septima/spatialsuite-s4#297]
Søgemarkering kan ikke fjernes vha. ”slet søgegeometri”, når der fx søges på en vejstrækning, adresse mm.  Den sletter når der søges på ny, men ellers ikke.

**Comment by klavspc** [comment]
Sweco retter SpS således, at _Slet arbejdsgeometri_ virker.

Bemærk, at hvis _Opret og anvend arbejdsgeometri_ har været åbnet så virker _Slet arbejdsgeometri_. Det er det forhold som Sweco er ved at rette op på. Løses i næste release af SpS
