### ISSUE TITLE
Sortering af søgeresultat

### ISSUE THREAD

**Issue by flemmingrasbak** [Septima/spatialsuite-s4#299]
Hvordan sorterer jeg resultatet af en søgning på en datasource vi selv indekserer? Jeg har opsat en søgning der finder ejendomme, når man indtaster ejerens navn. Flere ejere kan have samme navn, så jeg vil gerne sortere resultatet efter ejers navn, adresse, postnummer.

**Comment by klavspc** [comment]
Fra [dokumentationen](https://github.com/Septima/spatialsuite-s4#configure-datasources-to-be-searchable):

> Sorting: Search results are sorted first by relevance and secondly by the order in which they are returned from the datasource. It's much quicker to sort directly in a view in the database than in the datasource definition.

At resultaterne bliver sorteret i samme rækkefølge som de er indekseret betyder, at du skal sortere ejendommene på ejers navn, adresse, postnummer allerede i datasourcen. Så vil de blive sorteret på samme måde i resultatatet. Det betyder, at du skal have en ORDER BY ind i din select, hvad enten det er et view eller sql direkte i en datasource. (Du kan også vælge sort i datasourcen, men det er meget hurtigere at sortere direkte i sql'en)

**Comment by flemmingrasbak** [comment]
Jeg har en ORDER BY i min select og i ad hoc søgningen vises datasorucen med den rigtige sortering, men i S4 bliver resultatet ikke sorteret. Min datasource er som flg:

<datasource displayname="Ejendoms ejerforhold" endpoint="ep_cognito_pg" name="ds_vw_ca_matriklers_ejerforhold">
        <table geometrycolumn="geom" name="(select * from cognito.vw_ca_matriklers_ejerforhold order by navn, adresse_ejer, postnummer_distrikt, ejendomsnummer) as ejerforhold" pkcolumn="ogc_fid"/>
</datasource>
