### ISSUE TITLE
Search Spatial Suite data misser den sidste række

### ISSUE THREAD

**Issue by jdgsolrod** [Septima/spatialsuite-s4#301]
Hej,
Alle vores søgeresultater mangler den sidste række i datasourcen. Vi havde fejlen på en ældre version af S4, men nu har vi installeret seneste version, og vi har stadigvæk problemet. 
![image](https://user-images.githubusercontent.com/28621416/52554242-76c71f80-2de6-11e9-8252-03e20b727fd2.png)

Eksempelvis har vi 5 almene boligselskaber, men kun 4 kommer med i S4-søgning. Vi har 42 institutioner, kun 41 kommer med i S4.

Mvh Jonas

**Comment by Ellebjerg** [comment]
Hvis det kan hjælpe med fejlsøgningen, kan jeg fortælle, at vi ikke har problemet i Hvidovre. Vi har kun et enkelt lag - folkeskoler, hvor tælleren er på, men her tæller den rigtigt.

Vh Lars

**Comment by jdgsolrod** [comment]
Hvis bare det var tælleren, der talte forkert. Desværre er der én institution, én forening, ét alment boligselskab o.s.v. som slet ikke kan søges frem. Den manglende række/feature (eller hvad jeg nu skal kalde det), er nederste række i tabellen, hvis man analyserer hele datasourcen fra ad-hoc analyse. 

Fælles for dem alle er, at data ligger i en postgis-database. 

Det ligner et loop, der fejler et eller andet sted.

**Comment by Ellebjerg** [comment]
...og jeg trækker lige min kommentar tilbage. Vi har også fejlen, det er bare mig, der ikke kan tælle til 9. Det er også sidste række, der mangler hos os, men det er op mod SQL Server.

**Comment by jdgsolrod** [comment]
:)

**Comment by klavspc** [comment]
Denne fejl er en tidligere fejl i jar-filen i WEB-INF/lib. Kan du
dobbeltchecke, at du også har opgraderet denne og at der kun er én jar-fil?

**Comment by rsp-solrod** [comment]
Det var mig der havde glemt jar-filen, da jeg sidst opdaterede... Nu hvor jeg har opdateret rigtigt, kan jeg finde alle fem almene boligselskaber. I det mindste lyder det til, at Lars måske også har glemt jar-filen, hvilket opmuntrer mig lidt :-)

**Comment by jdgsolrod** [comment]
Super

**Comment by Ellebjerg** [comment]
Vi har opdateret jar-filen, men vi har til gengæld ikke opdateret modulet. Vi kører version 2.9.6, så jeg opdaterer til 2.9.10.

**Comment by Ellebjerg** [comment]
Opdateringen af modulet hjalp  :-)
