### ISSUE TITLE
"Hvad gælder for matriklen" tager nabomatrikler med i konfliktsøgning

### ISSUE THREAD

**Issue by markusroesgen** [Septima/spatialsuite-s4#304]
Efter udført adressesøgning i s4 laver jeg en konfliktsøgning på matrikelniveau i detaljevisning ("hvad gælder for matriklen" og kan konstatere, at der bliver "taget for meget med" (nabomatriklerne), se skærmdump.

**Comment by markusroesgen** [comment]
![S4_hvad gælder for matriklen](https://user-images.githubusercontent.com/11993556/55614831-3654a400-578e-11e9-9266-517611656866.JPG)

**Comment by klavspc** [comment]
Lidt baggrund:

Funktionen _Hvad gælder for matriklen_ i adressesøgningen virker sådan at
1. matriklen hentes fra dawa,
2. denne matrikels geometri lægges ind som arbejdsgeometri i kortet og
3. den helt almindelige funktion _Hvad gælder for_ kaldes

Fejlen fremkommer fordi dawa leverer en simplificeret geometri som altså overlapper andre jordstykker. Det er der ikke så meget s4 kan gøre ved. Jeg vil kontakte dawa og bede om at de returnerer den korrekte geometri.

Du kan dog også, i din spatialquery, justere hvilket _minimumoverlap_, der skal opfyldes for at objekter medtages i resultatet. Her vil du også

**Comment by klavspc** [comment]
@markusroesgen : Har du haft mulighed for at teste om konfliktsøgningen er blevet bedre efter at sdfe har løst https://github.com/DanmarksAdresser/Dawa/issues/697?

**Comment by markusroesgen** [comment]
Hej Klavs,

Det virker fint nu; ingen nabomatrikler bliver taget med.

Hilsen, Markus
