### ISSUE TITLE
Udpegning af geometri "nulstilles" når man søger vha S4

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#305]
Opgaven går ud på at lave en hørringsliste over flere spredte jordstykker i kommunen, som man bruger S4 til at søge frem.
Hvis man markerer f.eks. et jordstykke vha arbejdsgeometri i Spatial Suite og søger (vha. S4) frem til et nyt jordstykke for at tilføje dette til hørinslisten forsvinder den først udpegede geometri.

**Comment by klavspc** [comment]
Ja, s4 viser resultater i kortet ved at fjerne eksisterende geometri og tegne den nye ind. S4 bruger arbejdsgeometri fordi det så er nemt at udføre print og _Hvad gælder for_ for det valgte.

Een løsningsmetode _kunne_ være at s4 detekterer om "Redigér arbejdsgeometri"-vinduet er åbent. _Hvis_ det er åbent så bliver det valgte tilføjet. Hvis det _ikke_ er åbent gør s4 som den altid har gjort.

Meld gerne tilbage hvordan det vil passe ind i jeres arbejdsgange eller om der er bedre måder. Løsningen er selvfølgelig afhængig af om det er muligt at detektere om "Redigér arbejdsgeometri"-vinduet er åbent, men det kan jeg snakke med Sweco om.

Spændende problem som, når det er løst hvordan det præcis skal løses, nok vil tage en dags tid at få på plads.

**Comment by puwose** [comment]
Vi løste det med EMDB3, der ikke sletter udpegede geometri, når man bruger S4.
Tænker også vi kan bruge adhoc
