### ISSUE TITLE
Porblem ved start af S4 i Internet Explorer, når themesearcher er slået til

### ISSUE THREAD

**Issue by rsp-solrod** [Septima/spatialsuite-s4#308]
Efter vores opgradering til Spatial Suite 4.0.2 er der kommet et problem med S4, når man bruger den fra Internet Explorer 11 eller Edge. Første gang man begynder at skrive i søgefeltet, så går alting i stå i flere sekunder, hvor man ikke kan indtaste og heller ikke får noget svar fra søgningen. Det sker tilsyneladende efter, at der er hentet info om temaer med kald til "http://webgis.solrod.dk/rest/profile/tea/allthemes/[...]?userthemes=true&publiconly=false&_=[...]"
Hvis jeg slår themesearch fra, så opfører S4 sig, som den skal igen - men man kan selvfølgelig ikke finde temaer, som vi gerne vil kunne. Så vidt jeg kan se, svarer allthemes-servicen hurtigt nok.

**Comment by klavspc** [comment]
@rsp-solrod : Kan du sikre dig at i

- har nyeste version af s4 ([2.9.13](https://github.com/Septima/spatialsuite-s4#basic-installation-and-test-1)) samt
- har installeret det hotfix til temavælgeren som sweco releasede 26/3 ([spatialmap-4.0.2a-hotfix-2-themeselector+ie.zip](http://dist.spatialsuite.com/spatialsuite/4.0.2a/hotfixes/spatialmap-4.0.2a-hotfix-2-themeselector+ie.zip))?

Hvis begge ting er på plads så lad mig vide om der stadig er problemer - ellers luk issue

**Comment by rsp-solrod** [comment]
Jeg har tjekket s4-versionen. Men hotfixet kunne godt være et problem. Jeg ser ikke ud til at have adgang til zip-filen. Men jeg kan lige spørge Sweco, om de har lagt det på i forbindelse med vores opgradering. Jeg vender tilbage og lukker, hvis det er det, der er problemet. Det er det nok..

**Comment by rsp-solrod** [comment]
Det virker efter hotfixet. Tak for hjælpen!
