### ISSUE TITLE
Rettet: Kan ikke åbne workspaces fra link i S4

### ISSUE THREAD

**Issue by rsp-solrod** [Septima/spatialsuite-s4#309]
Jeg har opdaget, at links til workspaces ikke virker i S4 lige nu. Muligvis efter opgradering til Spatial Suite 4.0.2. Jeg får en fejlbesked i JavaScript-konsollen: "param not found: module.workspace.js". Så vidt jeg kan se, er den parameter nu sat. Men der er vist et requirement til en color.js-fil, som ikke er der længere. Jeg kan se, at den fejler i at hente den, første gang jeg prøver at åbne et workspace.

**Comment by klavspc** [comment]
@rsp : Hvilken version af workspace har i? Og ses fejlen i alle browsere?

**Comment by rsp-solrod** [comment]
Jeg har set fejlen både i IE11, Edge og chrome. Vi har workspace version 4.0.1.

**Comment by ChristianHelringAndersen** [comment]
Hej
har lige tjekket og vi har den samme fejl. Tjekket i IE11, FF og Chrome (seneste versioner).

 SpS 4.0.2 / Workspace version 4.0.1

**Comment by markusroesgen** [comment]
Vi har den samme fejl (testet i IE 11 og Google Chrome)

SpS 4.0.2a, workspace version 4.0.1

**Comment by klavspc** [comment]
Fejlen gælder for workspace3 i SpS 4+.
Fejlen er fundet - rettes i næste version af s4

Indtil da _kan_ følgende rettelse lægges på

1. Udpak [denne .zip-fil](https://github.com/Septima/spatialsuite-s4/files/3599880/workspaceSearcher.zip) (udpakker til workspaceSearcher.js)

2. __Overskriv__ WEB-INF\config\modules\thirdparty\septima\s4\js\workspaceSearcher.js med den nye fil
3. Reload dit site (Admin-konsol->Reload)
