### ISSUE TITLE
Vejnavne fra flere kommuner i S4's adressesøgning

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#314]
Med dagens release af dawa har funktionaliteten i API'et ændret sig således, at matchende vejnavne fra hele landet vises i søgeresultatet. Det er stadig muligt at skrive videre i feltet, herunder postnummer for at snævre resultatet ind. Endvidere virker søgningen selvfølgelig også når man vælger den _rigtige_ vej.

Det er en _meget irriterende_ situation for brugerne, som dog ikke forhindrer dem i at finde den adresse de ønsker. Vi er i fuld sving med at analysere årsagen til- og løsningen på problemet.

**Comment by Ellebjerg** [comment]
Kan der ikke laves en nødløsning ved at tilføje en søgepolygon (kvadrat), som omslutter kommunen. Det vil da begrænse mængden af overflødige søgeresultater.

**Comment by klavspc** [comment]
Vi har nu udarbejdet en rettelse

* _Hvis_ du har seneste version af S4, 2.9.13, installeret så kommer nedenfor en opskrift på hvordan du tilretter din S4.
* Hvis du _ikke_ har den seneste version af S4 så kan du prøve om det virker - hvis det ikke virker så bør du opgradere

**_Opskrift_**

* Find filen \WEB-INF\config\modules\thirdparty\septima\s4\deploy.xml i dit sandkasse- eller test-site
* Følgende linie skal rettes
  * `<param name="s4.search.script">//search.cdn.septima.dk/4.7.3/septimasearch.min.js</param>`
  * rettes til:
  * `<param name="s4.search.script">//search.cdn.septima.dk/4.7.3.fixdawa/septimasearch.min.js</param>`
* Reload sitet i admin-konsollen - og tryk F5 i din browser.
  * Dine brugere behøver slet ikke at gøre noget efter du har eksporteret
* Test, at adressesøgningen virker - prøv Lærkevej eller andet vejnavn, som du deler med andre kommuner.
* Hvis alt ser normalt ud så er du færdig

Næste version af S4 indeholder selvfølgelig ændringerne

**Comment by klavspc** [comment]
Dawa har nu rullet dele af deres opdatering tilbage - så nu bør selv sites uden ovennævnte rettelse virke igen.
