### ISSUE TITLE
S4 v. 2.10.3 - vedtaget lokalplan - se plandokument, virker ikke

### ISSUE THREAD

**Issue by birgithepaasch** [Septima/spatialsuite-s4#315]
Når der laves en adresse søgning og man vil se vedtaget lokalplan, vises link til plandokumentet ikke.

**Comment by klavspc** [comment]
Har du korrekt(e) tool(s) i din profil? Det er et tool, der skriver linket.

Se tools for planer her: https://github.com/Septima/spatialsuite-s4/tree/master/tools#s4-planSystem-plugin

Almindeligt link til plansystemet:
`<tool module="s4" name="s4-planSystem-plugin" />`

**Comment by birgithepaasch** [comment]
Jo, jeg har det korrekte tool på, det virkede fint inden opgraderingen.

**Comment by birgithepaasch** [comment]
Hvis der kun søges på vedtagne lokalplaner - kan dokumenterne hentes, det er kun når der søges på en adresse og vil hente de planer der hører til
