### ISSUE TITLE
S4 v 2.10.3 - link fra detailvisningen virker ikke

### ISSUE THREAD

**Issue by birgithepaasch** [Septima/spatialsuite-s4#316]
Når der søges på adresse og vi bruger funktionen nærmeste skole, virker linket ikke fra detailvisningen ikke.

**Comment by klavspc** [comment]
Er det linket til skolen, der ikke virker? Vises det ikke eller fejler det?

Kan du vedlægge et screenshot og markere, hvad der ikke virker? Evt sammen med fejlmeddelelse, hvis der er en. (F12 i Chrome åbner konsollen og hvis der er fejl vises det med rød ikon)

**Comment by birgithepaasch** [comment]
Jeg kan ikke se at den melder fejl ved F12
Det har før virket. Når der klikkes på afstand tiller skolenavn, zoomes i kortet som viser skolen
Når der klikkes på globus vises ruten. 
Før opgraderingen kunne vi også linke til detailvisningen for skolen. 
Jeg har prøvet at vedhæfte png - det ser ikke ud som om det virker...
