### ISSUE TITLE
Version 2.10.3:  Flere klik til den søgte adresse

### ISSUE THREAD

**Issue by markusroesgen** [Septima/spatialsuite-s4#317]
Efter opgradering til v2.10.3 kommer den søgte adresse ikke direkte frem som resultat.
Før opgraderingen kunne man direkte klikke på den fundne adresse i resultatlisten:

![s4_1](https://user-images.githubusercontent.com/11993556/65322338-cfde0980-dba6-11e9-92e9-1f712fa352ed.jpg)

Efter opgradering ser det sådan ud og man skal klikke en ekstra gang for at finde frem til adressen:

![s4_2](https://user-images.githubusercontent.com/11993556/65322381-f56b1300-dba6-11e9-837e-6acb98a66ec6.jpg)

![s4_3](https://user-images.githubusercontent.com/11993556/65322443-26e3de80-dba7-11e9-92b5-aab4945f95b2.jpg)

Kan det rettes, så det er mere brugervenligt igen?

Mvh Markus

**Comment by klavspc** [comment]
Har i sat _minimumShowCount_ for dawasearcheren som beskrevet i [vejledningen](https://github.com/Septima/spatialsuite-s4#s4customization)? 
```
//Adressesøgning i DAWA
// minimumShowCount: How many adresses should always be shown
dawasearcher: {enabled: true, info: true, print: true, minimumShowCount: 3},
```

**Comment by Ellebjerg** [comment]
Hej Markus
Vi havde samme "problem". Det er, som Klavs skriver, et spørgsmål om at sætte minimumShowCount til et antal større end nul.
Tidligere blev der, hvis denne stod til nul, vist tre resultater, når der var indtastning i søgefeltet, mens der ikke blev vist nogen, når der ikke var indtastet noget. Nu vises det angivne antal adresseforslag uanset, om der er indtastning i søgefeltet eller ej. I Hvidovre har vi valgt at køre videre med den gamle version af S4, da vi oplever det som forvirrende, at der gives tre adresseforslag, når der ikke er indtastet noget i søgefeltet.

Vh Lars

**Comment by markusroesgen** [comment]
Vi har sat minimumShowCount til "0" og har ikke ændret i denne fil i et helt år. Grunden til at vi har sat det til "0" er at vi vil slippe for den (forvirrende) visning af s4-vinduet før man indtaster i søgefeltet:

![s4_6](https://user-images.githubusercontent.com/11993556/65324808-9066eb80-dbad-11e9-909a-833aec684d85.jpg)

Selv om vi har sat værdien til "0" virkede det inden opgradering til v2.10.3. på den måde, at den fundne adresse direkte blev vist i resultatlisten, se vores eksterne borger-site, som stadig kører på den tidligere version og hvor minimumShowCount er "0":

Søg på "Skovbrynet 34":
https://webkort.sonderborg.dk

**Comment by markusroesgen** [comment]
Desuden virker "minimumShowCount " ikke helt som forventet (i version 2.10.3?). Sætter jeg værdien til "1" eller "2" er visning før indtasting altid som følgende:

![s4_7](https://user-images.githubusercontent.com/11993556/65325413-091a7780-dbaf-11e9-8e19-169af2ca74a8.jpg)

Og efter indtasting af korrekt adresse:

![s4_8](https://user-images.githubusercontent.com/11993556/65325423-146da300-dbaf-11e9-8cc2-5c07ee5a6fce.jpg)

**Comment by klavspc** [comment]
Se #321
