### ISSUE TITLE
Kosmetisk fejl i kolonnevisning (lokal datasource)

### ISSUE THREAD

**Issue by markusroesgen** [Septima/spatialsuite-s4#318]
Er label-navnet et ord med mange bogstaver fx "dagtilbudsområde", bliver resultatet vist med en kosmetisk fejl. Der er ikke nok afstand mellem label og value.

Skal afstanden mellem label og value være større som standard?

![s4_4](https://user-images.githubusercontent.com/11993556/65323635-344e9800-dbaa-11e9-816d-df0f3ba415ec.jpg)

![s4_5](https://user-images.githubusercontent.com/11993556/65323653-3ca6d300-dbaa-11e9-9ec7-849bc543c88e.jpg)

**Comment by klavspc** [comment]
Indtil vi slipper en mere elastisk version af gui'en så vil der være en max længde, der ser godt ud.

Indtil da må du forkorte eller finde på noget andet. Evt. sådan her:
```
<label>'Dagtilbudsområde: ' + dagtilbudsomr</label>
<value></value>
```
