### ISSUE TITLE
Version 2.10.3: "Hvad gælder for" kommer ikke direkte frem i adresseresultat

### ISSUE THREAD

**Issue by markusroesgen** [Septima/spatialsuite-s4#319]
Efter en søgning på "Skovbrynet 34" klikker jeg på den markerede pil:

![s4_13](https://user-images.githubusercontent.com/11993556/65326809-98755a00-dbb2-11e9-8c25-29a0ad9997b4.jpg)

Derefter klikker jeg på denne markerede pil:

![s4_12](https://user-images.githubusercontent.com/11993556/65326688-58ae7280-dbb2-11e9-902b-27c9617e92c7.jpg)

Den fundne adresse viser ikke "Hvad gælder for" i detaljevisning , kun "hvad gælder for matriklen". Der bliver heller ikke zoomet til adressen i kortet:

![s4_9](https://user-images.githubusercontent.com/11993556/65326214-3f58f680-dbb1-11e9-90ff-090a702d5278.jpg)

Klikker jeg på "pil tilbage" øverst i venstre hjørne, kommer jeg tilbage til den samme visning som i skærmdump nr. 2. Jeg klikker igen på samme pil:

![s4_12](https://user-images.githubusercontent.com/11993556/65327035-24878180-dbb3-11e9-855a-26c0a9b069fd.jpg)

Nu indeholder detaljevisning også "hvad gælder for" og der bliver zoomet til den fundne adresse i kortet:

![s4_11](https://user-images.githubusercontent.com/11993556/65326331-7c24ed80-dbb1-11e9-9ae2-9ffebb54d271.jpg)

Hvorfor virker det først ved anden forsøg?

Vi bruger efterfølgende tools:

![s4_14](https://user-images.githubusercontent.com/11993556/65327280-d3c45880-dbb3-11e9-8675-0433410f4a99.jpg)

**Comment by klavspc** [comment]
@markusroesgen : Tak for din melding - Jeg har prøvet flere gange, men jeg kan desværre ikke genskabe dit problem.

Hvilken version af SpS har du? Er det muligt for dig at åbne konsollen (F12 i Chrome) og se om der kommer nogen fejl?

**Comment by markusroesgen** [comment]
Hej Klavs

Vi kører SpS v4.0.2 og jeg kan heller ikke genskabe ovenstående i Google Chrome, kun i IE11.

Mvh Markus

**Comment by klavspc** [comment]
Kan desværre ikke genskabe noget sted.

Der har været lidt opdateringer og oprydninger omkring "Hvad gælder for". (bl.a. #327) så lad os se om det stadig er et problem hos dig i den nye 2.11
