### ISSUE TITLE
v. 2.10.4 ude med lille ændring i visning af adresser

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#321]
Dawasearcher tager i v 2.10.4 nu *to* parametre, som styrer forhåndsvisning af resultater.

Fra [dokumentationen](https://github.com/Septima/spatialsuite-s4#customization-of-s4-tool):
`minimumShowCount: 3, showMinimumOnBlank: true`
* Parameteren _minimumShowCount_ bestemmer hvor mange adresser man vil se. (Denne parameter har eksisteret længe og har ikke ændret betydning) Bemærk, at værdier under 3 ikke accepteres
* Parameteren _showMinimumOnBlank_ er ny og bestemmer om man vil se forhåndsvisning uden at have indtastet noget.

**_Opgradering:_**

Den nye version skal blot udpakkes og overskrive den eksisterende v 2.10.3.
* [Direkte link til download](https://github.com/Septima/spatialsuite-s4/archive/2.10.4.zip)
* [Vejledning](https://github.com/Septima/spatialsuite-s4#basic-installation-and-test-1)

Hvis du endnu ikke har opgraderet til v 2.10.3 så [læs nyhedsbrevet her](https://mailchi.mp/4e49cfdb24cd/version-2103-af-septima-search-for-spatial-suite-s4)

**Comment by markusroesgen** [comment]
Hej Klavs

Jeg har opgraderet til version 2.10.4 og parameteren _showMinimumOnBlank_ virker fint.

Jeg synes at parameteren _minimumshowcount_ ("how many adresses should always be shown" = "bestemmer hvor mange adresser man vil se") er misvisende. Parameteren beskriver  hvor mange adresser der skal vises som maksimum men ikke altid.

Jeg har sat parameteren _minimumshowcount_ til "20" og resultatet for søgningen "Møllegade 2" er efterfølgende 20 adresser (der findes flere men der vises maks. 20). Hvorfor bliver der vist en enkelt vej "Møllegade 6440 Augustenborg" i resultatlisten og ikke flere veje fx den i Nordborg eller Sønderborg?

![s4_15](https://user-images.githubusercontent.com/11993556/65581736-4b133700-df7c-11e9-9684-e11863d13e0d.jpg)

En søgning på "Møllegade 12" viser færre resultater (fordi der findes ikke 20 resultater). Hvorfor bliver der vist en enkelt vej "Møllegade 6310 Broager" i resultatlisten og ikke flere veje fx den i Augustenborg eller Sønderborg?

![s4_16](https://user-images.githubusercontent.com/11993556/65582107-0340df80-df7d-11e9-9dee-e1c939d3138e.jpg)

En søgning på "Møllegade 1" leverer et resultat, som jeg ikke havde forventet. Der vises kun fem veje, selv om der findes flere end 20 adresser. Hvorfor bliver adresserne ikke vist?

![s4_17](https://user-images.githubusercontent.com/11993556/65582659-2029e280-df7e-11e9-9c36-cecc3daf92f5.jpg)

Tak for forklaringerne.

Mvh Markus

**Comment by klavspc** [comment]
@markusroesgen 
* Parameteren hedder minimumshowcount fordi uden den ville du slet ikke se nogen adresser overhovedet - kun et resultat, der hedder _Adresser_ som brugeren så skal klikke på for at komme ind og se adresser. Dvs parameteren garanterer, at der bliver vist nogen selvom brugeren ikke har valgt kun at søge i adresser. Hvis der ikke er 20 adresser, der opfylder søgningen så kan Search ikke vise 20
* Du har ret i at det virker mærkeligt hvilke veje, der bliver vist - jeg vil se på det.

Opret gerne separate issues for fejlmeldinger og spørgsmål

**Comment by markusroesgen** [comment]
Hej Klavs

Jeg er enig med din forklaring og netop derfor synes jeg at et parameter navn _maximumshowcount_ vil være mere logisk ("how many adresses should be shown at most as a result" = "bestemmer hvor mange adresser der maksimalt skal vises i resultatet").

Mvh Markus
