### ISSUE TITLE
COWI gadefoto/skråfoto integration

### ISSUE THREAD

**Issue by albmorten** [Septima/spatialsuite-s4#322]
Hej

Den nye SDFE skråfoto integration i S4 er rigtigt fed og nu er vores spørgsmål så om i kan lave noget lignende til COWIs gadefoto/skråfoto ? :)

I sps findes standard modulet cowi-gadefoto hvor man sætter en række parametre der skal bruges til at åbne det rigtige cowi gadefoto projekt.

eksempel på link til vores projekt i Albertslund som åbnet med swecos gadefoto tool:

https://cmv.cowi.com/?u=xxxxx&p=xxx&origin=desktop&project=Albertslund%20Kommune,%20skråfotos&vLayers=module.cowi-gadefoto.layers.visible&hLayers=module.cowi-gadefoto.layers.hidden&assLayers=module.cowi-gadefoto.layers.visible&dssLayers=module.cowi-gadefoto.layers.hidden&maximize=module.cowi-gadefoto.layers.maximize&x=709593.6000000002&y=6173766.4&srid=25832

**Comment by klavspc** [comment]
Nyt tool _s4-cowi-gadefoto-plugin_ linker til DDG for adresser og matrikler

Toolet kræver, at standard-modulet _cowi-gadefoto_ er inkluderet i modules.xml og konfigureret med de nødvendige cbinfo-parametre.

Inkludér følgende tool i profilen:
`<tool module="s4" name="s4-cowi-gadefoto-plugin"/>`
