### ISSUE TITLE
Temasøgning uden resultater på eksternt site

### ISSUE THREAD

**Issue by jdgsolrod** [Septima/spatialsuite-s4#323]
Temasøgning fejler på vores borger-site (kort.solrod.dk). Det virker fint på vores interne site.

På borger-sitet og det interne site køres med følgende versioner:
S4 version 2.10.4
S4 jar-fil version 1.2.0
SpS version 4.0.2a med hotfix 1,2,3,4

Vi oplever, at der ikke kommer nogle søgeresultater fra temaer, når vi sørger på borger-sitet:
![image](https://user-images.githubusercontent.com/28621416/67001887-00985c80-f0db-11e9-8903-22600f4303a2.png)

Mens vi med samme søgning (i samme profil) på internt site får resultat:
![image](https://user-images.githubusercontent.com/28621416/67001857-f0807d00-f0da-11e9-9ed8-b7b25627f913.png)

Fejlbeskeden herunder kommer i js-konsollen kun på borger-sitet, og den kommer i det øjeblik S4's inputfelt får fokus.
![image](https://user-images.githubusercontent.com/28621416/66989775-4cd8a200-f0c5-11e9-9ef3-750b20055cd1.png)

**Comment by klavspc** [comment]
Vi ser på det

**Comment by klavspc** [comment]
Løst i næste version
