### ISSUE TITLE
Adresse søgning viser ikke forventede resultater

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-s4#324]
Adresser forslag kommer ikke frem

![image](https://user-images.githubusercontent.com/8122296/67190185-c9ce8900-f3ef-11e9-8c0e-a67820eaa0c0.png)

Forslag kommer dog efter man skriver komma

![image](https://user-images.githubusercontent.com/8122296/67190214-d7840e80-f3ef-11e9-8c1c-fc5badcd060f.png)

Det ser ikke som om der er problem hos DAWA

![image](https://user-images.githubusercontent.com/8122296/67190112-ac012400-f3ef-11e9-92f5-b5009aeeb780.png)

**Comment by gis-haderslev** [comment]
Vi bruger s4 version 2.10.4 hvis det er relevant

Adressen kommer heller ikke frem når man vælger at søgekategori "adresser"
![image](https://user-images.githubusercontent.com/8122296/67190407-321d6a80-f3f0-11e9-9115-a36463c1c935.png)

**Comment by klavspc** [comment]
Fejlen er fundet og rettes i næste version

_Forklaring:_

I modsætningen til [specifikationen](https://dawa.aws.dk/dok/api/vejstykke#s%C3%B8gning) søger dawa faktisk også i vejkode når man søger efter veje. De to veje, der vises istedet for det forventede resultat, har begge en vejkode, der starter med _163_

S4 virker på den måde, at hvis der returneres mere end én vej så vises disse istedet for adresser; Derfor vises de to veje i resultatet.

_Løsningen:_

S4 søger ikke i veje, hvis søgestrengen indeholder noget, der kunne være et husnummer.

_Resultat:_

Der returneres nu ikke veje og adresseresultatet bliver nu vist.
