### ISSUE TITLE
Indexsearcher - Langsom visning

### ISSUE THREAD

**Issue by birgithepaasch** [Septima/spatialsuite-s4#326]
Egne oprettede søgninger har været super godt. Efter opgraderingen er det dog som om at søgninger der indeholder flader - tager mega lang tid om at blive vist. Kan der gøres noget ved det? 
Vh/Birgithe

**Comment by markusroesgen** [comment]
Vi oplever samme problem både i IE og Chrome.
Klikker jeg på vores skoledistrikt-søgning i s4...

![s4_18](https://user-images.githubusercontent.com/11993556/67268981-12e91080-f4b6-11e9-926c-07bcb2a4fa58.jpg)

... skal man vente ca. 20-25 sekunder med dette billede...

![s4_19](https://user-images.githubusercontent.com/11993556/67268993-19778800-f4b6-11e9-8307-c5dd9f03d898.jpg)

... før de 16 objekter fra skoledistrikt-søgningen dukker op.

![s4_20](https://user-images.githubusercontent.com/11993556/67268998-1da3a580-f4b6-11e9-9422-259b48d5edc4.jpg)

Klikker jeg efterfølgende på et af de fundne objekter i s4, bliver objektet vist med det samme i kortet:

![s4_21](https://user-images.githubusercontent.com/11993556/67269012-24321d00-f4b6-11e9-809b-e674894df182.jpg)

Der er ingen performance problemer med vores andre lokale søgninger (punkt/linie).
Mvh Markus

**Comment by klavspc** [comment]
Performance er blevet påvirket fordi geometrierne nu returneres sammen med søgeresultatet (Før blev de først hentet når der blev klikket på et resultat)

Vi vil se, hvad der kan gøres - det er ikke sikkert, at det behøver at være hele den rå geometri, der returneres

**Comment by birgithepaasch** [comment]
Godt Nytår :-) 
Er der noget nyt på dette issue ?
Jeg har lavet ekstra temaer (simplified, som du foreslog) som kun bruges som søgegeometri - det vises hurtigt, men jeg mister jo muligheden for at se relaterede temaer til det oprindelige temasæt. 
Jeg håber I finder en brugbar løsning.
Vh/Birgithe

**Comment by klavspc** [comment]
Der er en løsning på vej i en kommende version af s4.

Den lange forklaring: Geometrien kommer med over fordi den i nogle tilfælde bliver brugt til at afgøre hvorvidt der skal vises detaljer for en valgt feature. I en kommende version af s4 vil dette blive erstattet med information om _hvorvidt_ der findes geometri, men altså ikke geometrien selv før den er nødvendig. Der er en del arbejde med dette da s4 i nogle tilfælde _ønsker_ geometrien, nemlig i detaljevisning, hvor man gerne vil kunne føre musen henover et resultat og se det highlightet i kortet.
