### ISSUE TITLE
S4 - Hvad gælder for knapper virker ikke i Spatial Suite 4.1

### ISSUE THREAD

**Issue by petergot** [Septima/spatialsuite-s4#327]
Efter opgradering til Spatial Suite 4.1 virker Hvad Gælder for knapper ikke. Vi benytter udelukkende Chrome, men det virker heller ikke i IE

Vores S4 opsætning i profilen ser således ud

<tool module="emdb" name="horingsliste-plugin"/>
        <include mustexist="true" onlychildnodes="true" src="[cbinfo.profile.themeactions.include]"/>
        <tool dir="custom" name="s4-plugin-8210-all"/>
        <tool module="s4" name="s4-soeg-egne-vejmidter-plugin"/>
        <tool module="s4" name="s4-adresse-hgf-matrikel-plugin"/>
        <tool module="s4" name="s4-eknap-plugin"/>
        <tool module="s4" name="s4-sdfe-oblique-plugin"/>
        <tool module="s4" name="s4-cvr-virk-plugin"/>
        <tool module="s4" name="s4-planSystem-plugin"/>
        <tool module="cvr_analyse" name="cvr_analyse_plugin"/>
        <tool module="demografi" name="demografi_plugin"/>
        <tool module="etnicitet" name="etnicitet_plugin"/>
        
MVH  
Peter G. Petersen, Aarhus Kommune

**Comment by markusroesgen** [comment]
Vi har samme udfordring i vores miljø (SpS 4.1).
Mvh Markus

**Comment by markusroesgen** [comment]
Det er både "hvad gælder for" og "hvad gælder for matriklen", der ikke virker i SpS 4.1.

**Comment by klavspc** [comment]
Løst i kommende version 2.11
