### ISSUE TITLE
S4 i SpS 4.1 driller i panel-middle placering

### ISSUE THREAD

**Issue by albmorten** [Septima/spatialsuite-s4#328]
Hej

I SpS 4.1 driller S4's css når man bruger den nye docking funktion på f.eks infobokse når S4's placering er sat til panel-middle i configgen. dele af s4 flytter sig som det skal. nogle dele gør ikke.

![s4sps](https://user-images.githubusercontent.com/24713112/69051404-7d816380-0a04-11ea-86df-c00194fe2d69.jpg)

**Comment by flemmingrasbak** [comment]
Vi oplever samme problem i Næstved, bortset fra at S4 boksen ikke flytter sig overhovedet.

**Comment by klavspc** [comment]
_panel_-property i custom tool er udvidet med en ny mulighed, nemlig 'map-top-right', som placerer søgefeltet i kortet øverst til højre
```
//  'default': same as panel-middle
//  'panel-middle': Force s4 to menu linie (right justified)
//  'map-top-right': SpS 4.1+ only
panel: 'default',
```
**_map-top-right_**:
![image](https://user-images.githubusercontent.com/3736091/69154768-e6d6a480-0ae0-11ea-8d2d-7f5758d90241.png)

**_panel-middle_**:
![image](https://user-images.githubusercontent.com/3736091/69154954-31f0b780-0ae1-11ea-9c7c-3b62035e750c.png)
