### ISSUE TITLE
Stednavne-søgningen virker ikke

### ISSUE THREAD

**Issue by ikast-mofri** [Septima/spatialsuite-s4#330]
Vi har sat stednavne på under Geodatastyrelsen-geosearch i vores S4-plugin, men det kommer ikke til at fremgå som et datasæt, der kan søges i.

**Comment by klavspc** [comment]
Det er fordi stednavne-søgning konfigureres som en separat linie
Fra [dokumentationen](https://github.com/Septima/spatialsuite-s4#customization-of-s4-tool):
```
//Geodatastyrelsen - Stednavne i geosearch
geostednavnesearcher: {enabled: true, info: true, print: true}, 
```
Hvis du ikke har ovenstående linie i dit custom tool så vil det være en god idé at opdatere det. Du kan se det medleverede tool i s4-modulet. _s4/tools/s4-plugin-dk-all.xml_
