### ISSUE TITLE
Fremsøgning af lokalplan giver forkert geometri

### ISSUE THREAD

**Issue by tleegaard** [Septima/spatialsuite-s4#331]
Når vi søger efter lokalplanen "BY5" er resultatet følgende polygon:
![image](https://user-images.githubusercontent.com/5439041/69238944-6cb62680-0b99-11ea-8753-eb9cc7839218.png)

Men lokalplanens afgrænsning ser ifølge Plandata således ud:
![image](https://user-images.githubusercontent.com/5439041/69239033-9e2ef200-0b99-11ea-841f-49e0649e5480.png)

Som det ses af skærmbilledet overlapper lokalplanen BY5 med både 1.31 og 1.41. Er det årsagen til forskellen i de fremsøgte geometrier?

**Comment by klavspc** [comment]
Hej Klaus

Plan-id er: *1060520*

*Vores *http://septima.dk/plandk2/ viser denne afgrænsning af planen og de
fire delområder

[image: image.png]


Med venlig hilsen


*Morten Lind*
Konsulent
Direkte: +45 3168 3640 morten@septima.dk
- - -
Septima P/S www.septima.dk
Frederiksberggade 19, 2. 1459 København K
Tlf: +45 7230 0672 - Cvr: 34900841


Den ons. 20. nov. 2019 kl. 13.30 skrev tleegaard <notifications@github.com>:

**Comment by klavspc** [comment]
Ja, geometrien er ikke korrekt på denne plan og det gælder også andre planer i vort index.

_Årsag:_
Vort opdateringsscript opdaterer index ved opdateringer i plandata og indlæser kun ændrede data - dette script tager ikke nok højde for opdateringer af subversioner af planer

_Løsning:_
Vi er i gang med at opdatere vort script og så snart det er kørt successfuldt vil de korrekte geometrier fremgå.

Dette issue lukkes da separat issue er oprettet for vores dataindlæsning
