### ISSUE TITLE
Sort prik til venstre for søgeboks

### ISSUE THREAD

**Issue by flemmingrasbak** [Septima/spatialsuite-s4#334]
Har netop installeret den nyeste version af S4 og valgt panel: 'map-top-right'
Der kommer en sort prik til venstre for søgeboksen.
![Udklip](https://user-images.githubusercontent.com/8004072/70257018-d7ff1b80-1789-11ea-9afd-ca052eb2b490.PNG)

**Comment by klavspc** [comment]
Den bliver fjernet i kommende version af s4

**Comment by klavspc** [comment]
@flemmingrasbak Jeg kan desværre ikke genskabe prikken her hos mig. I hvilken version af SpS ser du fejlen?

**Comment by flemmingrasbak** [comment]
Vi kører 4.1.0

**Comment by flemmingrasbak** [comment]
Vi kører 4.1.0

**Comment by flemmingrasbak** [comment]
Kom til at lukke issuet ved en fejl

**Comment by klavspc** [comment]
@flemmingrasbak Tror jeg har fundet den. Vil du teste om jeg har ret?

Kan jeg bede dig gå ind s4-modulets s4.css og lægge een linie til? I modules/thirdparty/septima/s4/css skal du tilføje linien `list-style: none;` Forsvinder prikken?
![image](https://user-images.githubusercontent.com/3736091/75673884-43bb2c80-5c84-11ea-8227-205a4eb23fba.png)

```
.inputcontainer-spacer {
    list-style: none;
    width: 400px;
    height: 30px;
}

```

**Comment by flemmingrasbak** [comment]
Ja, nu forsvandt den :-)

**Comment by klavspc** [comment]
Med i næste version
