### ISSUE TITLE
Oplysninger i presentation vises ikke i søgeresultatet

### ISSUE THREAD

**Issue by ikast-mofri** [Septima/spatialsuite-s4#335]
I min presentation har jeg angivet en række columns. F.eks.:

        <column name="">
            <label>'Overløb pr. år'</label>
            <value>overloeb_pr_aar</value>
        </column>
		<column name="">
            <label>'Overløb, vandmængde'</label>
            <value>overloeb_vandmaengde</value>
        </column>
		<column name="">
            <label>'Vandmængde'</label>
            <value>vandmaengde</value>
        </column>

Men disse oplysninger vises ikke i søgeresultatet. Er det ikke meningen, at de skal vises der ?

Mvh.
Morten Friis

**Comment by klavspc** [comment]
Jeg kan ikke se nogen fejl i det udsnit du vedlægger - vedlæg gerne hele presentation så jeg kan se om der skulle mangle noget andet i den. Den minimale presentation og de muligheder der er beskrives her: https://github.com/Septima/spatialsuite-s4#minimal-presentation-file

Bliver indekset bygget uden fejl?

**Comment by klavspc** [comment]
Og så skal dette tool (https://github.com/Septima/spatialsuite-s4/tree/master/tools#s4-details-s4index-plugin) lægges på i profilen for at detaljer vises for egne data:

`<tool module="s4" name="s4-details-s4index-plugin" />`

**Comment by ikast-mofri** [comment]
Hej

Det var dette tool, der manglede.






Venlig hilsen
Morten Friis
Teamkoordinator
__________________________________


Ikast-Brande Kommune
Planafdelingen
Sjællandsgade 6
7430 Ikast
Tlf.:  +4599604000
Direkte: +4599603320
E-mail: mofri@ikast-brande.dk
Sikker e-mail:  http://www.ikast-brande.dk/personlig
www.ikast-brande.dk<http://www.ikast-brande.dk>

 [cid:MpRELok3kSQgkqpWguwAQlogo_erhvervsklima_2019_mail_jpg]           [cid:SVLV1BjVqUO2bF7zWJAFEwIBK_DDH_logo_2018_jpg]



Ikast-Brande Kommune behandler og gemmer alle dokumenter i alle sager elektronisk.
Hvis du vil se de oplysninger, vi har registreret om dig, så kontakt sagsbehandleren af denne sag, som vil hjælpe dig videre. Du kan også læse mere om dine rettigheder på http://www.datatilsynet.dk<https://www.datatilsynet.dk/forside/>


Fra: Klavs Pihlkjær <notifications@github.com>
Sendt: 13. januar 2020 12:46
Til: Septima/spatialsuite-s4 <spatialsuite-s4@noreply.github.com>
Cc: Morten Friis <mofri@ikast-brande.dk>; Author <author@noreply.github.com>
Emne: Re: [Septima/spatialsuite-s4] Oplysninger i presentation vises ikke i søgeresultatet (#335)


Og så skal dette tool (https://github.com/Septima/spatialsuite-s4/tree/master/tools#s4-details-s4index-plugin<http://linkscan.io/scan/ux/aHR0cHM6Ly9naXRodWIuY29tL1NlcHRpbWEvc3BhdGlhbHN1aXRlLXM0L3RyZWUvbWFzdGVyL3Rvb2xzI3M0LWRldGFpbHMtczRpbmRleC1wbHVnaW4=/6EFF7C12FD7E7F9D1FE33E3BFE7FC7A5FB3C114120FC7AFA9FCCBC544BB75193?c=1>) lægges på i profilen for at detaljer vises for egne data:

<tool module="s4" name="s4-details-s4index-plugin" />
