### ISSUE TITLE
Transparent/fadende søgefelt

### ISSUE THREAD

**Issue by k561mon13** [Septima/spatialsuite-s4#341]
På skærme med lav opløsning fylder søgefeltet  en stor del af kortvinduet. Er der mulighed for at indstille det til at være transparent, fade ud, eller bliver mindre når markøren ikke er i umiddelbar nærhed af søgefeltet?

**Comment by klavspc** [comment]
Det kan vi godt kigge på - det kunne være noget med minimere til søgeikon når s4 ikke har fokus. Jeg vil tro at vi på et to-fire timer kunne finde en løsning og rest-estimat, hvis det kan lade sig gøre.

De, som er med på at medfinansiere denne tilpasning kan enten skrive det på issuet her eller skrive bagom til mig

**Comment by ikast-mofri** [comment]
Vi vil gerne være med, hvis det bliver muligt at vælge det til/fra i de enkelte plugins til SpS-profilerne.
Mvh.
Morten
Ikast-Brande

**Comment by klavspc** [comment]
Der er nu mulighed for at få en knap, der helt skjuler søgefeltet (og viser det igen). Se [beskrivelsen](https://github.com/Septima/spatialsuite-s4/tree/master/tools#s4-show-hide  )

`<tool module="s4" name="s4-show-hide"/>`

og hvis det skal være skjult fra start:
```
<tool module="s4" name="s4-show-hide" panel="middle-right">
  <jsonconfig>
    {"hideFromStart": true}
  </jsonconfig>
</tool>
```
Ikke helt det samme som transparent/fade som i ønsket, men jeg tror det er godt nok. Derfor lukker jeg issuet
