### ISSUE TITLE
Spørgsmål vedr. indeksering i vores PROD miljø (script)

### ISSUE THREAD

**Issue by markusroesgen** [Septima/spatialsuite-s4#342]
Hej

I har på et tidspunkt lavet et script til os, som sørger for indeksering af s4 i vores PROD miljø.
Jeg har en mistanke om at der er sket en fejl.

Scriptets indhold ser sådan ud:
wget -q http://**test**-kort-srv.sonderborg.alssok.net/jsp/modules/s4/buildIndex.jsp

For mig ser det ud som om dette script laver en indeksering i vores TEST miljø.

Skal det laves om?

Hilsen
Markus

**Comment by klavspc** [comment]
Du har ret i at det er test-miljøet, der bliver kaldt i dit eksempel.

Hvis dit produktionssite hedder kort-srv.sonderborg.alssok.net så er det
wget -q http://kort-srv.sonderborg.alssok.net/jsp/modules/s4/buildIndex.jsp, der skal kaldes.

**Comment by markusroesgen** [comment]
Hej Klavs

Vores PROD site hedder kort.sonderborg.alssok.net, er der en grund til at "**srv**" indgår i scriptets link?

Hilsen
Markus

**Comment by klavspc** [comment]
> er der en grund til at "**srv**" indgår i scriptets link?

Ja, det er den url, der tilgår sitet uden at logge ind. (SpS tillader ikke wget mod site, der kræver login).
 _-srv_ er normalt sat op således, at det kun kan kaldes fra serveren selv

**Comment by markusroesgen** [comment]
Tak for hurtig hjælp. Jeg har rettet scriptet.
Rigtig god dag :)
