### ISSUE TITLE
Detaljer: Tinglysninger for adresse fejler

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#352]
Modulet s4-details-adresse-tinglysninger skal tilpasses ny snitflade fra domstolsstyrelsen

**Comment by klavspc** [comment]
Løses i s4 v 2.14

**Comment by ChristianHelringAndersen** [comment]
Hej Klavs, ved du hvornår 2.14 bliver releaset? Har en bruger som venter (u)tålmodigt på issuet bliver løst ;-)

**Comment by klavspc** [comment]
@ChristianHelringAndersen Version 2.13 er på trapperne og jeg har ikke fået den nye dokumentation fra Domstolsstyrelsen endnu. Så der går lige lidt

**Comment by klavspc** [comment]
Tinglysninger kommer ikke tilbage i s4 som vi kendte det. Domstolsstyrlsen service er blevet lagt om til at skulle kaldes med certifikat

Tinglysningsinformation er ved at blive implementeret i serverversionen af Septima Search, dvs umiddelbart kunne ses i OneDoor, samt s3-klienterne i Arcmap og Qgis.

Næstkommende release af s4 vil kunne tilgå Search Server og dermed kunne vise tinglysninger og de andre ting, der ligger i server (primært ejendomssøgninger i Datafordeleren) - kræver Search Server installeret lokalt
