### ISSUE TITLE
Virksomhed mangler ved søgning på virksomhed

### ISSUE THREAD

**Issue by jdgsolrod** [Septima/spatialsuite-s4#356]
Adressen er korrekt officiel adresse i CVR, men S4 finder ikke virksomheden. Jeg kan se i readme til S4, at der søges en cvr-service af Septima. 

Konkret handler det om NETTO i Trylleskov Strand med P-nummer: 1022585629. Den er fra 2017, så helt ny er den ikke.

Jeg har installeret nyeste S4.

**Comment by klavspc** [comment]
Tak - vi vil undersøge, hvad der kan være sket

**Comment by klavspc** [comment]
Så er Netto i Trylleskoven med - vi er i gang med at gøre vore import-scripts mere robuste

**Comment by jdgsolrod** [comment]
Til info, hvis det kan bruges til at forbedre CVR-servicen. Vi har et par virksomheder, som fortsat driller på forskellig vis. Vi spurgte tre større virksomheder, om de ville ændre adresse i CVR, så vi kan søge dem frem med korrekt placering (med S4). En af dem ændrede adresse, men det har ikke hjulpet:

Falck (P-enhed 1003125423) ændrede en adresse fra Engvangen 10 (2680 Solrød Strand) til Engvangen 10B. P-enheden kan fremsøges, men lader ikke til at være geokodet - der sker intet, når det trykkes enter eller enkeltklikkes på resultatet i listen under søgefeltet. Svaret indeholder ingen wkt:
`{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":13.115214,"hits":[{"_index":"cvr","_type":"produktionsenheder","_id":"1003125423","_score":13.115214,"fields":{"telefonnummer_kontaktoplysning":["70102031"],"beliggenhedsadresse_postdistrikt":["Solrød Strand"],"navn_tekst":["FALCKS REDNINGSKORPS A/S"],"pnr":["1003125423"],"beliggenhedsadresse_postnr":["2680"],"beliggenhedsadresse_vejnavn":["Engvangen"],"hovedbranche_tekst":["Brandvæsen"],"virksomhed_cvrnr":["16271241"]}}]}}`

Netto (P-enhed 1003017047) har ikke ændret adresse i CVR fra Solrød Center 84 (2680 Solrød Strand) til Solrød Center 86. Men P-enheden kan fremsøges geokodet på Solrød Center 85, som er en kommunal ejendom med aktivitetscenter :/

Aldi (P-enhed 1003922707) har ikke ændret adresse i CVR fra Parkvej 14 (2680 Solrød Strand) til Jersie Center 2. P-enheden kan fremsøges, men lader ikke til at være geokodet - ligesom med Falck. Tidligere blev p-enheden placeret på Parkvej 11 af S4. Parkvej 11 ligger 250 m fra Aldi og huser en kommunal børnehave.

Det lader til, nogle virksomheder har en gættet geokodning, og andre slet ingen geokodning har.

Når en virksomhed kan fremsøges, men ikke er geokodet, kunne der for brugervenligheden skyld godt komme en besked om, at adressen fra CVR desværre ikke kunne placeres på kortet (e.lign.).

(De to virksomheder, som ikke ændrede adresse i CVR, gjorde det selvfølgelig på deres hjemmesider...)
