### ISSUE TITLE
Fejl i søgning i Spatial Suite data

### ISSUE THREAD

**Issue by jdgsolrod** [Septima/spatialsuite-s4#357]
Vi installerede seneste version af S4 (2.13.1) og kunne derefter ikke længere søge i Spatial Suite data. Jeg har lige opdaget, at der følger en ny version af .jar-filen med (1.2.3). Kopieres version 1.2.3 af .jar-filen til WEB-INF/lib og slettes 1.2.0 (den tidligere), går sitet ned ved config reload, og siger FileNotFoundException, da den ikke længere kan finde .jar-filen i version 1.2.0. I følge dokumentationen, skal .jar-filen i WEB-INF/lib bare erstattes. Skal jeg gøre andet, jeg har overset?

**Comment by klavspc** [comment]
@jdgsolrod : Nej, der burde ikke være mere, der skal gøres. Kan du sende mig et screenshot (eller copy-paste) af hele fejlmeddelelsen? Der plejer vist at være mere info omkring hvilken fil, der ikke kan findes og hvornår den bliver forsøgt åbnet

**Comment by jdgsolrod** [comment]
![image](https://user-images.githubusercontent.com/28621416/120995972-32fe3e00-c786-11eb-99b4-481805b311ec.png)

**Comment by klavspc** [comment]
@jdgsolrod : Bemærk, at ved udskiftning af .jar-fil skal sitet genstartes `stop/start Tomcat` . Kan det være det?

**Comment by jdgsolrod** [comment]
Ok. Det prøver jeg.

**Comment by jdgsolrod** [comment]
Tak. Det kunne godt komme i readme.

**Comment by jdgsolrod** [comment]
![image](https://user-images.githubusercontent.com/28621416/120997600-a2286200-c787-11eb-92bd-2a667ebf48ac.png)
