### ISSUE TITLE
S4 version 2.14.1. s4-cvr-virk-plugin

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#358]
Der zoomes ikke ind til virksomheden i kortet, når jeg bruger s4-cvr-virk-plugin.
E-knappen ved detaljevisning for virksomheder virker ikke.

**Comment by puwose** [comment]
Klavs. Kan vi mødes i TEAMS for en gennemgang af mulighederne i S4?

**Comment by klavspc** [comment]
> Klavs. Kan vi mødes i TEAMS for en gennemgang af mulighederne i S4?

Det kan vi sagtens, men det er nok bedre hvis du kan formulere så mange spørgsmål som muligt, gerne i et eget issue - så kommer svarene flest muligt til gode

**Comment by klavspc** [comment]
> Der zoomes ikke ind til virksomheden i kortet, når jeg bruger s4-cvr-virk-plugin.
> E-knappen ved detaljevisning for virksomheder virker ikke.

Vi er klar over, at visse virksomheder ikke er geokodet korrekt (vi geokoder pba diverse info i cvr)
- Prøv en anden virksomhed og se om der zoomes ind. Hvis der zoomes ind _bør_ E-knappen også virke

Vi arbejder på at forbedre geokodningen af virksomheder. Dette sker centralt i vores index og vil ikke i sig selv give anledning til opdatering af s4

**Comment by puwose** [comment]
Issues til TEAMS-møde

**1) Der zoomes ikke ind til virksomheden i kortet, når jeg bruger s4-cvr-virk-plugin.**
E-knappen ved detaljevisning for virksomheder virker ikke.
Uanset hvilken virksomhed jeg vælger

**2) Matrikelsøgning - detajlevisning**
Vis i Geokoderen åbner samme visning uanset hvilket jordstykke, der vælges
https://www.geokoderen.dk/#centrum=544327.078291814,544327.078291814

**3) Diverse**
Planer: 'regionplan' visning fejler og er udkommenteret
Detaljevisning kræver en separat aftale (éngangs-beløb) - Har vi betalt for det?

**4) Demo af toolet**

**Comment by puwose** [comment]
@klavspc Jeg har booket til til et TEAMS-møde d. 10-09 kl. 10.
Håber du har tid :-)

**Comment by klavspc** [comment]
Dette issue brydes op i enkelt-issues for overskuelighedens skyld

1.  CVR:  https://github.com/Septima/spatialsuite-s4/issues/359
2.  GeoKoder-link: https://github.com/Septima/spatialsuite-s4/issues/360
3.  Samling af spørgsmål:
3.1 Regionplaner: https://github.com/Septima/spatialsuite-s4/issues/361
3.2 Detaljevisning: I tilmeldte jer detaljevisning 2/5-2017 og kan bruge den så meget i vil
3.3 Adressesøgning: Det er meningen og sådan har det været længe
3.4 S4Index: Er indexsearcher [enablet](https://github.com/Septima/spatialsuite-s4#general-options) i dit tool? `indexsearcher: {enabled: true, info: true, print: true, datasources: "*", blankbehavior: "search"}` Har du [indekseret](https://github.com/Septima/spatialsuite-s4#build-the-search-index)?
4. Demo: Hvilket tool ønsker du demonstreret?

**Comment by klavspc** [comment]
> Jeg har booket til til et TEAMS-møde d. 10-09 kl. 10.

Jeg foretrækker at gå længere i dialogen og release en ny version før vi mødes. Med din tilladelse vil jeg sende den nye version til dig @puwose til test inden den kmmer ud til alle

Dette issue lukkes og vi fortsætter på de nyoprettede issues

**Comment by puwose** [comment]
ad 3.4. Nej, indexsearcher var ikke enabled - min egne datasources er med nu.

Nu kom denne fejl i stedet, så jeg har udkommenteret toolet
![s4-details-nearest-plugin](https://user-images.githubusercontent.com/21097639/132816937-c4079516-5e78-42c7-9a9b-977ad198ff2a.JPG)

**Comment by klavspc** [comment]
Godt at høre - den fejl du ser er allerede rettet og med i næste version (I min test havde jeg kun testet _med_ rute uden at tænke på, at der måske slet ikke er et abonnement på vores ruteservice)
