### ISSUE TITLE
Fejl i cvr-søgning meldt af Skanderborg

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#359]
Dette issue repræsenterer punkt 1) i https://github.com/Septima/spatialsuite-s4/issues/358#issuecomment-911553756

**Comment by klavspc** [comment]
Hej @puwose 

Som tidligere nævnt arbejder vi på en forbedret geokodning. Og så vil vi reducere outputtet af cvr-info da outputtet for visse virksomheder bliver ret stort.

Herudover kan jeg desværre ikke genskabe den fejl du ser. Når jeg sætter kommunekoden til 746 i toolet bliver jeg præsenteret for følgende liste af virksomheder:
![image](https://user-images.githubusercontent.com/3736091/132693137-415e8241-e8d3-4539-9504-7be14d8e50ed.png)

Når jeg så vælger AutoCare zoomer kortet:
![image](https://user-images.githubusercontent.com/3736091/132693369-d7c1ffac-c4bf-4384-8815-77a44243dd36.png)

Kan du beskrive, hvad du ser? Gerne med et par billeder

**Comment by puwose** [comment]
Nå, det virker af en eller anden grund?!
Måske fordi jeg efterfølgende har genstartet tomcat'en - kan det være grunden?!

**Comment by klavspc** [comment]
> Nå, det virker af en eller anden grund?!

Godt at høre - vi kigger fortsat på de produktionsenheder, som ikke er blevet georefereret

> Måske fordi jeg efterfølgende har genstartet tomcat'en - kan det være grunden?!

Det tror jeg ikke kan have nogen betydning
