### ISSUE TITLE
Geokoderlink fejl meldt af Skanderborg

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#360]
Der meldes flg fejl:

> Matrikelsøgning - detajlevisning
> Vis i Geokoderen åbner samme visning uanset hvilket jordstykke, der vælges
> https://www.geokoderen.dk/#centrum=544327.078291814,544327.078291814

**Comment by klavspc** [comment]
Vi har fundet en fejl i linket til geokoder, som rettes snarest - den svarer dog ikke helt til den indmeldte

Den fejl vi har fundet skriver samme tal i begge koordinatpositioner, men dog forskellige koordinater for forskellige jordstykker

@puwose: Er koordinaterne ikke forskellige for forskellige jordstykker hos dig?

**Comment by puwose** [comment]
@klavspc Jo, de er forskellige for forskellige jordstykker - sorry!

**Comment by klavspc** [comment]
Rettes til v 2.14.2

**Comment by klavspc** [comment]
Det viser sig, at der er fejl i GeoKoderen så selvom den kaldes med gyldigt punkt så vises det korrekte område ikke

Issuet er oprettet hos GeoKoderen (issue 2113) og der kan ikke gøres yderligere i s4 - link vil virke når geokoderen er fikset
