### ISSUE TITLE
Fejl i regionplaner meldt af Skanderborg

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#361]
Fra https://github.com/Septima/spatialsuite-s4/issues/358#issuecomment-911553756:

> Planer: 'regionplan' visning fejler og er udkommenteret

**Comment by klavspc** [comment]
@puwose: Hvilken fejl ser du? Hvis det er den gule geometri-fejl i SpS så må vi tale med Sweco
Bemærk, at regionplanen kan klikkes og vises uagtet meddelelsen fra SpS:
![image](https://user-images.githubusercontent.com/3736091/132698059-c849903b-ceaf-4525-a96f-1d639077d7a6.png)

OBS: Den grimme tekst, DetailsHandler_xxx, i detaljevisningen er fundet og vil blive vist korrekt

**Comment by puwose** [comment]
![regionplan_error_s4](https://user-images.githubusercontent.com/21097639/132814360-bdaa068f-ff12-433f-830e-f03875fa3ca5.png)

**Comment by klavspc** [comment]
Ja, det er præcis den gule meddelelse jeg skal tale med Sweco om - bemærk, at knappen kan klikkes og så vises planen korrekt
