### ISSUE TITLE
S4 - historik

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#364]
Hvordan gemmes historikken i S4?
Pr. session, pr. dag, eller.....?

**Comment by puwose** [comment]
Der står "Remember history between sessions", så det er vel så længe SpS holder sessionen.
Jeg tror nok, at vi sat det op så en session holder en hel dag. (Sweco tjekker lige på på det)
Udviklingsønske kunne være at slette hele historikken eller en eller flere søgninger

**Comment by klavspc** [comment]
Historikken gemmer valgte resultater, ikke søgninger

Der er ved `persist: true` ikke tale om SpS's session-begreb, men derimod helt generelt user session

Fra [vejledningen](https://github.com/Septima/spatialsuite-s4#general-options):
```
//History
// Promote: show history icon in search input
// persist: Remember history between sessions
historysearcher: {enabled: false, promote: true, persist: true},
```
_promote_ betyder, at historik-ikonet kommer op ved siden af søgefeltet
_persist_ medfører, at valgte resultater gemmes i en liste i en cookie lokalt - serveren er slet ikke indblandet
- hvis persist er false slettes historikken når man lukker browseren

Historikfunktionen er sponseret af Albertslund, tak for det. Sletning af hele historikken vil kunne laves på tre timer. Sletning af enkelt-resultater skal lige undersøges

**Comment by puwose** [comment]
Vi har flg parametre

`historysearcher: {enabled: true, promote: true, persist: true},`

Hvornår bliver historikken så slettet? Når man genstarter PC'en?

**Comment by klavspc** [comment]
Slettes i princippet aldrig. Jeg har et par opdateringer til næste version mht levetid og antal. Så hvis du synes, at den endnu er lidt umoden så vent med at bruge den

**Comment by puwose** [comment]
Nej, det er fint - tak for svaret
