### ISSUE TITLE
Ruteberegner som værktøj - kan ikke udfylde med adresse

### ISSUE THREAD

**Issue by birgithepaasch** [Septima/spatialsuite-s4#369]
Ruteberegner som selvstændigt værktøj tillader ikke, at der indtastes en adresse. Der kan dog klikkes i kortet, hvorefter værktøjet finder adressen

**Comment by klavspc** [comment]
Den nye version 4.0.4 af rutemodulet løser problemet . Kan downloades fra https://septima.dk/spatialsuite-route (Kræver afttale)
