### ISSUE TITLE
Link til planer i planinfo detaljevisning...

### ISSUE THREAD

**Issue by mortentj** [Septima/spatialsuite-s4#370]
Hej Klavs

Er det muligt, at få doklink m. i detaljevisningen på planinfo i s4? Det vil være super brugbart.
Pft. 

Morten (Roskilde Kommune)

**Comment by klavspc** [comment]
Hej Morten,

Du skal bruge toolet [s4-plan-plugin](https://github.com/Septima/spatialsuite-s4/tree/master/tools#s4-plan-plugin) til at vise doklinks

Grunden til at det ligger i et separat tool er at alle skal have adgang til doklinks (ovenstående tool), men ikke alle abonnerer på detaljevisningen
