### ISSUE TITLE
S4 fejler hvis man bruger IE

### ISSUE THREAD

**Issue by birgithepaasch** [Septima/spatialsuite-s4#371]
For at kunne stedfæste til vores ESDH system, er vi nød til at køre ESDH SpatialSuite profilen  i IE.
Vi oplever desværre problemer med S4, hvis man åbner SpatialSuite i IE. Vi får fejlbeskeden s4-xxxx tool is broken.

**Comment by klavspc** [comment]
Hvad er den første fejl du ser i konsollen (F12)? Den første fejl du ser er den vigtige - de følgende fejl (s4-xxxx tool is broken) er følgefejl af at s4 har fejlet i opstart

**Comment by klavspc** [comment]
Blev løst med special-tool, som fungerede i ie

Version 2.15.5 af s4 (seneste) bør klare sig betydeligt bedre i IE end forrige version
