### ISSUE TITLE
BBR meddelelse samt Vis i Ret BBR fejler

### ISSUE THREAD

**Issue by KKansimm** [Septima/spatialsuite-s4#372]
Ved adresse opslag virker disse to funktioner ikke længere. Fejlen er først begyndt i denne uge.

- [X] BBR meddelelse fejlen viser 500 Internal Server Error
- [ ] Vis i Ret BBR fejlen viserHTTP Status 400 – Bad Request

Københavns kommune benytter version 2.14.4

**Comment by klavspc** [comment]
BBR meddelelsen vises korrekt i v. 2.15.5 af s4. Men idet der er tale om en fejlen `500 Internal Server Error` mon ikke det er BBR-meddelelsen, der har været nede?

Kan desværre ikke selv teste RetBBR, idet jeg ikke har et gyldigt log-in. Url'en jeg forsøger at åbne er `https://ret2.bbr.dk/oversigt/0/7/0/${komnr}|${esrnr}`. Måske nogen har et bedre bud på et link til retBBR?

**Comment by klavspc** [comment]
> Kan desværre ikke selv teste RetBBR, idet jeg ikke har et gyldigt log-in. Url'en jeg forsøger at åbne er `https://ret2.bbr.dk/oversigt/0/7/0/${komnr}|${esrnr}`. Måske nogen har et bedre bud på et link til retBBR?

@KKansimm?

**Comment by KKansimm** [comment]
Det hele spiller nu. Måske har der været intern firewall issues eller lignende som nu er på plads??

**Comment by klavspc** [comment]
> Måske har der været intern firewall issues eller lignende som nu er på plads??

Det kan være - jeg lukker issue. Genåbn endelig eller lav nyt, hvis der bliver problemer igen
