### ISSUE TITLE
Modstridende default i s4?

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/spatialsuite-s4#373]
Der er tilsyneladende rod i default-placering af s4 i de forskellige plugins.

I s4-plugin-all er angivet _'default': In panel-brand if possible, else in panel-middle (menu linie, right justified)_, mens der i s4-plugin-onedoor står _'default': same as map-top-right_.

Det er muligt, at det kun er i beskrivelsen, at der er modstrid, men vi kan konstatere, at vores søgefelt flyttede fra panel-middle til map-top-right ved installation af den seneste version.

Vh Lars

**Comment by klavspc** [comment]
> I s4-plugin-all er angivet 'default': In panel-brand if possible, else in panel-middle (menu linie, right justified), mens der i s4-plugin-onedoor står 'default': same as map-top-right.

Observationen er korrekt, men det er ikke `s4-plugin-all`, som skal danne udgangspunkt for custom tilretninger. Det skal `s4-plugin-dk-all` derimod (Se [vejledning](https://github.com/Septima/spatialsuite-s4/tree/2.14.5/tools#s4-plugin-dk-all)). I dét tool er default angivet korrekt

Jeg retter selvfølgelig `s4-plugin-all` så svenskerne ikke bliver overraskede
