### ISSUE TITLE
Forældde links i OneDoor version

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/spatialsuite-s4#374]
Links til SDFEkort og kort.plandata.dk i OneDoor-versionen af s4 peger på temaer fra kortforsyningen, der ikke længere er i drift, og hvor de tilsvarende i dag skal hentes fra DAF. Det gælder bl.a. skærmkort og matrikel.

Vh Lars

**Comment by klavspc** [comment]
OneDoor-toolet til s4 serverer det som OneDoor server returnerer. Så det er OneDoor, der skal tilpasses

Når det er sagt så er jeg ikke sikker på hvad du mener med at et link, som er en url, peger på et tema. Det skal du nok præcisere når du melder fejlen til OneDoor

**Comment by Ellebjerg** [comment]
Jeg skriver til Martin om OneDoor.

Eksempel på URL, der henviser til temaer i SpS: https://sdfekort.dk/spatialmap?wkt=POINT(718909.36%206171512.34)&selectorgroups=admgraens+matrikelkort&layers=theme-gst-dtkskaerm_daempet+theme-gst-matrikelkort-roed+theme-gst-forvaltning-husnummer&label=Hvidovrevej%20306,%202650%20Hvidovre&labelPos=POINT(718909.36%206171512.34)

**Comment by klavspc** [comment]
Genåbnet - skal rettes i Septima Search

**Comment by klavspc** [comment]
- [ ] kort.plandata.dk
- [ ] SDFEkort

**Comment by klavspc** [comment]
Releases i s4 v. 2.14.7
