### ISSUE TITLE
Størrelse og placering af S4-søgefelt

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/spatialsuite-s4#376]
Vi har aktiveret visning af søgehistorik i S4. Desværre er det ikon, som kommer på, så stort, at søgefeltet ikke længere kan være i værktøjsbjælken. Vi har derfor flyttet det til topbjælken, men her placeres søgefeltet desværre så tilpas langt nede i bjælken, at bunden af feltet går ned under bjælken (se vedhæftede billede).

Det vil være hensigtsmæssigt, at ikonet gøres mindre, så søgefeltet kan være i værktøjsbjælken. Derved vil det formentlig også passe med placeringen i topbjælken.

Vh Lars

![S4 søgefelt](https://user-images.githubusercontent.com/10741426/152768498-3c6908c3-891c-4603-87a4-d526e6744816.png)

**Comment by klavspc** [comment]
Dækket af #377 - løses med snarlig release

**Comment by klavspc** [comment]
Løst i s4 v 2.14.6 (Downlaod: Se https://github.com/Septima/spatialsuite-s4#basic-installation-and-test)
