### ISSUE TITLE
Skråfotos kan vises i større eller fuld størrelse format

### ISSUE THREAD

**Issue by MichaelDavidKnudsen** [Septima/spatialsuite-s4#380]
De fire fundne skråfotos i Septima Search i Spatial Suite er meget små, og brugerne bør have mulighed for at se dem i større format og allerbedst i fuld størrelse. Hvis ikke muligt kunne der linkes til sdfe'a skråfoto-løsning fra skråfotos-fanen.

**Comment by klavspc** [comment]
s4 har ikke noget tool til at vise skraafotos - kun til at linke til skraafotos hos sdfe

Ad link til sdfe:
Issuet oprettes i OneDoor da det er en konfiguration hvorvidt man vil have link til sdfe på samme faneblad som skråfotos

Ad størrelse:
ja, s4 kan ikke zoome i billeder i dag - det er noget vi undersøger - vi har ikke nogen plan for hvornår der kommer noget

**Comment by klavspc** [comment]
> Issuet oprettes i OneDoor da det er en konfiguration hvorvidt man vil have link til sdfe på samme faneblad som skråfotos

Se https://github.com/Septima/OneDoor/issues/24
