### ISSUE TITLE
Søgning på datasource

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#386]
Vi har et ønske om at kunne søge på datasource, og få vist tilhørende themes.
![ds_s4Search](https://user-images.githubusercontent.com/21097639/169974996-39aec0c2-e986-4167-8294-83edd7eb911b.JPG)

**Comment by klavspc** [comment]
Der kan ikke søges på datasources, der kan derimod søges på temaer og/eller egne features

- Hvis du vil søge på temaer skal du enable temasøgning i dit custom tool. Fra [vejledningen](dafEventMessages):

```
//Themes in profile
themesearcher: {enabled: true},
```

- Du kan også vælge at indeksere din datasource med spildevandsrensninger  (Hvis der ellers er nogen felter i den som det giver mening at søge på) Vejledning [her](https://github.com/Septima/spatialsuite-s4#-search-spatial-suite-data). Hvis du så bruger toolet `<tool dir="custom" name="s4-details-themesForIndex-plugin" />` vil du for forekomster af spildevandsrensninger få mulighed for at tænde de temaer, der baserer sig på samme datasource

Jeg håber, at jeg har forstået og besvaret ønsket
