### ISSUE TITLE
Søgning i vejledninger med s4

### ISSUE THREAD

**Issue by mortentj** [Septima/spatialsuite-s4#387]
Hej 

I Roskilde Kommune har vi et (begyndende) site med små videovejledninger til SPS. Det ville være fint, hvis man kunne fremsøge disse via s4. Tanken er, at vi har en lokal tabel i vores database, med nødvendige info om vejledninger (fx en url, https://filer.roskilde.local/vejledninger/Webgis_vejledninger.html#Tilføj-temeaer-fra-kortskabet) - dog uden geometri. I modsætning til vores lokale i s4 (som jo har geometri!), så har vi ikke behov for "HGH", print m.m., da brugere blot skal have mulighed for at navigere til det sted på vores vejledningssite, hvor video ligger (se ovenstående url), så linket skal blot åbnes direkte i et nyt browser vindue.

Vedlagt er to skærmbilleder (mockups) til illustration af vores ønske.

![s4_resultatDialog](https://user-images.githubusercontent.com/31916013/182816107-4279e2b5-ca08-49da-841e-9c8902f2d8a4.png)
![s4_soegedialog](https://user-images.githubusercontent.com/31916013/182816109-2c20128c-17d2-4740-a5d5-54c888644a0f.png)

Kan det lade sig gøre og hvad vil det koste? Gode ideer og alternative løsningsmuligheder er meget velkomne:-)

På forhånd tak.
Mvh. Morten, Roskilde Kommune

**Comment by klavspc** [comment]
Som jeg forstår opgaven så kan det laves præcis som du foreslår i en tabel i db. Herpå en datasource og en presentation som bruges til indeksering på samme måde som jeres lokale data

Hvis der ikke er geometri på et resultat så vises der ikke hgh eller print

Der har tidligere, som forsøg i s4, været et guide plugin, som er tæt på det beskrevne. Men med de muligheder der er for egen indeksering mener jeg ikke at det længere er relevant

Lad mig vide, hvis der er noget jeg skal gøre eller hvis i ikke kan få det til at fungere som ønsket

**Comment by klavspc** [comment]
Dokumentation af hvordan man skriver presentation til s4 med links og hvordan man bestemmer en streng, _searchstring_, der også søges i (Der søges altid i titel):
https://github.com/Septima/spatialsuite-s4#presentations

**Comment by mortentj** [comment]
Tak for svaret - det lyder godt. Vi prøver at sætte det op.
Vh. Morten

**Comment by mortentj** [comment]
Hej Klavs
Det er muligt at sætte en datasource (uden geometri) til vejledninger op og indeksere den via s4. Jeg bøvler dog med, at det ikke er muligt at klikke og åbne url'en direkte i søgeresultatet (se skærmklip), da linket er sat til column format="heading". Som det er nu, skal der klikkes en ekstra gang for at få vist attributterne, hvor man så kan definere et link som column format = "hyperlink"

![image](https://github.com/Septima/spatialsuite-s4/assets/31916013/a8957426-4bed-4075-98eb-7424f792ad8f)

Er der en workaround, så det er muligt at åbne links i søgeresultat direkte?

Pft. 
Mvh. Morten (Roskilde Kommune)

**Comment by klavspc** [comment]
> Som det er nu, skal der klikkes en ekstra gang for at få vist attributterne, hvor man så kan definere et link som column format = "hyperlink"

Ja, det er den metode, som er ligetil

-- Avanceret ---
Du kan lave dit eget tool, som lytter til hvad, der der bliver valgt i s4

Du kan lade dig inspirere af toolet s4ApiDemo i s4's tool-folder. Det er denne kode, som lytter og kan gøre et-eller-andet.
```javascript
    	window["_s4OnSelect"] = window["_s4OnSelect"] || [];
       	var _s4OnSelect = window["_s4OnSelect"];    // Brug eksisterende array eller skab en ny
       	_s4OnSelect.push(function(result){ 
       		if (result.searcher.source == "Monumenter"){ 
       			alert("Monument " + result.title + " valgt"); 
       		} 
		return true; 
       	}); 
```
I eksemplet laves der en _alert()_, du vil gerne lave en window.open med target "_blank"

**Comment by mortentj** [comment]
Tak, den mulighed vil jeg kigge nærmere på.
Vh. Morten
