### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by rastermanden** [Septima/spatialsuite-s4#395]
Mod onedoor, men værdien præsenteres fint i onedoor web
![Screenshot from 2023-01-16 14-23-00](https://user-images.githubusercontent.com/1125134/212693240-f226481f-bc8a-4cbf-8dc9-b6c66778f9cd.png)

**Comment by klavspc** [comment]
@rastermanden Hvilken OneDoor (site og configuration søger du mod)?

**Comment by rastermanden** [comment]
standard på en lokal installation i Syddjurs

**Comment by klavspc** [comment]
Kan du skaffe konfigurationen til mig?

**Comment by rastermanden** [comment]
Du kan bare bruge https://onedoor.test.septima.dk/#/septima/standard
