### ISSUE TITLE
Kommuneplan Rammer

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#399]
Vil S4 kunne søge i kp-rammer, fx

https://skanderborg.viewer.dkplan.niras.dk/plan/34#/Kommuneplan_Planramme?id=1856&baseId=8873&parentId=9385

**Comment by klavspc** [comment]
@puwose : Var ovenstående svar tilfredsstillende?

Jeg lukker og du må genåbne, hvis der er noget vi bør gøre anderledes
