### ISSUE TITLE
Fejl i matrikelsøgningen i S4

### ISSUE THREAD

**Issue by petergot** [Septima/spatialsuite-s4#400]
Vi får en forkert visning i s4 hvis vi slår matr nr 190 op for Vejlby, Ellevang jf nedenfor.

Matr nr 190 har ikke mere den udstrækning som er markeret med rødt men en del af denne er nu under matr nr 317 som ikke kan fremsøges i s4.
Hvad skyldes det?

![image](https://user-images.githubusercontent.com/30045662/225920534-eededc95-0f02-43d3-ba90-adc94fb44137.png)

**Comment by petergot** [comment]
Kan problemet skyldes geosearch og bør der ikke snart skiftes til gsearch.

**Comment by petergot** [comment]
Det er faktisk lidt kritisk da byggesagsbehandlerne benytter S4 til konfliktsøgning og dermed nogle gange får forkerte søgepolygoner

**Comment by petergot** [comment]
Er der testet på de specifikke jordstykker via gsearch? Og er konklusionen at vi IKKE kan benytte matrikelsøgningen i s4 til konfliktsøgning pt. uden at kunne risikere fejl.  Og hvornår implementeres gsearch og løser det problemet.

**Comment by klavspc** [comment]
Lukkes. Med Gsearch vil korrekt matrikelnummer-udstrækning blive vist
