### ISSUE TITLE
Kan ikke søge i temaer

### ISSUE THREAD

**Issue by dikkri** [Septima/spatialsuite-s4#401]
Hej
Vi kan ikke søge i temaer efter den nye opdatering.

selv om temasøgeren er sat til true - er der andet der skal ændres? - den gamle version kørte fint med temasøgning
 //Themes in profile
 themesearcher: {enabled: true},

Vh Kamilla

**Comment by klavspc** [comment]
Det lyder ikke godt
- Hvilken version af SpS kører du?
- Hvilken browser?
- Hvilken temavælger?
- Har du mulighed for at åbne konsollen og kopiere en fejlmeddelelse til mig?

**Comment by dikkri** [comment]
Hej

Fejlen ligger vedr. temavælger
– når jeg skifter til themeselector så virker det – vi bruger themeselector-mini og det vil vi gerne fortsætte med😊
Er det S4 der skal rettes så?


Vi har opgraderet vores sandkasse til 4.4.0 – det er der jeg vil lægge den nye S4.
Browser: Edge
Er komme ikke nogle fejl i konsollen

Venlig hilsen
Kamilla Kristensen
GIS-medarbejder

***@***.***
Haderslev Kommune
Teknik og Klima
Christian X's Vej 39 - 6100  Haderslev
Direkte telefon: 24991732
***@***.******@***.***>
www.haderslev.dk

Haderslev Kommune behandler og gemmer alle relevante dokumenter i alle sager elektronisk.
Hvis du vil se de oplysninger, vi har registreret om dig, kan du kontakte afsenderen af denne mail, som vil hjælpe dig videre.
Du kan læse mere om dine rettigheder på https://www.haderslev.dk/databeskyttelse
Fra: Klavs Pihlkjær ***@***.***>
Sendt: 20. marts 2023 10:35
Til: Septima/spatialsuite-s4 ***@***.***>
Cc: Kamilla Kristensen ***@***.***>; Author ***@***.***>
Emne: Re: [Septima/spatialsuite-s4] Kan ikke søge i temaer (Issue #401)


Det lyder ikke godt

  *   Hvilken version af SpS kører du?
  *   Hvilken browser?
  *   Hvilken temavælger?
  *   Har du mulighed for at åbne konsollen og kopiere en fejlmeddelelse til mig?

**Comment by klavspc** [comment]
Tak for svar

Hvis du altid har brugt themeselector-mini og temasøgning har virket så bør det være en mindre rettelse

Har themeselector-mini virket i den forrige vesion af s4?

**Comment by dikkri** [comment]
Hej

Der er ikke røde fejl - der er disse:

***@***.***

Venlig hilsen
Kamilla Kristensen
GIS-medarbejder

***@***.***
Haderslev Kommune
Teknik og Klima
Christian X's Vej 39 - 6100  Haderslev
Direkte telefon: 24991732
***@***.******@***.***>
www.haderslev.dk

Haderslev Kommune behandler og gemmer alle relevante dokumenter i alle sager elektronisk.
Hvis du vil se de oplysninger, vi har registreret om dig, kan du kontakte afsenderen af denne mail, som vil hjælpe dig videre.
Du kan læse mere om dine rettigheder på https://www.haderslev.dk/databeskyttelse
Fra: Klavs Pihlkjær ***@***.***>
Sendt: 30. marts 2023 13:14
Til: Septima/spatialsuite-s4 ***@***.***>
Cc: Kamilla Kristensen ***@***.***>; Mention ***@***.***>
Emne: Re: [Septima/spatialsuite-s4] Kan ikke søge i temaer (Issue #401)


@dikkri<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdikkri&data=05%7C01%7Ckkri%40haderslev.dk%7C9ba47b982dcc4ee54cc208db310fd783%7C8e54772249734f1db42fd83ff3374932%7C0%7C0%7C638157716324619931%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4NW5oHUpJDESt2beGhyeRquNWwvZbdRSlTZ6Ur%2BawmE%3D&reserved=0> : Har du mulighed for at se om der vises nogle fejl i konsollen (F12)?

Fejl vises med rødt og du må gerne sende et screenshot af, hvad du ser

-

**Comment by klavspc** [comment]
> Hej Der er ikke røde fejl - der er disse: 

Ja, det var ikke meget at gå efter

Jeg kan desværre ikke se fejlen hos mig - er det muligt for dig at sende det udsnit af tools i din profil, hvor du inkluderer themeselector? Gerne alle tools. der har noget med themeselector at gøre
 
  

>//Themes in profile
>themesearcher: {enabled: true},

Og du er helt sikker på at du bruger det tool, hvor temasæøgning er enabled?

**Comment by dikkri** [comment]
Der står dette i toolet
 //Themes in profile
 themesearcher: {enabled: true},
og det er det rigtige tool  - for hvis jeg fx fjerner søgning i datasource så forsvinder den fra søgningen.
Når jeg udskifter themeselector-mini med themeselector så kan jeg godt søge i temaer.
Her vores tools:
[common-tools - Kopi.txt](https://github.com/Septima/spatialsuite-s4/files/11121199/common-tools.-.Kopi.txt)

**Comment by flemmingrasbak** [comment]
Vi har samme problem med at S4 ikke længere søger i temaer. Vi bruger:

- S4: 2.15.6.patch1
- SpS: 4.4.0
- tool name="themeselector-simple"

Findes der er løsning på problemet?

Mvh. Flemming

**Comment by klavspc** [comment]
@flemmingrasbak / @dikkri
Jeg kan som sagt ikke genskabe problemet hos mig og bliver nødt til at få adgang via rdp til een af jeres maskiner for at se, hvad der sker. Det kan også være Teamviewer selvfølgelig. Hvis det bliver Teamviewer vil jeg helst lige sidde med sessionen for mig selv og rode lidt - så måske på en maskine, som ikke er jeres arbejds-pc

Næstbedste er hvis i lægger temasøging på et borgersite (måske i en egen profil til mig) -  så kan jeg fejlsøge, men dog ikke rette

**Comment by klavspc** [comment]
> Jeg har flyttet lidt rundt på rækkefølgen af tools i profilen, så themeselector-simpel står før s4-tools'ne, og nu virker temasøgningen igen :-)

Godt fundet, Flemming

@dikkri : Kan du prøve dette?

**Comment by klavspc** [comment]
Godt at høre, Kamilla
