### ISSUE TITLE
Kunne man link til https://nyt.ois.dk/ i stedet for den gamle? 

### ISSUE THREAD

**Issue by KKansimm** [Septima/spatialsuite-s4#402]
Ved adresse eller matrikel søgning vises en masse offentlige links. Den ene er https://www.ois.dk
For bedre at kunne følge med med det nye ejendomsnummer begreb (BFEnr), har vi et ønske om at der linkes til https://nyt.ois.dk/  
i stedet.

**Comment by klavspc** [comment]
Tak for info. Vi ser på det til den kommende version

**Comment by klavspc** [comment]
Fikset - kommer i næste version
