### ISSUE TITLE
Opslag på Boligejer.dk giver fejl

### ISSUE THREAD

**Issue by KKansimm** [Septima/spatialsuite-s4#403]
Ved adresse eller matrikelsøgning er der en kobling til boligejer.dk. 
Der kommer desværre følgende fejl "-1 - Der skal vælges kommune og ejendomsnummer. - 500"
Kan I lige se på det?

**Comment by klavspc** [comment]
Tak skal du ha'. Det ser vi på til den kommende version

**Comment by klavspc** [comment]
Ja, boligejer.dk har ændret deres url - simpel ændring. Fikses i næste version af s4
