### ISSUE TITLE
Ensartet adresse og matrikel muligheder

### ISSUE THREAD

**Issue by KKansimm** [Septima/spatialsuite-s4#404]
Ved søgningen via adresse får man adgang til yderligere funktioner som Planer, Administrativ inddeling og nærmeste. 
Skulle det ikke være mening at tilsvarende muligheder var tilgængeligt ved matrikel søgning?

**Comment by klavspc** [comment]
Jo, det lyder rigtigt - jeg ser på det til den kommende version af s4

**Comment by klavspc** [comment]
**Planer**:

S4 er udvidet med et nyt tool. Kommer i næste version:

```
<!--Dette tool er deprecated-->
<tool module="s4" name="s4-details-dawa-planer-plugin" />
<!--erstattet af dette-->
<tool module="s4" name="s4-details-planer-plugin"/>
```

**_Valgfrit_**: Man kan angive hvornår toolet skal være aktivt. Her vist med default-værdierne:

```
<tool module="s4" name="s4-details-planer-plugin">
  <jsonconfig>
    {"targets": ["husnummer", "matrikelnummer"]}
  </jsonconfig>
</tool>

```

**Comment by klavspc** [comment]
**Nærmeste:**

Toolet `s4-details-nearest-plugin` er opdateret så det også viser nærmeste for matrikelnumre

**_Valgfrit_**: Man kan angive hvornår toolet skal være aktivt og hvilke datasources, der skal søges i. Her vist med default-værdierne:

```
 <tool module="s4" name="s4-details-nearest-plugin">
     <jsonconfig>
        { "targets": ["husnummer", "matrikelnummer", "virksomhed"],
          "datasources": "*"}
     </jsonconfig>
 </tool>

```
