### ISSUE TITLE
Fejl ved søgning i Plandata

### ISSUE THREAD

**Issue by KKansimm** [Septima/spatialsuite-s4#405]
Vi oplever manglende planer ved søgning efter vedtaget lokalplaner fra Plandata.
I København findes der 3 tillægsplaner til "Enghave Brygge", og kun de første to kommer frem.
Vi benytter S4 version 2.15.4

**Comment by klavspc** [comment]
Ja, der mangler planer i den søgning vi har lige nu idet den bygger på et indeks somvi ikke opdaterer længere

Vi er ved at omlægge til et indeks, hvor vi henter planer ned hver nat - Mere om det i et snarligt nyhedsbrev
