### ISSUE TITLE
Stedfæstelser (SBSYS)

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#406]
Jeg kan ikke fremsøge vedlagte stedfæstelse via S4.
Hvad kan det skyldes?

![S4_SBSYS](https://user-images.githubusercontent.com/21097639/227884794-23522f19-e238-40b0-b01c-560e9ebcba16.PNG)

**Comment by klavspc** [comment]
Jeg kender desværre ikke toolet "Vis information" særlig godt, men véd selvfølgelig, hvad s4 gør

Første skridt vil være om det er korrekte matrikelnummer som vises i kortet

Dernæst: Er det markerede matrikelnummer et "objekt", der _kan_ søges info på? Når et resultat bliver valgt i s4 så bliver det vist i kortet ved hjælpe af den indbyggede funktion _setMarkingGeometry_. Om det gør objektet klikbart må du vende med Sweco. Jeg hører gerne om der er noget vi kan gøre anderledes

Den fulde linie når et resultat vælges er
`mc.setMarkingGeometry(wkt, true, false, _s4Params.view.zoomBuffer);`

**Comment by puwose** [comment]
Min fejl.
Jeg brugte en forkert datasource i config.xml.
Det virker nu

![esdh2](https://user-images.githubusercontent.com/21097639/229053747-1fb92f15-ff6d-4e56-8ac6-346b63258672.PNG)

**Comment by klavspc** [comment]
> Det virker nu

Godt at høre
