### ISSUE TITLE
Omlægge GeoSearch til GSearch

### ISSUE THREAD

**Issue by klavspc** [Septima/spatialsuite-s4#407]
Septima Search omlægges til at anvende [GSearch](https://dataforsyningen.dk/news/4861), som erstatter GeoSearch

For s4 _kan_ det betyde, at konfigurationen må opdateres - mere om det i næste nyhedsbrev

**Comment by petergot** [comment]
Jeg kan ikke tilgå 663 med det angivne link

**Comment by klavspc** [comment]
> Jeg kan ikke tilgå 663 med det angivne link

Undskyld det er et internt repo. Her er teksten:

Septima Search omlægges til at anvende [GSearch](https://dataforsyningen.dk/news/4861), som erstatter GeoSearch

Det bliver desværre ikke muligt at give præcis samme funktionalitet
- ikke alle resourcer tager kommunenummer som parameter - det bliver for eksempel ikke muligt at afgrænse matrikelsøgningen til kommune
- Der bliver ikke længere søgt samlet, men derimod som et antal enkeltkald for hver resource - det _kan_ komme til at betyde noget for hvorledes resultater vises i resultat-listen
- [Endnu uforudsete forskelle]

**Comment by Ellebjerg** [comment]
Det med manglende kommunefilterering på matrikelsøgning lyder mildt sagt grimt. 
Kan der laves et begrænsning med fx bbox, så denne søgning ikke er helt ubrugelig?

**Comment by klavspc** [comment]
> Det med manglende kommunefilterering på matrikelsøgning lyder mildt sagt grimt.

Det synes jeg også

Ja, der er nogle muligheder - resultatet er dog at vi sammen med de øvrige ændringer faktisk skal kode en eller flere helt ny(e) searchere op fra bunden

En sådan ny searcher _kunne_ basere sig på gsearch, men den kunne næsten endnu bedre bruge septimas data-api, som udstiller offentlige data - vi er ved at vurdere omfanget af sådan en ny searcher og forventer at komme med et udspil til alle search-kunder om hvordan den kan finansieres

**Comment by klavspc** [comment]
**Opdatering**: Vi er godt i gang med omlægningen til gsearch, men der er endnu et stykke vej. Den nuværende version af gsearch understøtter ikke helt de muligheder som vi er vant til

Vi er i dialog med sdfi både direkte og igennem et antal issues:

https://github.com/SDFIdk/gsearch/issues/183
https://github.com/SDFIdk/gsearch/issues/185
https://github.com/SDFIdk/gsearch/issues/186
https://github.com/SDFIdk/gsearch/issues/187
https://github.com/SDFIdk/gsearch/issues/188
https://github.com/SDFIdk/gsearch/issues/189

Det er endnu for tidligt at forudsige hvornår vi har omlagt, men vi håber, at det sker i god tid før GeoSearch nedlægges så vi kan få en rolig overgang

**Comment by klavspc** [comment]
**Opdatering**: SDFI har lagt vore ønsker ind i deres udviklingsplan, https://github.com/SDFIdk/gsearch/projects/5, til release i maj

Der kommer derfor _ikke_ nogen gsearch med i førstkommende release af s4. Et bud herfra er at gsearch er inkluderet i en s4-release slut maj/begyndelsen af juni
