### ISSUE TITLE
Plansearcher - der kommer kun vedtagne lokalplaner med

### ISSUE THREAD

**Issue by ikast-mofri** [Septima/spatialsuite-s4#408]
Selvom jeg har sat følgende ind i vores plugin, så søges der kun i vedtagne lokalplaner - og alle kommer for øvrigt ikke med (se særskilt issue):

//Plansystem

//Full set of targets is ['vedtagetlokalplan', 'kommuneplanramme', 'kommuneplantillaeg', 'lokalplanforslag', 'regionplan', 'byggefelt', 'delområde', 'vedtagetkloakopland', 'mulighedforudtraedenkloakopland', 'zonestatus']

plansearcher: {enabled: true, info: true, print: true, targets: ['vedtagetlokalplan', 'kommuneplanramme', 'kommuneplantillaeg', 'lokalplanforslag', 'regionplan', 'byggefelt', 'delområde', 'vedtagetkloakopland', 'mulighedforudtraedenkloakopland', 'zonestatus'], skraafoto: true},

Mvh.
Morten

**Comment by klavspc** [comment]
Ja, der fritekst-søges kun i vedtagne lokalplaner. De øvrige plantyper ses i
- detaljer for plan (`s4-details-planinfo-plugin`), hvor man kan se byggefelter og delområder for en lokalplan
- i `s4-details-dawa-planer-plugin`, som viser planer for en adresse

Og så kan man søge på planid i søgefeltet og hvis der et match med en plantype så vises denne

Kun plantyper nævnt i targets i toolet medtages i ovenstående
