### ISSUE TITLE
E-knap-opslag fra matrikel giver "forkert resultat"

### ISSUE THREAD

**Issue by ikast-mofri** [Septima/spatialsuite-s4#409]
Hvis man bruger E-knap-opslaget fra en fremsøgt matrikel, f.eks. på matrikel 25a Brande By, Brande, så bliver resultatet i E-knap-vinduet rodet og forkert. Der burde kun være oplysninger om den markerede ejendom (den som pilen peger på i vedhæftningen), men der er oplysninger om en hel del ejendomme. Derudover er ejendomsnummeret øverst i vinduet det forkerte. Det burde se ud som på side to i vedhæftningen.
Mon ikke der er fordi, det er matrikel-geometrien, der bruges som opslag, mens E-knappen egentlig er lavet til opslag ud fra et punkt?
Mvh.
Morten
[2 _ E-knap-for mange matrikler.docx](https://github.com/Septima/spatialsuite-s4/files/11089797/2._.E-knap-for.mange.matrikler.docx)

**Comment by klavspc** [comment]
Jeg vil ændre funktionen så den giver et punkt videre til E-knappen istedet for hele fladen

Det gjorde den i SpS3+ og det er min manglende viden om E-knappen, som gjorde at jeg valgte at sende hele fladen

Ændres til næste version af S4

For at undgå E-knap for fundne matrikelnumre kan du indtil videre udkommentere (//) følgende linie i 
`_s4CustomButtons.push({"buttonText": "Vis ejendomsoplysninger", "buttonImage": _s4eKnapUri, "callBack": s4DoEKnap, "searcher": "geosearcher", "target": "matrikelnumre"});`

Det vil sige ændres til
`//_s4CustomButtons.push({"buttonText": "Vis ejendomsoplysninger", "buttonImage": _s4eKnapUri, "callBack": s4DoEKnap, "searcher": "geosearcher", "target": "matrikelnumre"});` 
eller fjernes helt
