### ISSUE TITLE
Kan ikke fremsøge lokalplan

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#411]
Hvorfor kan jeg ikke fremsøge lokalplan "1174 Else Maries Høj i Alken" i S4?
![lokalplan_s4](https://user-images.githubusercontent.com/21097639/234816468-46867429-120e-4705-8487-87a3d40ba2dc.PNG)

**Comment by puwose** [comment]
Hej Klavs
Er der noget nyt vedr. dette issue?

**Comment by klavspc** [comment]
Kan fremfindes nu - den nye plansøgning er med i næste s4
