### ISSUE TITLE
Linket til BBR meddelelse virker ikke længere

### ISSUE THREAD

**Issue by KKansimm** [Septima/spatialsuite-s4#412]
Jeres link (https://bbr.dk/pls/wwwdata/get_ois_pck.show_bbr_meddelelse_pdf?i_municipalitycode=0101&i_realpropertyidentifier=10805) til BBR meddelelse virker ikke. Måske fordi det er en OIS baseret løsning.
Måske kunne I overveje at benytte dette i stedet??
https://boligejer.dk/bbrmeddelelsepdf?kommuneId=0101&ejendomId=010805

**Comment by klavspc** [comment]
Tak for tippet! Det er løst i næste release - tak
