### ISSUE TITLE
Søgning på ESR-ejendomsnummer i vers. 2.16.1 virker ikke

### ISSUE THREAD

**Issue by mortentj** [Septima/spatialsuite-s4#420]
Hej 

Jeg har installeret den nye s4 version 2.16.1, men jeg kan ikke få søgning på ESR-ejendomsnummer til at virke? BFE virker fint

Mvh. Morten, Roskilde

**Comment by klavspc** [comment]
Jeg ser, at jeg ikke fik skrevet, at der skal søges på komkode+ejendomsnummer (foranstillet "0" i komkode er frivillig)

![image](https://github.com/Septima/spatialsuite-s4/assets/3736091/b01bf5af-4fcc-40d2-92f1-895d74549659)

**Comment by mortentj** [comment]
Perfekt, tak for info:-)

**Comment by KKansimm** [comment]
Dejligt denne mulighed endelig er kommet. 
Vi har selv lavet vores egen alternativ løsning, hvor brugerne ikke skal angive kommunekode foran ejendomsnummeret, derfor hvis vi skal til at overgå til Septimas måde et gøre det på, har vi et ønske om at kommunens eget kommunenummer bliver tilføjet automatisk fra et eller andet parameter.  Er dette muligt ?
Vi tilføjer derudover oplysningen om ejendommen er grund, ejerlejlighed eller bygning på fremmed grund  som I lige overveje at tilføje :-)

**Comment by klavspc** [comment]
> --- kommunekode ... Er dette muligt ?

Ja, det er det og i har jo allerede angivet kommunekode i konfigurationen - det nåede ikke med i denne omgang, men kommer helt sikkert i næste

**Comment by klavspc** [comment]
> det nåede ikke med i denne omgang, men kommer helt sikkert i næste

Og jeg vil også lave søgestrengen mere fleksibel så den f.eks. kan tage mellemrum, " ", istedet for kun bindestreg, "-"

**Comment by ikast-mofri** [comment]
God funktion :-)
Er stødt på en ejendom, der af en eller anden grund kommer med to gange i søgeresultatet, selvom de to resultater ser ud til at være helt ens. Har du et bud på hvorfor?
![image](https://github.com/Septima/spatialsuite-s4/assets/5417678/fac534c5-7cbc-4d23-a98e-1fa410cc0637)

**Comment by klavspc** [comment]
Ikke andet bud end dublet i ESR

Vil ikke undersøge yderligere før der _ikke_ dukker en ejendom op

**Comment by klavspc** [comment]
https://github.com/Septima/septima-search/issues/704

**Comment by klavspc** [comment]
Har rettet op i søgning med esr-nummer
- Ovenstående dublet er fjernet (skyldtes, at der både var et gældende og et foreløbigt bfe-nummer)
- Flere søgestrenge understøttes nu
  - 101-14533 (bindestreg),  
  - 101 14533 (mellemrum), samt   
  - 14533, dvs intet kommunenummer, hvis kommunenummer (municipality) er sat i s4
