### ISSUE TITLE
themesearch

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#421]
Kan man lave søgning, så det er muligt at fremsøge en del af temanavn?
Når man fx søger "udbudte", havde jeg en forventning om at den også fandt "Funktions**udbudte** veje"

![s4_themesearch1](https://github.com/Septima/spatialsuite-s4/assets/21097639/c313a679-aefb-49b5-8911-df2b950824f8)
![s4_themesearch2](https://github.com/Septima/spatialsuite-s4/assets/21097639/077864d7-8bf1-427c-9b80-ddf6ce5db164)

**Comment by klavspc** [comment]
Nej det kan man ikke. Der søges i begyndelsen af ord

Der er nogle muligheder som vi vil se på, men det vil ikke gøre søgningen hurtigere - vi vender tilbage

**Comment by klavspc** [comment]
Jeg har rettet på søgealgoritmen så der faktisk kigges "inde i" ordene. Har forsøgt at ramme en balance så søgningerne ikke bliver for sløve - glæder mig til at høre hvad I synes ved næste release
