### ISSUE TITLE
Efter opgradering til 2.16.1 mangler valgmuligheder under adresse-søgeresultatet

### ISSUE THREAD

**Issue by ikast-mofri** [Septima/spatialsuite-s4#422]
Hidtil (senest ved version 2.15.7) har vi haft disse valgmuligheder, når der er søgt på en adresse:
![image](https://github.com/Septima/spatialsuite-s4/assets/5417678/7320fc7a-c688-465a-9efb-f4801b900d96)

Efter opgradering til version 2.16.1 har vi kun disse muligheder og samtidigt står linket til skråfotos lidt underligt:
![image](https://github.com/Septima/spatialsuite-s4/assets/5417678/54b27438-9175-49d6-adab-340ab5f6129a)

Som jeg har forstået det, så skulle det ikke være nødvendigt at rette i ens opsætning i forbindelse med opgraderingen, men måske har jeg overset et eller andet om dette?

Mvh.
Morten Friis

**Comment by ikast-mofri** [comment]
Hvis jeg sætter dette ind i profilen:

<tool module="s4" name="s4-adresse-plugin">
  <jsonconfig>
    {"links": ["jfa","bbrmeddelelse","boligejer.dk","vurdering","bbkort","ois", "geokoder", "retbbr", "skraafoto", "skraafoto_dataforsyningen", "sdfekort", "plankort"]}
  </jsonconfig>
</tool>

Så får jeg de manglende links, men til gengæld så er flere af dem med to gange.
Hvis jeg helt undlader <tool module="s4" name="s4-adresse-plugin"/>, så får jeg vist disse links:
![image](https://github.com/Septima/spatialsuite-s4/assets/5417678/02024514-ffe7-45ce-ae69-0ca0f581fcd8)

**Comment by klavspc** [comment]
Ja, jeg har rykket lidt rundt på hvilke links, der vises hvor

Med den nye ejendomsvisning flyttede jeg nogle links over til ejendom, hvor jeg synes de hørte mere naturligt til (Vurdering f.eks)

Jeg beklager, at links ikke fremstår med samme navn som før. Vi har lige lagt om og åbenbart ikke fået alle titler gjort helt pæne - det kigger vi på

**Comment by ikast-mofri** [comment]
Det ser ud som om disse kommer med, når jeg sætter plugin'et "s4-adresse-hgf-matrikel-plugin" på - er det ikke en fejl?
![image](https://github.com/Septima/spatialsuite-s4/assets/5417678/6d8ce720-1246-4cd3-b5a6-81d07516151c)

**Comment by petergot** [comment]
Hvad blev konklusionen på de manglende links. Hvad skal vi gøre for at få dem med igen. BBRkort f.eks.
