### ISSUE TITLE
BBR har lukket for ESR nummer søgning i deres kort.bbr.dk (BBRkort) løsning

### ISSUE THREAD

**Issue by KKansimm** [Septima/spatialsuite-s4#432]
URL'en på BBRkort offentlige links kaldet skal ændres, hvor bfe nummer tilføjes til sidst tilsyneladende.
F.eks.

https://kort.bbr.dk/link/esr/0101/6022780?p=722247.619,6178153.402,15&bfe=6022780

**Comment by klavspc** [comment]
Tak - vi retter

**Comment by rastermanden** [comment]
Linket kan forkortes til https://kort.bbr.dk/?bfe=6022780

**Comment by klavspc** [comment]
Vi håber på at få rettelsen ud i denne uge

**Comment by klavspc** [comment]
Link til bbrkort virker igen
