### ISSUE TITLE
Fejlvisning af ESR nummeret ift. BFEnr

### ISSUE THREAD

**Issue by KKansimm** [Septima/spatialsuite-s4#433]
Vi har opdaget flere steder efterhånden af ESR nummeret vises som BFEnr, måske ved ejendomme med blandede ejerskaber.
Typisk hvor der er ejerforeninger med ejerlejligheder.
Her er et par BFEnr som giver samme ESR nummer : 100127143, 6009081, 100409832 .
Kan I lige undersøge om det er fejl eller noget I har valgt ikke at honorer ift ESR??

**Comment by klavspc** [comment]
> ESR nummeret vises som BFEnr

Hvordan? Kan du vedlægge et eksempel?

**Comment by klavspc** [comment]
> Her er et par BFEnr som giver samme ESR nummer : 100127143, 6009081, 100409832

Hvordan giver bfe et esr-nummer? Kan du vedlægge et eksemple?

**Comment by KKansimm** [comment]
Jamen det står allerøverste i det screenshot jeg har sendt til dig???

**Comment by klavspc** [comment]
Ok - så er det løst

Tak skal du have, Andy

Jeg **_finder_** jo korrekt ejendom med bfe 100127143 - jeg kommer bare, fejlagtigt, til at skrive det i parantes som et esr#. Jeg har nu rettet til således, at jeg ikke skriver et fejlagtigt esr# i parantes
