### ISSUE TITLE
Hvad gælder for

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#439]
Vores sagsbehandlere vil gerne bruge S4 til HGF-søgning, og bruger punktet "Hvad gælder for" når de har fundet en adresse

![hgf_valg](https://github.com/Septima/spatialsuite-s4/assets/21097639/a3ebd84d-438e-44fa-9e03-93372eb64373)

Men S4 bruger adressepunktet som inputgeometri til høringen, så rigtig mange konflikter findes ikke, da adressepunktet ligger indeni en bygning.

Jeg er klar over, at de bare kan bruge "Hvad gælder for matrikelnummeret", men de vil gerne have adressen på rapporten.
Kan "Hvad gælder for" funktionen sættes op til at søge via jordstykke?

![hgf_s4](https://github.com/Septima/spatialsuite-s4/assets/21097639/77a8f911-72f7-49ea-bb2b-ae35e9226186)
![hgf_sps](https://github.com/Septima/spatialsuite-s4/assets/21097639/5537d60f-9b1a-4b67-8e08-474e71cf8548)

**Comment by klavspc** [comment]
@puwose : 
Jeg forstår behovet, men er ikke meget for at ændre titlen radikalt. Det _er_ jo matrikelnummeret, der søges med

Hvad siger du til nedenstående forslag:
![image](https://github.com/Septima/spatialsuite-s4/assets/3736091/979e297c-87aa-42c9-9b51-7b3d22f4e31f)


Hvis du kan li' det så udskift **_hele_** indholdet af `s4/tools/s4-adresse-hgf-matrikel-plugin.xml` med (det er kun én linie, der er ændret)
```
<?xml version="1.0" encoding="UTF-8"?>

<tool type="plugin">
    <requires>
    [if: ModuleDefined("s4") ]
        <include src="[module:s4.dir]/tools/s4-requires.xml" nodes="/tool/requires/*" mustexist="true"/>
    [endif]
   </requires>
    <src><![CDATA[
    [if: ModuleDefined("s4") ]
        if (_s4Params.dawasearcher && _s4Params.dawasearcher.enabled){
                var links = this.jsonConfig.links ? this.jsonConfig.links : ["skraafoto_dataforsyningen", "jfa","bbrmeddelelse","ois", "sdfekort", "plankort"];
                _s4Params.dawasearcher.searcher.addDetailHandlerDef(new Septima.Search.OffentligeLinksForAdresseMatrikel({more: false, links: links}));
        }
        var _s4HgfMatrikelKnapUri = Septima.Search.s4Icons.infoIconUri;
        _s4CustomButtons.push({"buttonText": "Hvad gælder for matrikelnummeret", "buttonImage": _s4HgfMatrikelKnapUri, "callBack": s4DawaHgfMatrikelKnap, "searcher": "dawasearcher", "target": "adresse"});
    [endif]
    ]]>
    </src>
    <jssrc><![CDATA[
    [if: ModuleDefined("s4") ]
        function s4DawaHgfMatrikelKnap(result){
            jQuery.ajax({
                url: result.data.properties.jordstykke.href,
                data: {format: "geojson", srid: "25832"},
                success: function(result, data){
                    s4DoInfo({title: data.properties.matrikelnr + ", " + data.properties.ejerlavnavn + " (" + result.title + ")", geometry: data.geometry, searcher: result.searcher});
                }.bind( this, result)
            });
        }
    [endif]
    ]]>
    </jssrc>
</tool>
```

**Comment by klavspc** [comment]
@puwose ?

**Comment by puwose** [comment]
Hej Klavs

Det opfylder behovet, tak :-)

**Comment by klavspc** [comment]
Har oprettet #440 så `s4-adresse-hgf-matrikel-plugin` kan vise info som vist ovenfor
