### ISSUE TITLE
S4 søgninger i det indlejrede kort i ESDH (SBSYS)

### ISSUE THREAD

**Issue by sonjaherning** [Septima/spatialsuite-s4#441]
Vi har tidligere kunnet fremsøge alt hvadb S4 er opsat til.
Nu er der stor forskel på det indlejrede kort i SBSYS og SP.S profilen

Vedlagt billede som det ser ud i Sp.S
![Kort fra SP SPNG](https://github.com/Septima/spatialsuite-s4/assets/169881642/65c24940-9893-4b3a-a5a0-74964532c4da)

Vedlagt billede som det ser ud i det indlejrede kort i SBSYS
![kort fra sbsys](https://github.com/Septima/spatialsuite-s4/assets/169881642/c429034f-6ce2-4543-a8e4-759bb2c19cf7)

Mvh Sonja

**Comment by klavspc** [comment]
Hej Sonja - det ligner to helt forskellige opsætninger af s4. Det ser ud som om det indlejrede kort ikke bruger den profil (sps) som det burde

Første ting, der skal undersøges:

Hvis I har kortet indlejret som IFrame i SBSYS, som jeg tror I har, så  prøv at kalde IFrame-urlen direkte i browseren. Så er det til at se hvad der foregår

**Comment by sonjaherning** [comment]
Hej Klavs
Opsætning i SBSYS
![image](https://github.com/Septima/spatialsuite-s4/assets/169881642/f9238df9-d08a-4fda-a2ac-5011b56ebc02)
Profilen som bliver kaldt er https://kort.herning.dk/spatialmap?profile=gisesdh
Mvh Sonja

**Comment by klavspc** [comment]
Jeg tolker dit bellede som at SBSYS indlæser http://kort.herning.dk/esdh.html i en IFrame. Jeg kan desværre ikke se den side

Forsøg at åbne den i en browser - Du _bør_ nu du se det samme som du ser i SBSYS

- Hvis du ser det samme som i SBSYS så er det åbenlyst forkert profil, som bliver indlæst
- Hvis du ikke ser det samme som i SBSYS så må du tale med dem, der sætter SBSYS op om hvordan de indlæser sps

**Comment by klavspc** [comment]
@sonjaherning : Hvordan går det med denne?

**Comment by sonjaherning** [comment]
Hej Klavs
Jeg er desværre ikke kommet videre
Mvh Sonja

**Comment by DortheBakToefting** [comment]
Hej Klavs
Vi oplever samme problem i Randers som Herning også har rapporteret.

Ren SpS:
![esdh_sps](https://github.com/Septima/spatialsuite-s4/assets/22609617/625333f2-5df2-4b28-9f8c-fc16bd22128f)

SpS i SbSys (chromium-browser):
![esdh_sps_sbsys](https://github.com/Septima/spatialsuite-s4/assets/22609617/fccda6b1-c7bd-48d2-9d84-445e2c34ecc0)

VH Dorthe

**Comment by sonjaherning** [comment]
Hej Dorthe
Ja, det er lidt af et træls problem.
Jeg har også oprettet issue [SPSHEK-507] Problemer med det indlejrede webgis kort i ESDH - Sweco Collaborate Bug and Issue Tracker (gcbit.dk)<https://gcbit.dk/browse/SPSHEK-507>
God dag herfra Herning
Mvh Sonja

Fra: Dorthe Bak Tøfting ***@***.***>
Sendt: 29. maj 2024 09:34
Til: Septima/spatialsuite-s4 ***@***.***>
Cc: Sonja Meyer ***@***.***>; Mention ***@***.***>
Emne: Re: [Septima/spatialsuite-s4] S4 søgninger i det indlejrede kort i ESDH (SBSYS) (Issue #441)


Hej Klavs
Vi oplever samme problem i Randers som Herning også har rapporteret.

Ren SpS:
esdh_sps.JPG (view on web)<https://github.com/Septima/spatialsuite-s4/assets/22609617/625333f2-5df2-4b28-9f8c-fc16bd22128f>

SpS i SbSys (chromium-browser):
esdh_sps_sbsys.JPG (view on web)<https://github.com/Septima/spatialsuite-s4/assets/22609617/fccda6b1-c7bd-48d2-9d84-445e2c34ecc0>

VH Dorthe

**Comment by klavspc** [comment]
Jeg er overbevist om at fejlen opstår fordi den browser som SBSYS starter op (og som viser sps) ikke får lov til at kalde de services, der er brug for (Dawa, datafordeler, GeoSearch, o.s.v.) - Browseren er formentligt startet med en positiv-liste over hvilke services, der må kaldes

Randers kontakter SBSYS med henblik på at gøre det indlejrede kort mindre restriktivt mht hvad der kaldes

**Comment by sonjaherning** [comment]
Hej 
Har Randers fået løst problemet?
Mvh Sonja

**Comment by klavspc** [comment]
> Hej Har Randers fået løst problemet? Mvh Sonja

@DortheBakToefting: Har I fået talt med SBSYS om en mindre restriktiv åbning af Spatial Suite i SBSYS?

**Comment by DortheBakToefting** [comment]
Hej 
Nej, vi har desværre stadigvæk problemet. Vi har møde med leverandøren onsdag morgen og håber at komme videre med en løsning herefter. 
Mvh Dorthe

**Comment by klavspc** [comment]
>Vi har møde med leverandøren onsdag morgen

@DortheBakToefting I er velkomne til at ringe til mig, hvis jeg kan hjælpe. Vis gerne følgende tekst til leverandøren:
> Jeg er overbevist om at fejlen opstår fordi den browser som SBSYS starter op (og som viser sps) ikke får lov til at kalde de services, der er brug for (Dawa, datafordeler, GeoSearch, o.s.v.) - Browseren er formentligt startet med en positiv-liste over hvilke services, der må kaldes

**Comment by sonjaherning** [comment]
@DortheBakToefting Er spændt på at høre resultatiet af jeres møde i går Mvh Sonja

**Comment by DortheBakToefting** [comment]
Vi er ikke nået i mål med en løsning, desværre. Jeg har dog opdaget, at søgefunktionen virker mht. adresser i vores test-miljø som i dag er blevet opgraderet til SbSys version 142. Torsdag opgraderer vi til Sbsys version 141 på produktionen (fra 140) og er spændt på om det vil vise sig at have en positiv effekt.

**Comment by DortheBakToefting** [comment]
Vi er nu på version 142 af Sbsys og det har bevirket at adressesøgning virker igen hos os.

**Comment by sonjaherning** [comment]
)Hej Dorthe  Virker de andre eksterne tjenester også Mvh Sonja

**Comment by klavspc** [comment]
Dejligt, at SBSYS' opdatering har fjernet blokeringen - jeg lukker issuet

**Comment by DortheBakToefting** [comment]
Ja, de andre services fungerer også.
