### ISSUE TITLE
GeoFA plugin til Qgis

### ISSUE THREAD

**Issue by sonjaherning** [Septima/spatialsuite-s4#445]
Hvorfor er alle kolloner ikke med ved indberetning af data, mangler bl.a links etc Pt Så skal vi indberette disse felter i udinaturen.dk eller direkte i GeoFa
Mvh Sonja

**Comment by klavspc** [comment]
Dette er ikke det rigtige sted at oprette issues til GeoFA/Qgis

Lukkes
