### ISSUE TITLE
Filarkiv

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-s4#446]
Hej

Linket via S4 til filarkivet fejler, der kommer denne fejl:
![Skærmbillede 2024-06-12 111126](https://github.com/Septima/spatialsuite-s4/assets/8122296/78f704e1-8ccc-4ce6-831d-67a9d373ad67)

**Comment by klavspc** [comment]
Silkeborg oplever det samme - jeg undersøger

**Comment by klavspc** [comment]
Jeg ville prøve "haderslev2", men det er bare et gæt på hvad JO kan have ændret jeres kommunenavn til

Fra dokumentationen:
```
<!-- ========================================= -->
<!-- S4 mod JO FilArkiv -->
<!-- ========================================= -->
<param name="s4.jo.filarkiv.kommunenavn">xxx</param>

```
Linker til "https://xxx.filarkiv.dk/

**Comment by klavspc** [comment]
>Jeg ville prøve "haderslev2", men det er bare et gæt på hvad JO kan have ændret jeres kommunenavn til

Jeg kan se, at https://haderslev2.filarkiv.dk/ svarer

**Comment by tinadyhr** [comment]
Jeg har prøvet at ændre vores parameter og det virker!

**Comment by sonjaherning** [comment]
Vi har samme problem i Herning
Mvh Sonja

**Comment by dikkri** [comment]
Hvis jeg skriver haderslev2 så kommer jeg rigtig nok på en filarkivside - hvor man kan logge ind. Men vi kan ikke bruge denne side, vores login virker ikke der.
Jeg ved ikke om det er noget vi er på vej til (at bruge haderslev2) - men pt tilgår filarkivet via https://haderslev.filarkiv.dk/ og dette link virker med vores login.

Venlig hilsen
Kamilla Kristensen
GIS-medarbejder

[Haderslev Kommunes logo]
Haderslev Kommune
Teknik og Klima
Christian X's Vej 39 - 6100  Haderslev
Direkte telefon: 24991732
***@***.******@***.***>
www.haderslev.dk

Haderslev Kommune behandler og gemmer alle relevante dokumenter i alle sager elektronisk.
Hvis du vil se de oplysninger, vi har registreret om dig, kan du kontakte afsenderen af denne mail, som vil hjælpe dig videre.
Du kan læse mere om dine rettigheder på https://www.haderslev.dk/databeskyttelse
Fra: Klavs Pihlkjær ***@***.***>
Sendt: 12. juni 2024 12:46
Til: Septima/spatialsuite-s4 ***@***.***>
Cc: Subscribed ***@***.***>
Emne: Re: [Septima/spatialsuite-s4] Filarkiv (Issue #446)


Jeg ville prøve "haderslev2", men det er bare et gæt på hvad JO kan have ændret jeres kommunenavn til

Jeg kan se, at https://haderslev2.filarkiv.dk/ svarer

-

**Comment by klavspc** [comment]
Information fra JO vedr. link til Filarkivet:

> Linket er det rigtige, men vi er i migrationsfase fra gammel til det nye FilArkiv, der desværre tager rigtig lang tid.
> 

> I bliver derfor nødt til at skrive ”2” i linket for at få fat i det nyeste data. Desværre, og jeg ved ikke hvorfor det er valgt sådan.
> 
> Eksempel:
> 
> [silkeborg.filarkiv.dk](http://silkeborg.filarkiv.dk/)                             => det gamle FilArkiv, som ikke bliver opdateret
> [silkeborg2.filarkiv.dk](http://silkeborg2.filarkiv.dk/)                           => det nye FilArkiv


Derfor:

Ret denne parameter indtil det virker:
```
<!-- ========================================= -->
<!-- S4 mod JO FilArkiv -->
<!-- ========================================= -->
<param name="s4.jo.filarkiv.kommunenavn">xxx</param>

```
Linker til "https://xxx.filarkiv.dk/"

Hvis I stadig ikke kan få det til at fungere så kontakt JO
