### ISSUE TITLE
Filarkiv plugin fejler

### ISSUE THREAD

**Issue by puwose** [Septima/spatialsuite-s4#447]
![s4_filarkiv](https://github.com/user-attachments/assets/45026124-f41f-4be5-bae8-8c1d91d57eed)
![s4_filarkiv_search](https://github.com/user-attachments/assets/d368d34d-e3e0-4948-af48-43b99f5807c3)

Cbinfo-param:
    <param name="s4.jo.filarkiv.kommunenavn">skanderborg</param>

Tool i profil:
		<tool module="s4" name="s4-jo-filarkiv-link-plugin" />

**Comment by puwose** [comment]
https://skanderborg.filarkiv.dk/Search/2#P1=Stadionalle&P2=3&P3=1

Url'en plejer at være sådan

**Comment by klavspc** [comment]
Hej @puwose Se [dette issue](https://github.com/Septima/spatialsuite-s4/issues/446) som ligner dit og som JO har kommenteret på

(Kort version:
Prøv skanderborg**2**.filarkiv.dk. Hvis det virker så ret cbinfo-parametren `<param name="s4.jo.filarkiv.kommunenavn">xxx</param>`. Se https://github.com/Septima/spatialsuite-s4/tree/master/tools#s4-jo-filarkiv-link-plugin)
