### ISSUE TITLE
Søgning på vejnavn alene

### ISSUE THREAD

**Issue by Nicolajsen** [Septima/spatialsuite-s4#45]
Det er et ønske for nogle brugere at man kan frem søge en vejstækning ud fra vejnavnet. Rent praktisk vil de gerne at kortet zoomer til vejstrækningen når man klikker på vejnavnet som når man søger en adresse.
Dertil kommer at det ikke for nuværende er muligt at fremsøge veje, hvor der ikke er tilknyttet et adressepunkt.

**Comment by flemmingrasbak** [comment]
Vil man kunne lave datasourcen, så den trækker på vejman.dk's wfs-service?
