### ISSUE TITLE
CHR (Centrale HusdyrbrugsRegister) i søgefeltet

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-s4#87]
Info: https://fvm.glr-chr.dk/portal/page/portal/forside/chr og http://www.foedevarestyrelsen.dk/Leksikon/Sider/Centrale-HusdyrbrugsRegister,-CHR.aspx
Vi i Haderslev Kommune er interesseret i at kunne søge i CHR via S4.
webbaseret søgning findes her: https://chr.fvst.dk/
Er der flere der vil tilslutte sig?

**Comment by klavspc** [comment]
@gis-haderslev: Er du stadig interesseret i at kunne søge i CHR? Er der en søgesnitflade til CHR?

**Comment by gis-haderslev** [comment]
Nej, vi må ligge denne ønske til side, der gevinsten er ikke stor nok.
Du må gerne lukke issuet vi kan altid tager det igen, hvis behovet opstår.
